kiegroup/appformer

livespark-webapp/src/main/resources/ErraiApp.properties
of the number of roles/groups of a user, can be reached. new solution
`patches` the host page (UserHostPageFilter) with user's info that now
is supported on errai client security.
=> BZ-1221380: remove use of cookies (that have 4k limit) what, depending

livespark-common-widgets/livespark-crud-component/pom.xml, livespark-deployment/src/main/java/org/livespark/backend/server/service/build/BuildAndDeployCallable.java, livespark-form-modeler/livespark-form-modeler-codegen/livespark-form-modeler-codegen-impl/src/main/java/org/livespark/formmodeler/codegen/view/impl/java/tableColumns/impl/BooleanBasicTypeColumnMetaGenerator.java, livespark-form-modeler/livespark-form-modeler-codegen/livespark-form-modeler-codegen-impl/src/main/java/org/livespark/formmodeler/codegen/view/impl/java/tableColumns/impl/BooleanColumnMetaGenerator.java, livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/java/org/livespark/formmodeler/renderer/client/rendering/renderers/relations/multipleSubform/columns/impl/BooleanColumnGenerator.java, livespark-integration-tests/src/test/java/org/livespark/codegen/DataModelGenerationTest.java
This PR depends on two PRs in [uberfire-extensions](https://github.com/uberfire/uberfire-extensions/pull/274) and [kie-wb-common](https://github.com/droolsjbpm/kie-wb-common/pull/348).
This PR:
* Uses the "is" prefix for getters of boolean values.
* Uses the new fully qualified name of CheckboxCellImpl (moved in linked PRs).
* Fixes exception when session expires and target directory is deleted before the deployed war file.
* Adds errai-ui as a dependency (no longer brought in transitively).
=> Fix issues with boolean column generation and issue with build service cleanup.

livespark-deployment/src/main/java/org/livespark/backend/server/service/GwtWarBuildServiceImpl.java, livespark-deployment/src/main/java/org/livespark/backend/server/service/build/BaseBuildCallable.java, livespark-deployment/src/main/java/org/livespark/backend/server/service/build/BuildAndDeployWithCodeServerCallable.java, livespark-integration-tests/pom.xml, livespark-integration-tests/src/test/resources/arquillian.xml
The generated app will now be built using the local maven repository set by
the system property "maven.repo.local".
The integration tests are now configured to build the generated app
with the same maven local repo as the integration tests use themselves.
Avoid calling buildAndDeploy multiple times by only dispatching to
the super class a single time. This caused integration tests to intermittently fail
from the generated war file being deployed multiple times.
=> Fixes to integration-test harness + fix a double-deployment bug

livespark-showcase/livespark-webapp/src/main/java/org/livespark/backend/server/FilterProducer.java
This PR filters out generated *.java files from the DataModelerService and prevents the KieBuilder from compiling *.client.local.* classes.
=> Add producer for *.client.local.* and generated class filters.

livespark-showcase/livespark-webapp/pom.xml
The build will fail because the changes are not yet on master -- and livespark PR builds are not configured to run upstream repos first.
=> Fixes after IP BOM 7.0.0.CR4 upgrade

livespark-showcase/livespark-webapp/src/test/java/org/livespark/client/LiveSparkEntryPointTest.java
Call to homeProducer.init(); is made by liveSparkEntryPoint.init(); now.
=> LiveSparkEntryPointTest test fix

appformer-bom/pom.xml, appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/pom.xml, appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/html/inputs/ObjectSelectorTemplateProvider.java, appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/ObjectSelectorBoxHelper.java, appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/test/java/org/kie/appformer/formmodeler/codegen/view/java/inputs/impl/ObjectSelectorBoxHelperTest.java, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-api/pom.xml, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-api/src/main/java/org/kie/appformer/form/modeler/fields/shared/fieldTypes/relations/objectSelector/definition/ObjectSelectorFieldDefinition.java, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-api/src/main/java/org/kie/appformer/form/modeler/fields/shared/fieldTypes/relations/objectSelector/provider/ObjectSelectorFieldProvider.java, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-api/src/main/java/org/kie/appformer/form/modeler/fields/shared/fieldTypes/relations/objectSelector/type/ObjectSelectorFieldType.java, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-api/src/main/resources/ErraiApp.properties, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-api/src/main/resources/org/kie/appformer/form/modeler/fields/FormModelerFieldsShared.gwt.xml, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-api/src/test/java/org/kie/appformer/form/modeler/fields/shared/fieldTypes/relations/objectSelector/provider/ObjectSelectorFieldProviderTest.java, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-client/pom.xml, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-client/src/main/java/org/kie/appformer/form/modeler/fields/client/rendering/renderers/relations/selector/ObjectSelectorFieldRenderer.java, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-client/src/main/resources/ErraiApp.properties, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-client/src/main/resources/META-INF/beans.xml, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-client/src/main/resources/org/kie/appformer/form/modeler/fields/FormModelerFieldsClient.gwt.xml, appformer-form-modeler/appformer-form-modeler-fields/appformer-form-modeler-fields-client/src/test/java/org/kie/appformer/form/modeler/fields/client/rendering/renderers/relations/selector/ObjectSelectorFieldRendererTest.java, appformer-form-modeler/appformer-form-modeler-fields/pom.xml, appformer-form-modeler/appformer-form-modeler-rendering/appformer-form-modeler-rendering-api/pom.xml, appformer-form-modeler/pom.xml, appformer-showcase/appformer-webapp/pom.xml, appformer-showcase/appformer-webapp/src/main/resources/org/kie/appformer/AppFormer.gwt.xml
**WARNING**: to be merged with https://github.com/kiegroup/kie-wb-common/pull/1024 and https://github.com/kiegroup/kie-wb-common/pull/1025
Added ObjectSelector related code, which was removed from kie-wb-common
@pefernan @jsoltes can you give a look?
=> JBPM-6108 ObjectSelector should not appear in Form-modeler editor

uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SideDockItemFocused.java, uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/items/SideDockItemFocusedTest.java
This PR resolves [AF-891 [Data Modeler] Icons are disappearing from the toolbar on the right](https://issues.jboss.org/browse/AF-891) and adds unit tests for the `SideDockItemFocused` class.
@wmedvede, could you please review?
=> Resolve AF-891 and add unit tests for SideDockItemFocused.

uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepositoryTest.java
Custom Maven settings can change the location of local Maven repository.
Therefore it's not safe to always assert it's `${user.home}/.m2/repository`.
=> Fix a test that fails when using custom Maven settings

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-api/src/main/java/org/uberfire/ext/security/management/api/exception/RealmManagementNotAuthorizedException.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-backend/src/main/java/org/uberfire/ext/security/management/service/UserManagerServiceImpl.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/main/java/org/uberfire/ext/security/management/client/ClientSecurityExceptionMessageResolver.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/main/java/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementClientConstants.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/main/resources/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementClientConstants.properties, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/test/java/org/uberfire/ext/security/management/client/ClientSecurityExceptionMessageResolverTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/README.md, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/BaseKeyCloakManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakUserManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/DefaultKeyCloakTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManagerTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakUserManagerTest.java
Hey @ederign @tomasdavidorg 
See [this JIRA ticket](https://issues.jboss.org/browse/AF-483). This commit improves the security management by handling the exceptions when a user is not authorized to manage some realm, and it  displays a user friendly message (instead of the exception). 
Tested in a Keycloak SSO environment as well.
Thanks!
=> AF-483: Security Management - Show friendly message when an operation is not authorized

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementWidgetsConstants.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupCreationWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/BaseRoleEditorWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/BaseUserEditorWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/UserCreationWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowView.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.ui.xml, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/resources/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementWidgetsConstants.properties, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupCreationWorkflowTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflowTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/RoleEditorWorkflowTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/BaseUserEditorWorkflowTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/UserCreationWorkflowTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/UserEditorWorkflowTest.java
Hey @ederign @tomasdavidorg 
See details in [the JIRA ticket](https://issues.jboss.org/browse/AF-467). The change is just about being able to show several notifications in the user editor, rather than a single one (as before this commit), and finally checking the current user assignments in order to display a notification.
Thanks!
Roger
=> AF-467: Security management - Show a warning notification if user has no assignments set.

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataIndexManager.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridCellSelectionsTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridGroupingTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridRowsMergedTest.java
@manstis I changed `org.uberfire.ext.wires.core.grids.client.model.impl.BaseGridData#moveRows` method a little bit and added couple of tests. However one test[1] is still failing. If I keep old implementation of `org.uberfire.ext.wires.core.grids.client.model.impl.BaseGridData#moveRows`  multiple added test will fail, could you please help?
[1]  
`org.uberfire.ext.wires.core.grids.client.model.impl.GridRowsMergedTest#testMergedBlock_MoveRowsUp_Indexes3and4to1`
Ensemble with:
- https://github.com/kiegroup/kie-wb-common/pull/1339
=> DROOLS-1946 Change implementation of moving rows

dashbuilder/dashbuilder-client/dashbuilder-navigation-client/pom.xml, dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/NavigationManager.java, dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/impl/NavigationManagerImpl.java, dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/widget/editor/NavTreeEditor.java, dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/test/java/org/dashbuilder/client/navigation/widget/editor/NavTreeEditorTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/htmleditor/HtmlEditorPresenter.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/htmleditor/HtmlEditorView.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/ConfigurationContext.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditHTMLPresenter.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditHTMLView.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditHTMLPresenterTest.java
See: https://issues.jboss.org/browse/RHDM-219
---
---
Regarding the [ignored exception](https://github.com/Voog/wysihtml/blob/26a85fc0e51bde077c23bcdcbdc0549f34341e0c/lib/rangy/rangy-core.js#L1318), it was introduced by the `wysihtml` [version update](https://github.com/kiegroup/appformer/commit/24423b31654e74739f2e2af0c0c3f0f26eecce34#diff-620e02db07d901ae62cd35ca89329df4). Since everything still works as expected and the lib is in a beta version, I think that we can wait for a more stable API and ignore the exception for now.
The fix refers to loading and destroying the `wysihtml` editor everytime we show and hide the modal, respectively.
---
- https://github.com/kiegroup/appformer/pull/134
- https://github.com/kiegroup/kie-wb-distributions/pull/668
=> [7.5.x] [Content Management] HTML panel causes errors when saving & when adding page to navigation tree

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/BearerAuthenticationInterceptor.java
Hey @ederign 
This is the fix for [RHDM-233](https://issues.jboss.org/browse/RHDM-233). It's just removing the resteasy annotations for that interceptor, this way it will not intercept other requests rather than the keycloak admin area related ones (as it's already being registered programatically for that kind of requests [here](https://github.com/kiegroup/appformer/blob/master/uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/Keycloak.java#L45))
@tomasdavidorg As you was facing with this issue, probably you can give it a look as well, if you have a chance.
PS: This is a critical issue targeted for RHDM 7.0.GA. So creating the PR for `7.5.x`, next step will be …
=> [7.5.x] RHDM-233: Do not register the KC security management authentication client interceptor by default

uberfire-message-console/uberfire-message-console-client/pom.xml, uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleService.java, uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceRow.java, uberfire-message-console/uberfire-message-console-client/src/test/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceRowTest.java, uberfire-message-console/uberfire-message-console-client/src/test/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceTest.java
See https://issues.jboss.org/browse/AF-972
(Product JIRA https://issues.jboss.org/browse/RHDM-295)
This is the corollary of https://github.com/kiegroup/appformer/pull/144 for 7.5.x
(cherry picked from commit 52ee57a846d4e84106d6a89d4f3f98168ff17e7f)
(cherry picked from commit 58a72d1b036cf1a5f0cfd28ec5079afd83b2be76)
=> [7.5.x] AF-972: Wrong order of the validation messages

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProviderTest.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/ComplexFieldsTest.java
With @paulovmr fixed the issues below:
https://issues.jboss.org/browse/RHDM-306
https://issues.jboss.org/browse/RHDM-307
https://issues.jboss.org/browse/RHDM-309
There was a problem with colons in urls (it seems it's an ES problem with query strings). So now every project have their own assets.
It also fixes a problem with an error that appeared when creating some assets. It was a sort that contains a null field. In lucene that enables the "sort by doc number", but in ES that is by default so we omitted those sort field that are null.
@ederign could you review?
=> [RHDM-306, RHDM-307, RHDM-309]

uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceExecutorService.java, uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceScopeContext.java, uberfire-backend/uberfire-backend-cdi/src/test/java/org/uberfire/backend/server/cdi/WorkspaceBuilderServiceImpl.java
Threads used to contain usernames to debug what workspace was running there. I removed those debug names.
@ederign, can you review it please?
=> [RHDM-308]: Fixed issue with thread names

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProviderTest.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/ComplexFieldsTest.java
With @paulovmr fixed the issues below:
https://issues.jboss.org/browse/RHDM-306
https://issues.jboss.org/browse/RHDM-307
https://issues.jboss.org/browse/RHDM-309
There was a problem with colons in urls (it seems it's an ES problem with query strings). So now every project have their own assets.
It also fixes a problem with an error that appeared when creating some assets. It was a sort that contains a null field. In lucene that enables the "sort by doc number", but in ES that is by default so we omitted those sort field that are null.
@ederign could you review?
=> [RHDM-306, RHDM-307, RHDM-309]: Fixed filtering issues and duplicated assets in different projects. Only include not null sort fields.

uberfire-test-utils/src/main/java/org/guvnor/test/CDITestSetup.java
Running tests which use the CDITestSetup on jenkins sometimes cause NPE in the weld cleanup. Such class and NPE:
- org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest
- https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-wb-pullrequests-7.5.x/46/testReport/org.drools.workbench.screens.dtablexls.backend.server/DecisionTableXLSServiceImplCDITest/testValidateColumnsNotInStandardOrder/
@manstis please have a look,
Ensemble with:
kiegroup/drools-wb#794
=> DROOLS-2218: Log NPE during weld cleanup

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataSelectionsManager.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridCellSelectionsTest.java
See https://issues.jboss.org/browse/DROOLS-2303
@jomarko This fix also applies to Guided Decision Tables where it too was possible to select a "row" and then insert a new column that was then not included in the selected row.
=> DROOLS-2303: [DMN Designer] Add column to whole row outline

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManager.java
the path manipulation was weak, now it's using direct path (nio2) api to manipualte and extract repository name
=> AF-989: the path manipulation wasn't working on windows paths

pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-bayesian-network/uberfire-wires-bayesian-network-client/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-api/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-client/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-scratchpad/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-trees/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml
Hey @mbiarnes @tiagodolphine @manstis 
Created ticket and branches with same names for doing the right Jenkins integration tests. 
See https://issues.jboss.org/browse/JBPM-6806
NOTE: Found that the decision tables depend on some `uberfire-wires` artifacts, so finally updated wires dependencies for using the KIE Lienzo modules as well.
Please **DO NOT MERGE** yet.
Thanks!
=> [DO NOT MERGE] JBPM-6806: Included KIE Lienzo artifacts into the dependency management.

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/BusyIndicatorView.java
[ERRAI-1095](https://issues.jboss.org/projects/ERRAI/issues/ERRAI-1095) prevents callbacks from invoking on Errai callers after the enclosing bean is destroyed. A possible side-effect is that some beans can be closed before they hide popups, causing the popups to remain indefinitely. This prevents that issue for loading popups created with the `BusyIndicatorView`.
=> Close busy popup when view closed to prevent issues from ERRAI-1095

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java
When moving the last element of a row, the empty row wasn't removed. This change triggers the row removal every time the last column is removed from a row, doesn't matter if it's because a removal or because a move.
@jsoltes @dgutierr could you please review?
=> AF-599: When adding fields next to each other, each field leaves empty row behind.

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUploadBase.java
Notifications should be handled in success/error callbacks in a way
it is "native" to target system.
=> Remove useless alerts for Upload editor.

uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
Hi @paulovmr,
this test has been failing for a long time on our Jenkins against productized binaries with 
`java.security.NoSuchAlgorithmException: class configured for SSLContext: sun.security.ssl.SSLContextImpl$DefaultSSLContext`
I think that this should fix the issue and should not break anything. Could you, please, take a look at this?
=> fix GuvnorM2RepositoryTest

uberfire-test-utils/src/main/java/org/guvnor/test/CDITestSetup.java
Running tests which use the CDITestSetup on jenkins sometimes cause NPE in the weld cleanup. Such class and NPE:
- org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest
- https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-wb-pullrequests-7.5.x/46/testReport/org.drools.workbench.screens.dtablexls.backend.server/DecisionTableXLSServiceImplCDITest/testValidateColumnsNotInStandardOrder/
=> [7.5.x] DROOLS-2218: Log NPE during weld cleanup

pom.xml, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/pom.xml, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/AbstractFileExport.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/FileExportProducer.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/FileExportResources.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/FileExportScriptInjector.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2S.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2D.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SSettings.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/Context2DFactory.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/IContext2D.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/SvgExportSettings.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/SvgFileExport.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/AbstractFileExportTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/ImageFileExportTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/jso/FileExportScriptInjectorTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2DTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/svg/Context2DFactoryTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/svg/SvgFileExportTest.java
_Stunner_ needs to export diagrams presented on canvas to SVG files, the idea is to add this feature and an abstraction of canvas and the library implementation used for that on _Uberfire,_ in this way any other components that need to export a canvas to SVG may use this feature.
* Added a `FileExport` implementation to support SVG on `SvgFileExport`
* Abstraction interface to the Context2D that is used to generate the SVG
* _JsInterop_ to the library **[canvas2svg](https://github.com/gliffy/canvas2svg)** with an overlay to distinguish save/restore from groups, that is the containers nodes, the idea is to open a PR to add this feature on the native canvas2svg, then we could remove the overlay
* _Webjar_ configuration to **canvas2svg**
Related JIRA https://issues.jboss.org/browse/JBPM-6110 …
=> JBPM-6110 - Adding support to export a canvas context to SVG

dashbuilder/src/main/config/zanata.xml
since dashbuilder is in appformer (so in uberfire) it doesn't make sense to have different Zanata projects. There is right now existing a Uberfire 2.0.0 and Dashbuilder UF 2.0.0 as Zanata projects.
=> updated to correct Zanata version

uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
Prevent Jenkins fail with:
**Error Message**
```
loader constraint violation: loader (instance of org/powermock/core/classloader/MockClassLoader) previously initiated loading for a different type with name "javax/security/auth/x500/X500Principal"
```
**Stacktrace**
```
java.lang.LinkageError: loader constraint violation: loader (instance of org/powermock/core/classloader/MockClassLoader) previously initiated loading for a different type with name "javax/security/auth/x500/X500Principal"
at org.guvnor.m2repo.backend.server.GuvnorM2RepositoryTest.setup(GuvnorM2RepositoryTest.java:134)
```
=> [7.7.x] Fix for internal QE Jenkins

uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
Prevent Jenkins fail with:
**Error Message**
```
loader constraint violation: loader (instance of org/powermock/core/classloader/MockClassLoader) previously initiated loading for a different type with name "javax/security/auth/x500/X500Principal"
```
**Stacktrace**
```
java.lang.LinkageError: loader constraint violation: loader (instance of org/powermock/core/classloader/MockClassLoader) previously initiated loading for a different type with name "javax/security/auth/x500/X500Principal"
at org.guvnor.m2repo.backend.server.GuvnorM2RepositoryTest.setup(GuvnorM2RepositoryTest.java:134)
```
=> Fix for internal QE Jenkins

uberfire-api/src/main/java/org/uberfire/backend/vfs/PathFactory.java, uberfire-client-api/src/main/java/org/uberfire/client/mvp/RenameInProgressEvent.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/common/SaveAndRenameCommandBuilder.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorRenameTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/common/SaveAndRenameCommandBuilderTest.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/LockManagerTest.java
See https://issues.jboss.org/browse/RHBA-415
Before:
After:
---
- https://github.com/kiegroup/appformer/pull/275
- https://github.com/kiegroup/drools-wb/pull/842
=> RHBA-415: After rename, designer is not marked as dirty more

dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreen.java, dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreenTest.java
=> [7.7.x] AF-1119: "Are you sure you want to discard unsaved data?" Displayed

uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/engine/IndexerScheduler.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/provider/LuceneIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/ConstrainedIndexerScheduler.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/index/MetadataIndexEngine.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/common/IOServiceIndexedTest.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/common/MetadataIndexEngineBatchTest.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/common/util/TestFileSystemProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
The RHBA-593/AF-1106 fix ensures that watch services are removed when a filesystem is destroyed, so that a new filesystem created with the name of a delete FS does not use a stale watch service.
The other commit is small code-style fixes suggested by @ederign for the AF-1084 PRs.
=> RHBA-593/AF-1106 fix + minor code-style fixes for AF-1084

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/VFSServicesServerImpl.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/VFSServicesServerImplTest.java
Hey @ederign @hasys 
From Stunner I'm now using the uberfire `VFSService` and just realized it's missing to pass the filter in a method... that's the fix. 
Thx!
=> JBPM-7089: Fix VFSService missing filter delegate

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/widget/BreadcrumbsView.css, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/widget/BreadcrumbsView.java
Changing the css styles to have only cursor over the breadcrumb links
=> JBPM-6907: Last breadcrumb element should be text only

uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/context/WorkspaceProjectContext.java, uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/context/WorkspaceWorkspaceProjectContextTest.java
The error happened when saving contributor in Contributors Tab. In that moment an UpdatedOrganizationalUnit event is thrown, and it contains the Organization Unit updated. 
WorkspaceProjectContext observes that event and update the context, but in that method all values are set to null but Organizational Unit.
I kept with the old active values but organizational unit because that is the only one that changed.
@barboras7 @Rikkola would you mind to review it please?
=> [AF-1091]: Fixed error that appears after using the Contributors tab

uberfire-extensions/uberfire-preferences-ui-client/src/main/java/org/uberfire/ext/preferences/client/admin/AdminPagePerspective.java, uberfire-extensions/uberfire-preferences-ui-client/src/test/java/org/uberfire/ext/preferences/client/admin/AdminPagePerspectiveTest.java
Cherry-picked from https://github.com/kiegroup/appformer/pull/315
=> [7.7.x] AF-1171: "Reset All perspective layouts" button breaks the "Settings" and "Library" perspectives

uberfire-commons/pom.xml, uberfire-commons/src/main/java/org/uberfire/commons/cluster/events/ClusterEventObserver.java, uberfire-commons/src/main/java/org/uberfire/commons/cluster/events/ClusterSerializedCDIMessageWrapper.java, uberfire-commons/src/main/java/org/uberfire/commons/clusterapi/Clustered.java, uberfire-commons/src/main/resources/org/uberfire/commons/UberfireCommons.gwt.xml, uberfire-commons/src/test/java/org/uberfire/commons/cluster/events/ClusterEventObserverTest.java, uberfire-extensions/uberfire-social-activities/uberfire-social-activities-backend/src/main/java/org/ext/uberfire/social/activities/persistence/SocialClusterMessaging.java, uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/events/NewProjectEvent.java
Now CDI Events are also distributed in the cluster.
Just annotate your @Portable events with @Clustered and Appformer will replicate them on each node.
@tomasdavidorg to test this, on cluster env. open the library on each node and add some projects and spaces. If they appear on other nodes this mechanism is working.
The CDI event that is being distributed in this POC is the NewProjectEvent. (later PRs will propagate other  important events)
ps: This PR doesn't yet cover the sync of deleted spaces/projects/files. This will be addressed in later work.
=> [AF-1141] Distributed CDI Events on Cluster

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/AbstractLayoutEditorTest.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java
Backport of https://github.com/kiegroup/appformer/pull/326
@dgutierr @kkufova could you please take a look?
=> [7.7.x] AF-1184: [Layout editor] Moving any component on canvas breaks Layouteditor

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2S.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2D.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/IContext2D.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2DTest.java
JBPM-7145 changes to support SVG backend export, allow adding attributes to SVG groups.
It is necessary to add the BPMN id to SVG groups, so it was inserted on the saveGroup method that is an JsOverlay to the **canvas2svg**  lib.
Stunner will use this feature to save the diagrams SVG on the VFS.
@romartin 
@LuboTerifaj
=> JBPM-7145 allow SVG persisted on backend (Stunner)

dashbuilder/dashbuilder-packaging/dashbuilder-client-all/pom.xml
This change allows to consume Dashbuilder's client artifacts via the `dashbuilder-client-all` BOM.
Related PRs:
kiegroup/droolsjbpm-build-bootstrap/pull/753
kiegroup/appformer/pull/350
kiegroup/optaplanner-wb/pull/279
=> PLANNER-1026 Add sources artifacts to dashbuilder-client-all BOM

uberfire-server/src/main/java/org/uberfire/server/BaseUploadServlet.java, uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
Ensure BaseFileUploadServlet creates the file in a batch.
See https://issues.jboss.org/browse/JBPM-5813 (more specifically the reported issue on the Product [JIRA](https://issues.jboss.org/browse/RHPAM-447?focusedCommentId=13576647&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13576647)).
=> JBPM-5813: Stunner - Open XML editor instead of sorry screen when process can't be opened

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitVersionAttributeView.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/GitImpl.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/ListCommits.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/model/CommitHistory.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitHistoryTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitSubdirectoryCloneTest.java
Fixes `ListCommits` command to follow path name changes, and maps version records to correct paths of renamed files.
Note that there are issues with some editors when trying to view previous versions of moved files. One that I encountered is with the data modeller. That editor produces two commits when moving a file. One renames the Java class and the other moves the file. If you try checking out the commit that renames the Java class, the data modeller cannot load the class, presumably because the class name and file name do not match. We might want to make a JIRA issue to ensure that rename operations are committed atomically. //cc @wmedvede
=> AF-1186: Versions history is lost after asset rename

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2S.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2D.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/IContext2D.java
Changes to support Diagram SVG is not highlighted on the WB (jbpm-process-svg widget).
Insert the node id in the same way it was done for the containers.
PS: unit tests will be updated later, the PR is to be tested ASAP since this is a blocker.
@romartin 
@LuboTerifaj
=> JBPM-7245  Diagram SVG is not highlighted on the WB

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
Cherry-picked from https://github.com/kiegroup/appformer/pull/389.
=> [7.7.x] AF-1227: Library content is not visible when Projects link is clicked

pom.xml, uberfire-backend/uberfire-backend-cdi/pom.xml, uberfire-security/uberfire-security-api/pom.xml
- Remove unused dependencies.
- Declare used dependencies instead of relying transitive dependencies.
- Remove javax.validation:validation-api, which is already managed
by IP BOM.
- Remove javax.annotation:jsr250-api exclusion because cdi-api no longer
depends on it.
=> Improve dependencies in uberfire-backend-cdi and uberfire-security-api

uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java, uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
AF-1233: Manually added dependencies do not show up in Dependencies
AF-1236: Newly created persistable data objects are not automatically added to the list of Project Persistable Data Objects
AF-1237: Project duplication should use the suffix "-2" instead of " [2]"
* https://github.com/kiegroup/appformer/pull/393
* https://github.com/kiegroup/kie-wb-common/pull/1862
=> [7.7.x] Settings fixes

uberfire-server/src/main/java/org/uberfire/server/BaseUploadServlet.java, uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
Ensure BaseFileUploadServlet creates the file in a batch.
See https://issues.jboss.org/browse/RHPAM-447 (more specifically [this](https://issues.jboss.org/browse/RHPAM-447?focusedCommentId=13577472&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13577472)).
This is the corollary of https://github.com/kiegroup/appformer/pull/359 for 7.7.x
(cherry picked from commit 95dbbd17e67330efebc4f1f911bb206ae39a53fe)
=> [7.7.x] RHPAM-447 (JBPM-5813): Stunner - Open XML editor instead of sorry screen when process can't be opened

uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java, uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
AF-1233: Manually added dependencies do not show up in Dependencies
AF-1236: Newly created persistable data objects are not automatically added to the list of Project Persistable Data Objects
AF-1237: Project duplication should use the suffix "-2" instead of " [2]"
* https://github.com/kiegroup/appformer/pull/392
* https://github.com/kiegroup/kie-wb-common/pull/1861
=> Settings fixes

uberfire-io/src/test/java/org/uberfire/io/impl/BatchTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystem.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImpl.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProxy.java
The story begins [here](https://issues.jboss.org/browse/RHPAM-559
). 
Data modeler code does the following: 
1. create a file with content (A.java);
2. Rename this file;
2.1 Start a batch();
2.2 Rename this file A.java -> B.java (one git commit)
2.3 Change the content of this file in the refactoring process; (one git commit)
2.4 Close batch 
The issue is that instead of a renaming(a->b) + modify event(b) they are receiving a delete on a and created in b.
@wmedvede did a great job helping me isolating this issue and what happening is that our VFS in batch mode does a amend of each commit and in the end batch process compare the three in 2.1 with the tree in 2.2 and get the 'wrong' events (or at least a compressed vision of the timeline).
The problem is that on git, when I do the same in …
=> [AF-1238] FileSystem Watch Events should reproduce all the history on BatchMode

pom.xml
The requirement now is to use only Final versions of dependencies for community or product.
=> upgraded to errai Final version

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchLayoutInfoImpl.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/WorkbenchLayoutInfoImplTest.java
https://issues.jboss.org/browse/AF-1252
When we default to 0 it just means the notification shows up in the top of the screen.
I believe this fixes at least:
- RHPAM-990
- RHPAM-1133
- RHPAM-1136
ping @jomarko @tomasdavidorg @barboras7
=> AF-1252 : Notification event throws NPE in standalone mode when using IE

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchLayoutInfoImpl.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/WorkbenchLayoutInfoImplTest.java
(cherry picked from commit e006d2d240705aafba0b99abb0e409e0b6106c5d)
https://issues.jboss.org/browse/AF-1252
@jomarko @tomasdavidorg @barboras7 Same as the one for master. Making this early to get green builds in time.
https://github.com/kiegroup/appformer/pull/403
=> [7.7.x] AF-1252 : Notification event throws NPE in standalone mode when using IE

uberfire-server/src/main/java/org/uberfire/server/BaseUploadServlet.java, uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
- Removes unnecessary ioService.createFile(xxx) invocation for later writing the file content with ioService.write(xxx)
=> [7.7.x] RHPAM-994: Stunner - Error popup appears once importing some processes

dashbuilder/dashbuilder-webapp/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml, uberfire-showcase/uberfire-client-webapp/pom.xml, uberfire-showcase/uberfire-webapp/pom.xml
Hello @ederign,
I'm introducing a new profile that will enable to skip gwt compilation of showcases in downstream-pullrequests jobs. In normal build, nothing is skipped. Only when you add -Pno-showcase to mvn command line, the showcases won't be gwt-compiled.
https://github.com/kiegroup/jbpm-wb/pull/1160
https://github.com/kiegroup/kie-wb-common/pull/1917
https://github.com/kiegroup/drools-wb/pull/877
https://github.com/kiegroup/appformer/pull/401
=> AF-1248: Add profile to enable skipping of gwt compilation of showcases

uberfire-server/src/main/java/org/uberfire/server/BaseUploadServlet.java, uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
- Removes unnecessary ioService.createFile(xxx) invocation for later writing the file content with ioService.write(xxx)
(cherry picked from commit 34d83fe1b86e15785dddc3d1b44ef22cee478f8d)
=> JBPM-7268: Stunner - Error popup appears once importing some processes (#396)

uberfire-io/src/test/java/org/uberfire/io/impl/BatchTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
Tomas and Porcelli.
The post-commit hook was not called in VFS batch mode. This is fixed by this PR.
This doesn't fix the 'create project hook' because there is no hook for 'creating project'. But we do some commits in the project creation, so probably user can track those on this case.
Tomas, in order to test it:
a1 is the project name.
➜  /tmp cd fs-drools-wb/.niogit/a1/a1.git
➜  a1.git git:(master) ls
HEAD     branches config   db.lock  hooks    logs     objects  refs
➜  a1.git git:(master) cd hooks
➜  hooks git:(master) ls
post-commit
➜  hooks git:(master) cat post-commit
date >> /tmp/hookCalledg
To place the hooks automatically on new repos:
-Dorg.uberfire.nio.git.hooks=/tmp/hooks
But only do this with all the system repos already created. You don't want to have hooks on those. :-)
=> [AF-1401] Some user actions don't fire post-commit hook: create data object, modify data object

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java
The old method was overriding af default resize handler : https://github.com/kiegroup/appformer/blob/2b157a2ca6f8e4f2c2a9b02fc5cb731b1ddc64a4/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java#L244
=> [AF-1396] Asset editors don't resize with window size change

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseColumnRendererTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/IntegerColumnRendererTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/StringColumnRendererTest.java
See https://issues.jboss.org/browse/DROOLS-2792
This PR adds support for more than one text value to be rendered in the Header cells.
=> DROOLS-2792: [DMN Designer] Data-types: Grid: LiteralExpression. Allow different Header content to be rendered.

uberfire-extensions/uberfire-security/uberfire-servlet-security/src/main/java/org/uberfire/ext/security/server/CleanupSecurityCacheSessionListener.java, uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/CleanupSecurityCacheSessionListenerTest.java, uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/io/IOServiceSecuritySetupTest.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/authz/AuthorizationManager.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/authz/PermissionManager.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationManager.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthzResultCache.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultPermissionManager.java, uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/AuthorizationManagerTest.java, uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/DefaultAuthzResultCacheTest.java, uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/PermissionManagerTest.java
@domhanak @ederign bringing feature to master 
looks like due the changes that @dgutierr was executing on security, this feature was postponed and never revisited.
=> AF-923: cache invalidation on session expire/logout for security related info

pom.xml, uberfire-bom/pom.xml
jboss-ip-bom 8.1.0.Final is identical to 8.1.0.CR2 - we had to do this as prod will work only with Final versions. In future there won't be anymore CRs for jboss-ip-bom - only Final versions.
=> upgraded jboss-ip-bom to 8.1.0.Final

uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
There was a NPE when trying to delete _src/main/.java_ from index, but those files are not directly indexed as they are. They are converted to _src/main/java_, so we can't delete a _.java_ that is not there. 
I added that check so now it will not try to delete dot files from index.
=> [AF-1544]: Dot files are not indexed, so dot files condition added before queueing delete events

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyGroupPropertiesManager.java
@ederign please check. When WildflyGroupPropertiesManager fails to initialize (when groups.properties files is not found) `groupsPropertiesFileLoader` is null. This leads to unnecessary NPE thrown from the `destroy()` method on container shutdown. This is happening quite often when running tests using cargo which doesn't have the group file in the correct location (And it's OK because it doesn't need it) and it's spamming the console.
Also fixed exception message that wasn't showing the contents of the varargs argument - as it was it was only showing argument as `[Ljava.lang.String;@25154f`
<details>
<summary>Exception</summary>
<pre>
[talledLocalContainer] 13:40:00,761 ERROR [org.uberfire.ext.security.management.BackendUserSystemManager] (MSC service thread 1-5) UserManagementService …
=> Prevent NPE in WildflyGroupPropertiesManager

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/common/PortUtil.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/git/Daemon.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHService.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderHookTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderSSHBadConfigTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/daemon/common/PortUtilTest.java
Avoid port failure if already in use, by automatically assigning a new available port in case of preferred port isn't available.
This change should improve our testing infrastructre, avoiding what's called `randon` test failures.
Docs: https://github.com/kiegroup/kie-docs/pull/1157
=> AF-1585: avoid port failure if already in use, by automatically assigning a new available port

pom.xml, uberfire-backend/uberfire-backend-server/pom.xml, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/PropertiesLineWriterPredicate.java
Upgrate to Wildfly 14
There is a concern related to SNAPSHOT version that will be solved in jboss-integration-platform-bom
@ederign would you mind to review?
Here is kie-wb, https://www.dropbox.com/sh/54ngqqacaqjh2f9/AADoeCmukZ7xytqTpYJCTfEma?dl=0
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* …
=> [AF-1555]: Upgrade to Wildfly14

pom.xml
My previous PR caused some errors in kie-wb-common and drools-wb like:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-blacklisted-dependencies) @ drools-wb-guided-dtable-editor-api ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
Found Banned Dependency: commons-logging:commons-logging:jar:1.1.1
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```
=> Fix enforcer error about commons-logging

pom.xml
These overrides are no longer needed, because the versions in question have already been migrated to jboss-integration-platform-parent
```
uberfire-parent overrides 'version.com.google.guava' defined in jboss-integration-platform-parent from '20.0' to '20.0'
uberfire-parent overrides 'version.com.google.gwt' defined in jboss-integration-platform-parent from '2.8.2' to '2.8.2'
uberfire-parent overrides 'version.commons-cli' defined in jboss-integration-platform-parent from '1.3.1' to '1.3.1'
uberfire-parent overrides 'version.org.apache.sshd' defined in jboss-integration-platform-parent from '1.6.0' to '1.6.0'
uberfire-parent overrides 'version.org.eclipse.jgit' defined in jboss-integration-platform-parent from '4.8.0.201706111038-r' to '4.8.0.201706111038-r'
uberfire-parent overrides …
```
=> Remove useles property overrides

dashbuilder/dashbuilder-distros/pom.xml, dashbuilder/dashbuilder-distros/src/main/assembly/assembly-tomcat-8.xml, dashbuilder/dashbuilder-webapp/pom.xml, uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-parent-with-dependencies/pom.xml, uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/pom.xml, uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml, uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml, uberfire-nio2-backport/uberfire-nio2-api/pom.xml, uberfire-showcase/showcase-distribution-wars/pom.xml, uberfire-showcase/showcase-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml, uberfire-showcase/uberfire-client-webapp/pom.xml, uberfire-showcase/uberfire-webapp/pom.xml
You can check for yourself by running this in the appformer repo:
`grep 'org.slf4j.*' -r --include=*.java -o -h | sort | uniq`
You'll see that we're only ever using from slf4j is Logger and LoggerFactory that come from slf4j-api
If you're curious which functionality slf4j-ext (which we don't use) provides, you can check its [website](https://www.slf4j.org/extensions.html).
=> Remove slf4j-ext which is not user anywhere

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/GridCell.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetEditCellMouseEventHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetEditCellMouseEventHandlerTest.java
Fix regression found in Guided Decision Table.
This PR also includes a fix for when `scesim` sets a Grid to `selected` before it is visible.
Tested with DMN, Guided Decision Table and Scenario Simulation Editors. All good.
=> DROOLS-2910: [DMN Designer] Update cell (double-)click interactions

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Clone.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitCloneTest.java
Wrong config:
[remote "origin"]
url = https://github.com/porcelli/SampleTest.git
fetch = +refs/:refs/
mirror = true
Config updated:
Config via a git clone uri
Config of a sample repo cloned (not mirrored)
To test the use case:
Import a repo (i.e. https://github.com/ederign/KieDora.git ) 
Add a hook like this one:
Do a commit in the repo, see the remote repo updated (but your user should have ssh keys configured and write access to this repo.
=> AF-1636 - Imported projects have wrong config on Git repository config

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchLayoutImpl.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/events/WorkbenchProfileCssClass.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/WorkbenchLayoutImplTest.java
@jesuino @jhrcek does that works for you?
https://cl.ly/90d703c9cfea/%255B6fa93efe9abf842e880d3dfec28d4e8e%255D_Image%2525202018-11-27%252520at%2525207.22.09%252520PM.png
@jesuino please fire the event when the profile is selected/changed (also on startup)
@jhrcek $('.uf-workbench-layout') is a selector that will containg the css class.
=> [AF-1725] Make it possible to identify currently enabled business-central profile (for selenium testing)

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/SanitizedNumberInput.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/SanitizedNumberInputTest.java
New component - input that allows only numbers (and optionally minus sign and/or decimal point) to be typed. 
Issue: [AF-1036](https://issues.jboss.org/browse/AF-1036)
Two things to note:
- `<input type="number">` is already sanitized by default in Google Chrome (but Chrome also allows you to type in "e" and a plus sign)
- in Firefox it is possible to enter an invalid character using a compose key (e.g. Compose + o + a => å), even cancelling all keyboard events does not prevent this.
=> AF-1036: implement sanitized number input

uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryRemovedEvent.java
@jhrcek Added Clustered to DeleteProjectEvent. Now, when a project is deleted all nodes of the cluster are informed. If they are in the same View and any node deletes the project, view is closed and all return to LibraryView.
=> [AF-1713]: Added clustered event when deleting project

pom.xml
Same case as https://github.com/kiegroup/kie-soup/pull/78
Move the extra-enforcer-rules version to 1.0 so that the dependency is available from maven central
=> Update the extra-enforcer-rules version to 1.0

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/ColumnIndexUtilities.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetKeyboardHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/ColumnIndexUtilitiesTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetKeyboardHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java
Dependent on #558 
Ensemble with:
- kiegroup/kie-wb-common#2200
- kiegroup/drools-wb#968
=> DROOLS-2932: Extend KeyboardOperations to support header cells navigation

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/CreateRepository.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitForkTest.java
To test this:
Current behavior:
1-) Open BC and create some repos without git hook dir defined.
2-) Shutdown BC and setup git hooks template dir -Dorg.uberfire.nio.git.hooks=/tmp/hooks
3-) Run BC and see ALL repos with hooks:
After this PR:
1-) Open BC and create some repos without git hook dir defined.
2-) Shutdown BC and setup git hooks template dir -Dorg.uberfire.nio.git.hooks=/tmp/hooks
3-) Run BC and only new repos has the template.
=> Configs and hooks of the repository should be preserved

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/FileExportScriptInjector.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/JsFileSaver.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/JsPdf.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/jso/FileExportScriptInjectorTest.java
The problem was caused after any exception on client, the native libraries used on the export was not working anymore, seems that they were unloaded, getting NPE when trying to acess them on all the export formats.
**Solution:** 
Changed the native libs that use JsInterop setting the namespace **GLOBAL**:
`@JsType(isNative = true, namespace = JsPackage.GLOBAL)`. 
Some adjustments were necessary on the `FileExportScriptInjector` to make these changes work.
Now if we get any exception on client, it is still possible to export Diagrams without any error, the native libraries are still loaded as expect.
@romartin @hasys
=> JBPM-7855 - Stunner cannot export diagrams (after any exception on client)

dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/pom.xml, dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/exports/NativeLibraryResources.java, dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/exports/ResourcesInjector.java
Removed C3 default CSS and let patternfly C3 CSS take over.
=> AF-1758: Use Patternfly C3 CSS classes instead injecting C3 CSS

dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/pom.xml, dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3Displayer.java, dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3DisplayerView.java, dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/test/java/org/dashbuilder/renderer/c3/client/C3DisplayerGeneralTests.java
Fixing noData state. Now when there's no data the chart won't even attempt to render, instead it will show a no data info. This fixes the bubble chart issue.
=> AF-1749: C3 Bubble Chart does not filter data correctly and display an error

uberfire-preferences/uberfire-preferences-backend/src/main/java/org/uberfire/preferences/backend/PreferenceBeanStoreImpl.java
I'm in a desparate situation trying to hunt down one Unexpected error which randomly appears in one of our selenium tests suites (1-2x in a suite of 20 tests). It only happens from time to time in random tests. But when it happens, it's always after the initial load of the home page:
The error is:
```
Uncaught exception: Client-side exception occurred although RPC call succeeded. Caused by: (TypeError) : this.f is undefined
```
There is no additional detail available, but @tiagobento told me this error means that this error is thrown from success callback of some RPC call.
I'm trying the following to identify the source of this NPE: 
1. I logged in and downloaded HAR file (json file capturing client-server HTTP communication) from chrome's dev tools
2. grepped all RPC call commands done …
=> Fix NPE in PreferenecBeanStoreImpl

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/selectpicker/JQuery.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/selectpicker/JQueryList.java
See https://issues.jboss.org/browse/DROOLS-3344
This PR introduces two king of enhancements: **I) The introduction of keyboard shortcuts** in the Data Types tab, and **II) Visual changes** to clarify some concepts to the user.
Now users can use <kbd>↑</kbd> and <kbd>↓</kbd> to navigate between Data Types, and expand/collapse by using <kbd>→</kbd>/<kbd>←</kbd>, respectively:
Also, when users are searching for some DT, they can just press <kbd>Tab</kbd> to navigate in the results (ahh.. but they can press <kbd>↓</kbd> to go to the first result too):
BTW.. the navigation can be disabled by pressing <kbd>Esc</kbd>.
When users want to update a Data Type, they just need to press <kbd>Ctrl</kbd> + <kbd>E</kbd> to activate the edit mode, and then, they can save the changes by pressing …
=> DROOLS-3344: [DMN Designer] Data Types - UX improvements in the Data Type List View

uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GAVResolverFromParentPomTest.java, uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2MavenRepositoryServiceImplTest.java, uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2RepoServiceCreator.java, uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/MockFileItem.java, uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/resources/org/guvnor/m2repo/backend/server/helpers/gav-pom-without-group.xml, uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/resources/org/guvnor/m2repo/backend/server/helpers/gav-pom-without-version.xml, uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/resources/org/guvnor/m2repo/backend/server/parent-gav-pom.xml
Moving selenium tests specifically ArtifactRepositoryBugfixTest. This is QE initiative to reduce selenium test suite.
Those tests trying to resolve missing GAV parameters from parent pom
=> Add test resolve from parent pom

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/KIEColours.java
I made changes to the font of highlighted cells based on [DROOLS-3393](https://issues.jboss.org/browse/DROOLS-3393).
**This should be merged together with: https://github.com/kiegroup/drools-wb/pull/1041.**
The highlighted cells now look as follows:
@danielezonca, @Rikkola, could you please take a look?
=> DROOLS-3435 Change the text color in highlighted cells

pom.xml, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/main/java/org/uberfire/ext/editor/commons/template/TemplateRenderer.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/main/java/org/uberfire/ext/editor/commons/template/mustache/MustacheTemplateRenderer.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/main/resources/org/uberfire/ext/editor/commons/UberfireCommonsEditorAPI.gwt.xml, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/pom.xml, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2S.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/template/mustache/ClientMustacheTemplateRenderer.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/template/mustache/Mustache.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/template/mustache/MustacheSource.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2DTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/template/mustache/ClientMustacheTemplateRendererTest.java
Inserting a _template engine_ to run on Client that is based on [Mustache](https://mustache.github.io/) using the implementation for `Javascript` [MustacheJS](https://github.com/janl/mustache.js). The idea is to process text templates on client side now, although it will allow us to keep the same API having an implementation on backend if necessary since there is a Java implementation (https://github.com/spullara/mustache.java).
The template engine is going to be used on Stunner to generate the **Process Documentation**.
Related PR https://github.com/kiegroup/kie-wb-common/pull/2363
@romartin 
@ederign 
@LuboTerifaj
=> JBPM-7916 - Stunner - Process Documentation (Template Engine)

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java
See: https://issues.jboss.org/browse/DROOLS-3399
---
- https://github.com/kiegroup/appformer/pull/609
- https://github.com/kiegroup/kie-wb-common/pull/2411
=> DROOLS-3399: [DMN Designer] Data Types - Disable the global 'Save' button when edit mode is enabled

uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/archive/Archiver.java, uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/archive/FileNameResolverTest.java
https://issues.jboss.org/browse/AF-1814
Problem was the default first folder was called _ when the entire repository was zipped. This PR changes the default folder to "project" in these cases.
@jomarko if you could please review and I'm open to reviews from the appformer team, who ever has time.
=> AF-1814 : Downloaded project can't be extracted with built-in Windows unzipper

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataTest.java
This fix point 2, 4, 5, 6 of the ticket https://issues.jboss.org/browse/DROOLS-3377
@kkufova @Rikkola 
PR list:
https://github.com/kiegroup/drools-wb/pull/1059
https://github.com/kiegroup/appformer/pull/626
=> [DROOLS-3377] Fix init width calculus

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/ColumnPicker.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.ui.xml, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/ColumnPickerTest.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/PagedTableTest.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-table/src/main/java/org/uberfire/ext/widgets/table/client/UberfireColumnPicker.java
Added the ability (enableDataGridMinWidth) to configure the PagedTable to set a minimal width to ensure that have enough space to display the visible columns. In case that the required size is bigger than the avaliable space an horizonal scroll appears. The default column size is also configurable and it's applied when the column has not one fixed.
=> JBPM-8232: Horizontal scrollbars missing in task inbox

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitCacheInvalidationTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderPostCommitHookTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitForkTest.java
* Unlock locked 'doraFs' instance after the asserts
Locks make this test fail on Windows, because of how
Windows handles files in use. 
Also multiple tests can't be executed because `AbstractTestInfra` is unable to deleted locked files on Windows.
* Set file permisions differently when running on Windows
PosixFilePermission is not supported in Windows environment, adds a branch  that sets permissions in compatible way 
* Wrap path assertions strings with File to make it OS agnostic 
Use File to make asserts that check paths work on windows properly too
=> [BAQE-888] Investigate a fix JGit community tests failures on windows

uberfire-extensions/uberfire-security/uberfire-servlet-security/src/main/java/org/uberfire/ext/security/server/BasicAuthSecurityFilter.java, uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/BasicAuthSecurityFilterTest.java
This PR adds a init-param to the `BasicAuthSecurityFilter` so that it's possible to configure URIs that should not be authenticated.
Related PRs:
https://github.com/kiegroup/appformer/pull/645
https://github.com/kiegroup/kie-wb-common/pull/2492
https://github.com/kiegroup/kie-wb-distributions/pull/881
=> AF-1821: Readiness and Liveness endpoints

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContextTest.java
Missing SASL security parameters
**Add this to ISPN 9.4.9 Server**
```
<subsystem xmlns="urn:infinispan:server:endpoint:9.4>
<hotrod-connector cache-container="clustered" socket-binding="hotrod-internal" name="hotrod-internal">
<authentication security-realm="ApplicationRealm">
<sasl server-name="jdg-server" mechanisms="DIGEST-MD5" qop="auth">
<policy>
<no-anonymous value="true" />
</policy>
<property name="com.sun.security.sasl.digest.utf8">true</property>
</sasl>
</authentication>
</hotrod-connector>
</subsystem>
```
**Also create a user/pass**
**Add this parameter to BC**
```
-Dorg.appformer.ext.metadata.infinispan.sasl.username=user
-Dorg.appformer.ext.metadata.infinispan.sasl.password=pass
-Dorg.appformer.ext.metadata.infinispan.sasl.qop=auth …
```
=> [AF-1868]: Improved security properties

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/BaseSingletonDOMElementFactory.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommon.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommonTest.java
- kiegroup/drools-wb#1112
This PR unifies the way how Guided Decision Table and Scenario Simulation user can cancel the cell edit mode.
- By enter, new value is stored, selection is moved down
- By shift + enter, new value is stored, selection is moved up
- By tab, new value is stored, selection is moved right
- By shift + tab, new value is stored, selection is moved left
- By Esc, new value is discarded, selection remains same
=> DROOLS-3438: Unify cell editing cancellation 

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyBootstrapper.java
See https://issues.jboss.org/browse/DROOLS-3591
Also see https://issues.jboss.org/browse/RHDM-912
The problem was that the `BootstrapSelect` Java Script was being loaded multiple times and event handlers for the component were being registered an equal number of multiple times. This lead to, for example, a cursor-down key press moving the selection multiple times.
I put a break point in `bootstrap-select.js` (L#1506) and observed the selection move one position, then another and another; for each successive registered event handler. Debugging `PatternFlyBootstrapper` showed the check failed and multiple instances of the `BootstrapSelect` were injected into the header. I also examined the `global` Java Script objects on the page and there was none for `Selectpicker` (nor `DateRangePicker` …
=> DROOLS-3591: [DMN Designer] Data Types - Type dropdown is not navigable by keyboard

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/index/directory/DirectoryFactory.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOSearchServiceImpl.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/KObjectUtil.java
KObjectUtil was generating the cluster id using the system file separator instead of using "/", that was causing that on windows system (file separator -> "\\") indexing was retriggered subsequently causing errors due to existing locks.
@adrielparedes @paulovmr @porcelli could you please take a look?
=> JBPM-8419: Indexing has not finished - org.apache.lucene.store.LockObtainFailedException

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataSelectionsManager.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/GridWidget.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationInvokeContextMenuForSelectedCell.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridCellSelectionsTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationInvokeContextMenuForSelectedCellTest.java
See https://issues.jboss.org/browse/DROOLS-3940
(Well, not directly related, but I found whilst writing DROOLS-3940 that deleting a column that had a selected header cell lead to strange behaviour - as the _selected header cells_ were not being cleared when the column deleted).
=> DROOLS-3940: DMN Editor: Update contextual menus (headers and cells)

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/selectpicker/JQuerySelectPicker.java
@manstis @jomarko @karreiro 
This is the twin part of https://github.com/kiegroup/kie-wb-common/pull/2632
It add "val" method that is used in the other PR
=> [DROOLS-3993] Add "val" method to JQuerySelectPicker

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/widgets/LayoutElementPropertiesPresenter.java
ManagedBean respects the ApplicationScoped annotation, which means it always returns the same instance. In LayoutEditorPropertiesPresenter instances of LayoutElementPropertiesPresenter - if instances of LayoutElementPropertiesPresenter are created with ManagedInstance, then only a single one will be created. With newInstances the cache is correctly created for each element.
=> AF-1966: Changing from ManagedBean back to newInstance

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/ws/JGitFileSystemsEventsManagerTest.java
The test JGitFileSystemsEventsManagerTest.java defining system property APPFORMER_JMS_CONNECTION_MODE=REMOTE, due to this fact, tests are failing if they performing after JGitFileSystemsEventsManagerTest.
=> Fix Failed to create session factory

appformer-js/pom.xml, dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/pom.xml, dashbuilder/dashbuilder-packaging/dashbuilder-all/pom.xml, dashbuilder/dashbuilder-packaging/dashbuilder-server-all/pom.xml, dashbuilder/dashbuilder-webapp/pom.xml, pom.xml, uberfire-bom/pom.xml, uberfire-commons/src/test/java/org/uberfire/commons/cluster/events/ClusterEventObserverTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionHistoryPresenterTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionSelectedEventMock.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/BaseIndexTest.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BaseIndexTest.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/BaseIndexTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-backend/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml, uberfire-packaging/uberfire-all/pom.xml, uberfire-packaging/uberfire-server-all/pom.xml, uberfire-showcase/uberfire-client-webapp/pom.xml, uberfire-showcase/uberfire-webapp/pom.xml
fixing uberfire-packaging submodules and duplicate dependency
removed duplicated dependency
added missing deps because of enforcer-rule
disabled maven-jar-plugin
added missing deps
change type of artifact to pom
missing deps adn excludes for testing
updated kie-parent to 7.22.0-SNAPSHOT
updating missing versions to 7.23.0.-SNAPSHOT
disbled maven-jar-plugin
BXMSPROD-333: implementing new methods from javax.enterprise.event.Event
(cherry picked from commit 25899f41bbca0da5923e669bda2ab91c2d28cd61)
upgraded missing deps to 7.24.0-SNAPSHOT
=> BXMSPROD-8: refactor to build without jboss-ip-bom

uberfire-api/src/main/resources/META-INF/beans.xml, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/main/resources/META-INF/beans.xml
Most/all *-wb test failures seems related to a parsing error on beans.xml in `uberfire-api`
Considering that it don't contain any real configuration and that empty file is enough, I think we can remove the content and keep the file empty
@mbiarnes
=> fix beans.xml parsing error

dashbuilder/dashbuilder-backend/dashbuilder-services/pom.xml
appformer on Jenkins https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/deployedRep/job/appformer/15/console breaks because of enforce-direct-dependencies check in dashbuilder-services. This PR adds missing deps.
=> added missing dependencies

appformer-js/pom.xml, dashbuilder/dashbuilder-packaging/dashbuilder-server-all/pom.xml, uberfire-packaging/uberfire-all/pom.xml, uberfire-packaging/uberfire-server-all/pom.xml
enabled the maven-jar-plugin again because the disabling of it causes much more problems then the problem:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.0:jar (default-jar) on project appformer-js: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
This error has to solved ASAP.
=> revoked the disabling of maven-jar-plugin

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpPresenter.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/KieEditorTest.java
The issue was caused when two users were trying to delete the same asset at same time (with the delete popup opened). When first user finally deletes the asset the second user gets the concurrent delete notification, whatever option he chooses (cancel or ignore) on that popup, the delete popup will still be opened, so he will be able click on the delete button, getting that error.
To prevent that situation, we'll be hiding the delete popup if there's a concurrent deletion.
@tomasdavidorg @adrielparedes @ederign Could you please take a look?
https://github.com/kiegroup/appformer/pull/731
https://github.com/kiegroup/kie-wb-common/pull/2740
=> AF-2053: Dialog remains open after asset is deleted at the same time

pom.xml
Works locally; the next step is to create a nightly job that will trigger these two profiles and uploads results into SonarCloud. After that, we can enable it for PRs.
=> AF-1652 Add code coverage measurement profiles to Appformer

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/GridHighlightHelper.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/GridHighlightHelperTest.java
- https://issues.jboss.org/browse/DROOLS-4211
- https://issues.jboss.org/browse/DROOLS-4212
---
- https://github.com/kiegroup/appformer/pull/738
- https://github.com/kiegroup/kie-wb-common/pull/2749
- https://github.com/kiegroup/drools-wb/pull/1191
---
DROOLS-4211 and DROOLS-4212 JIRAs comprehend only the search mechanism. Thus, the PR implements that for Guided Decision Tables, DMN graphs, and DMN boxed expressions, without a rich user experience (which will be implemented on [DROOLS-4306](https://issues.jboss.org/browse/DROOLS-4306)).
To test this PR, just execute the following code into the _browser inspector_:
```javascript
document.querySelector('.kie-search-bar').style.display = ""
```
The search component will be enabled, and now you can type something and press <kbd>Enter</kbd> to …
=> DROOLS-4211 / DROOLS-4212: Search feature - Implement search mechanism PoC on GDT / DMN graph

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/InputAutocomplete.java
@paulovmr (String[]) options.get().toArray()) doesn't work on GWT on OSX (but works on your linux env right?)
Anyway, (String[]) options.get().toArray() doesn't work on JDK, so I changed it for a new implementation.
@karreiro this is what was generating the annoying exception on drools-wb web app. (/cc @manstis)
Child PR (but not dependent): https://github.com/kiegroup/kie-wb-common/pull/2775
Stack of the error (on OSX, chrome and with gwt:run): 
ErraiConsoleLogHandler.java:91 Error caused by: ClassCastException: null
at BVe_g$.hHb_g$ [as createError_0_g$] (Throwable.java:120)
at BVe_g$.rHb_g$ [as initializeBackingError_0_g$] (Throwable.java:112)
at BVe_g$.aHb_g$ (Throwable.java:66)
at BVe_g$.GHb_g$ (Exception.java:29)
at BVe_g$.wsc_g$ (RuntimeException.java:29)
at new BVe_g$ …
=> [AF-2117] Get all users throw an exception when there is no implementation found

pom.xml, scripts/release/update-version.sh, uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-parent-with-dependencies/pom.xml
The commit https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/34dfe2ec1c3634a0d06db0b16f49b57e5e085301 moved uberfire-bom from appformer into droolsjbpm-build-bootstrap, with uberfire-bom version kept as Appformer version. Since this is not very user-friendly and breaks product build, this PR proposes a change of uberfire-bom version to KIE version to align it with the rest of the BOMs.
Related PRs: 
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1009
- https://github.com/kiegroup/droolsjbpm-integration/pull/1873
- https://github.com/kiegroup/drools-wb/pull/1198
- https://github.com/kiegroup/jbpm-designer/pull/856
- https://github.com/kiegroup/jbpm-wb/pull/1375
- https://github.com/kiegroup/kie-uberfire-extensions/pull/87
- …
=> changed uberfire-bom version to KIE version

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataTest.java
@kkufova @gitgabrio @danielezonca Can you please test and review it?
Basically, I only changed the Map implementation from HashMap to TreeMap for the cloned Map used to manage the cells shift when a column is deleted. It this case, the order of the cell position is critical, consider the used logic: 
```
for (Map.Entry<Integer, GridCell<?>> e : clone.entrySet()) {
if (e.getKey() > index) {
((BaseGridRow) row).deleteCell(e.getKey());
((BaseGridRow) row).setCell(e.getKey() - 1,
e.getValue());
}
}
```
Please notice, cells are stored in a MAP, not a list.
Navigating the cloned Map without following an order, can lead to lost some cells.
. HashMap doesn't guarantee the order of the keys, so changing it with TreeMap prevent the issue.
=> DROOLS-4415: Cell placeholder disappear in some cases

uberfire-experimental/uberfire-experimental-client/src/main/java/org/uberfire/experimental/client/UberfireExperimentalEntryPoint.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/RuntimePluginsEntryPoint.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/config/PluginConfigService.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorGenerator.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/plugins/RuntimePluginStartup.java
There were necessary the Errai bus connection check on Runtime Plugins startup, to avoid issues on BPMN editor.
The long term solution could be creating a new module as discussed.
@tiagobento 
@ederign
=> KOGITO-136 - BPMN webapp for Kogito, fixing issue with Errai bus disabled

uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java, uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplResolveWorkspaceWorkspaceProjectTest.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java, uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
AF-2064: Unexpected error is displayed after project is created on OpenShift [Cat1]
AF-2153: Contributor should not be removed from the project when it is edited in the space
* https://github.com/kiegroup/appformer/pull/771
* https://github.com/kiegroup/kie-wb-common/pull/2819
=> HA improvements

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/BooleanTextBox.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/BooleanTextBoxTest.java
https://issues.jboss.org/browse/DROOLS-4445
https://github.com/kiegroup/appformer/pull/776
https://github.com/kiegroup/drools-wb/pull/1218
=> DROOLS-4445 : Edit boolean columns in guided decision tables do not support alias with objects

dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/migration/DashbuilderDataMigration.java
[AF-2059](https://issues.jboss.org/browse/AF-2059) - Add Lock to Dashbuilder Migration Service for HA Environments
Create a **lock** mechanism to avoid conflicts in Cluster environments where multiples Pods could run the Dashbuilder Data Migration at same time. This lock also avoids the migration to run twice.
Three files are created under **.niogit/dashbuilder** to indicate that the migration process has executed. If these files are removed, the migration will run again at next system startup.
* datasets.migration.done
* perspectives.migration.done
* navigation.migration.done
This PR is related with this [commit](https://github.com/gabriel376/appformer/commit/7416921240cf2000c368cb5cf6a71def40d777dd)
=> AF-2059 - Add Lock to Dashbuilder Migration Service for HA Environments

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/ickl/IckleConverter.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/ickl/converters/RegexpQueryConverter.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/ickl/IcklConverterTest.java
**[RHPAM-2287](https://issues.jboss.org/browse/RHPAM-2287) Filter by asset type displaying no results**
* Issue caused by missing Regexp Query implementation on class IckleConverter, that converts from  Lucene to ISPN
=> [RHPAM-2287] Filter by asset type displaying no results

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/LockManagerTest.java
- Opened asset will now be updated even for user who push the change
- A warning popup will be shown to the user if he has lock on the asset. He can then accept the incoming changes or discard and save his current changes.
=> AF-2054 :Open asset is not updated for user who push the change

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/common/SaveAndRenameCommandBuilder.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/common/SaveAndRenameCommandBuilderTest.java, uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorPresenterTest.java
To resolve the issue, I changed the `SaveAndRenameCommandBuilder` to launch a command BEFORE the saveAndRename call is invoked. In this way, it's possibile to add a command witch synchronizes the columns widths from front-end model to back-end model.
@jomarko @gitgabrio @danielezonca
Related PR: https://github.com/kiegroup/drools-wb/pull/1227
=> [DROOLS-4083] After asset renaming, column width is automatically changed

uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/provider/IndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/provider/LuceneIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/index/MetadataIndexEngine.java
When ISPN got rebooted the main caches were lost, also the indexes because ISPN is not a persistent cache. So when ISPN is restarted, BC generates caches again and force reindexing.
=> [AF-2182]: Added generation of base caches in case they don't exist

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
**[AF-2232](https://issues.jboss.org/browse/AF-2232) IllegalStateException when logging out from BC**
**Issue:**
* Some activities are not `closed` before calling `destroy` in shutdown (logout) operation
**Solution:**
* Always call `close` before `destroy`
=> [AF-2232] IllegalStateException when logging out from BC

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/LayoutEditorFocusController.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/AbstractLayoutEditorTest.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/infra/LayoutEditorFocusControllerTest.java
This solution for AF-2215 records the scroll position and restore it after the layout editor draw all layout elements.
This should be tested with Form Editor and Page Layout Editor.
=> AF-2215: Avoid losing scroll position when editor changes

pom.xml
this is dependent PR for https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1055
=> javax.validation-api needs to keep older version

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/mock/MockPlaceManager.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManager.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PluginPlaceManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/WorkbenchConstants.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java, uberfire-workbench/uberfire-workbench-client/src/main/resources/org/uberfire/client/resources/i18n/WorkbenchConstants.properties
JIRA task: [AF-2214](https://issues.jboss.org/browse/AF-2214)
If the user has unsaved changes and closes the browser, then they lost all changes without being warned about. Thus, as a last resort, in this PR the browser will ask the user for confirmation when closing the tab, closing the browser or refreshing the page.
**DEMO**
=> [AF-2214] User confirmation when closing the workbench with unsaved stuff

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/pom.xml, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/SimpleTable.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/PagedTableTest.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/SimpleTableTest.java
Update global preferences key when GridpreferencesStore  preference key is changed.
Only persist preferences when global preferences key has value.
Added test dependency to be able to introduce test
=> JBPM-8742: Link column preferences with saved filter

uberfire-backend/uberfire-backend-server/pom.xml, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/VFSLockServiceImpl.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/servlet/ReleaseUserLocksServlet.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/servlet/ReleaseUserLocksServletTest.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/mock/MockPlaceManager.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManager.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PluginPlaceManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/WorkbenchConstants.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchCloseHandlerImplFallback.java, uberfire-workbench/uberfire-workbench-client/src/main/resources/org/uberfire/UberfireWorkbench.gwt.xml, uberfire-workbench/uberfire-workbench-client/src/main/resources/org/uberfire/client/resources/i18n/WorkbenchConstants.properties
Same code: https://github.com/kiegroup/appformer/pull/796
JIRA task: [AF-2214](https://issues.jboss.org/browse/AF-2214)
If the user has unsaved changes and closes the browser, then they lost all changes without being warned about. Thus, as a last resort, in this PR the browser will ask the user for confirmation when closing the tab, closing the browser or refreshing the page.
**DEMO**
=> [7.5.1] [AF-2214] User confirmation when closing the workbench with unsaved stuff

pom.xml
https://issues.jboss.org/browse/DROOLS-4563
Parent PR:
- kiegroup/droolsjbpm-build-bootstrap#1075
Dependent PRs:
-    kiegroup/appformer#814
-    kiegroup/kie-wb-common#2934
-    kiegroup/drools-wb#1238
=> DROOLS-4563 javax.validation-api version 1.0.0.GA managed 

uberfire-backend/uberfire-backend-server/pom.xml, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/VFSLockServiceImpl.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/servlet/ReleaseUserLocksServlet.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/servlet/ReleaseUserLocksServletTest.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/UserAgent.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java
**Task**: [AF-2305](https://issues.jboss.org/browse/AF-2305)
**Cause**:
The root cause of this bug is that `LockManager` also has a `WindowClosingHandler`, responsible for releasing asset locks when users close the browser.
Due to [AF-2214](https://issues.jboss.org/browse/AF-2214), `WindowClosingHandler` does not guarantee anymore that users have actually closed the browser.
Thus, users lose the lock when they decide to stay on the page.
As in [AF-2214](https://issues.jboss.org/browse/AF-2214), `WindowClosingHandler` can be replaced by the `ClosedHandler`.
Then, the lock is released only when the user actually decides to close the browser.
However, there is one limitation:
In Firefox and MS Edge, the event is fired when a _tab_ is closed, but it is **not** fired when the _browser_ is …
=> [AF-2305] Keeping asset locks if the user decides to stay on the page

appformer-js/package.json
Adds babel-jst to devDependencies.
Version is 23.0.0 as version 24.0.0 is not compatible.
@tiagobento Please take a look :)
=> Fix unmet-peer-dependency errors in appformer-js

pom.xml
BXMSPROD-525
the version version.org.kie property is duplicated what we have in kie-parent, so it is now useless https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L343
=> BXMSPROD-525 version.org.kie property removed

pom.xml
https://issues.jboss.org/browse/BXMSPROD-507
Parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1095
merge together with this #821 and kie-soup PR kiegroup/kie-soup/pull/117
=> BXMSPROD-507: upgrade netty to 4.1.42.Final

uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SideDockItem.java, uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/items/SideDockItemTest.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/docks/UberfireDock.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/docks/UberfireDockTest.java
https://issues.jboss.org/browse/RHPAM-2317
This adds the possibility of having different labels and tooltips for the docks which was not supported.
Video (Updated - Tooltip shows Properties instead of Open properties panel):
https://drive.google.com/file/d/1AbYsbhHG2RfZJjtSz3Kb2cKyQJG6tLsB/view?usp=sharing
=> RHPAM-2317 - Users cannot find the properties menu unless it's pointed out to them

uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SideDockItem.java, uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/items/SideDockItemTest.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/docks/UberfireDock.java, uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/docks/UberfireDockTest.java
**This is part of an ensemble**:
**https://github.com/kiegroup/kie-wb-common/pull/3024**
https://issues.jboss.org/browse/RHPAM-2317
This adds the possibility of having different labels and tooltips for the docks which was not supported.
Some small adjustments due to sonar cloud fail.
* Wider test coverage
* Change to method name in a test.
* Unnecessary code removed.
Video (Updated - Tooltip shows Properties instead of Open properties panel):
https://drive.google.com/file/d/1AbYsbhHG2RfZJjtSz3Kb2cKyQJG6tLsB/view?usp=sharing
=> [7.30.x] RHPAM-2317 - Users cannot find the properties menu unless it's pointed out to them

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/pom.xml, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridCell.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilities.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/Logging.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMerged.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelper.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilitiesTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/LoggingTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTestUtils.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattenedTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMergedTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelperTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanelTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandlerTest.java
See https://issues.jboss.org/browse/DROOLS-4735
- https://github.com/kiegroup/appformer/pull/843
- https://github.com/kiegroup/kie-wb-common/pull/3004
- https://github.com/kiegroup/drools-wb/pull/1264
This PR really moves calculation of row heights from "on demand" to be cached in the `RenderingInformation` class. Subsequent uses of rows' heights was then moved to use the cached value if a `RenderingInformation` instance was available (i.e had been instantiated elsewhere in the class and could be passed as a parameter etc to needy code).
=> DROOLS-4735: [DMN Designer] Grid performance is dire

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilities.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilitiesTest.java
See https://issues.jboss.org/browse/AF-2347
=> AF-2347: [wires-grids] CellContextUtilities.makeCellRenderContext() wrong for scrolled grids

appformer-js/package.json, appformer-js/pom.xml, appformer-js/yarn.lock
BXMSPROD-597
* lock-treatment-tool added to dev-dependencies
* locktt script added
* pom execution changed to `npm run locktt`
=> BXMSPROD-597: frontend project locktt execution improved

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorPluginImpl.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorPresenter.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/LayoutEditor.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponentsView.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumn.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/AbstractLayoutEditorTest.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/LayoutEditorPluginImplTest.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/LayoutEditorPresenterTest.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponentsTest.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnTest.java, uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/container/ContainerTest.java
Added the LockRequiredEvent when a component is dropped in the editor in canvas.
ensemble: 
kie-wb-common: https://github.com/kiegroup/kie-wb-common/pull/3063
=> AF-1395 : The new Form modeler editor is not locked when it is edited

dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/pom.xml, dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/resources/org/dashbuilder/renderer/C3Renderer.gwt.xml, dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/pom.xml, dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/resources/org/dashbuilder/DisplayerAPI.gwt.xml
During https://github.com/kiegroup/appformer/pull/860 review these unused dependencies were found.
=> DROOLS-4518: Remove unused dependencies

uberfire-commons/pom.xml
dependency:
- https://github.com/kiegroup/drools/pull/2506
=> AF-2154: remove unnecessary OSGi support of uberfire-commons module

uberfire-workbench/uberfire-workbench-client/pom.xml
During KOGITO-436 review some unused dependencies were found, this PR is an effor to eliminate them.
=> KOGITO-436: Remove unused dependencies

pom.xml, uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/MonacoEditorInitializer.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/Monaco.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoEditor.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoLanguages.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoLoader.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoStandaloneCodeEditor.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoStandaloneCodeEditorHelper.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyBootstrapper.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyClientBundle.java, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/PatternFly.gwt.xml, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/monaco/MonacoEditorInitializerTest.java
See:
- [DROOLS-4689](https://issues.jboss.org/browse/DROOLS-4689): [DMN Designer] Code Completion - Setup Monaco (loader)
- [DROOLS-4690](https://issues.jboss.org/browse/DROOLS-4690): [DMN Designer] Code Completion - Add Monaco support for 'TextAreaSingletonDOMElementFactory'
- [DROOLS-4691](https://issues.jboss.org/browse/DROOLS-4691): [DMN Designer] Code Completion - Enable code completion for only Literal Expressions
- [DROOLS-4692](https://issues.jboss.org/browse/DROOLS-4692): [DMN Designer] Code Completion - UI adjusts for Monaco component into DMN Boxed Expression component
---
---
- https://github.com/kiegroup/appformer/pull/836
- https://github.com/kiegroup/kie-wb-common/pull/3000
=> DROOLS-4689/DROOLS-4690/DROOLS-4691/DROOLS-4692: [DMN Designer] Code Completion - Enable code completion for Literal Expressions

appformer-kogito-bridge/pom.xml, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/context/EditorContextProvider.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/context/KogitoChannel.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/context/impl/EditorContextProviderImpl.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/context/interop/EditorContextWrapper.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/interop/Envelope.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/interop/WindowRef.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/ResourceContentService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/impl/EnvelopeResourceContentService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/impl/NoOpResourceContentService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/interop/ResourceContentEditorServiceWrapper.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/producer/ResourceContentServiceProducer.java, appformer-kogito-bridge/src/main/resources/META-INF/ErraiApp.properties, appformer-kogito-bridge/src/main/resources/org/appformer/kogito/bridge/AppformerKogitoBridge.gwt.xml, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/context/KogitoChannelTest.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/WorkbenchClientEditorActivity.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/GWTEditorNativeRegister.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/java/org/uberfire/annotations/processors/WorkbenchClientEditorProcessorTest.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchClientEditorTest5.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchClientEditorTest6.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest6.expected, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/ClientEditorActivityGenerator.java, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java, uberfire-workbench/uberfire-workbench-processors/src/main/resources/org/uberfire/annotations/processors/templates/activityClientEditor.ftl
Add a new parameter to the editor `setContent` method and make sure it is generated correctly.
Also create a wrapper object for the context. Editors can now access the context by injecting  `EditorContextProvider`.
https://github.com/kiegroup/kogito-tooling/pull/47
https://github.com/kiegroup/kie-wb-common/pull/3099
=> KOGITO-652: Context for editors

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/ACLSettings.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/ACLSettingsTest.java
The bug is caused because authzPolicy is retrieved only when the ACLSettings is created, after it is created the reference changes (with the new HomePage), but not updated on ACLSettings.
In this change we change the reference when it is updated.
=> AF-903: Update authzPolicy reference when it is saved

uberfire-backend/uberfire-backend-api/src/main/java/org/uberfire/backend/authz/AuthorizationPolicyStorage.java, uberfire-backend/uberfire-backend-api/src/main/java/org/uberfire/backend/authz/AuthorizationService.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/authz/AuthorizationPolicyMarshaller.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/authz/AuthorizationPolicyVfsStorage.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/authz/AuthorizationServiceImpl.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/authz/AuthorizationServiceTest.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/authz/AuthzPolicyDeployerTest.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/authz/AuthzPolicyMarshallerTest.java, uberfire-backend/uberfire-backend-server/src/test/resources/WEB-INF/classes/security-policy.properties, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflowTest.java, uberfire-showcase/uberfire-client-webapp/src/main/java/org/uberfire/client/auth/ShadowedAuthorizationService.java
-  Added feature to remove a specific group from security-policy.properties
-  If the user adds a group with the same name as deleted group, default configurations will be applied to the newly added group.
=> AF-2397 :Deletion of group from Business Central UI does not remove group from the security-policy.properties file

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseKeyboardOperation.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseKeyboardOperationTest.java
@jomarko @dupliaka @danielezonca @manstis @danielzhe 
It seems the management of this case was not present. I just added this case i.e. the case where a HEADER cell is selected. To manage case where header cells are spanned over multiple column, It selects the last selected cell if pressed key is RIGHT, and the first one otherwise. 
https://issues.redhat.com/browse/DROOLS-4585
=> DROOLS-4585: Focus doesn't moves after the selected header cell

uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml, uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/PatternFly.gwt.xml
See https://issues.redhat.com/browse/KOGITO-936
@ederign @manstis I've fixed the issue related to the assets size. However, we're still using the dev version. I've deployed a new Monaco version on [webjars.org](https://www.webjars.org) to check if the bug is fixed and if we could use the minified version, but we can't:
We have 3 options to handle this issue:
1. Setup an assets pipeline on BC
2. Use static files (instead of [webjars.org](https://www.webjars.org)'s)
3. Keep the dev version for now
Given the size we achieved, my proposal with this PR refers to the third option. But, please, let me know WDYT :-)
---
PS.: There are some odd dependencies in the  `pom.xml` file. But, when we require `vs/editor/editor.main`, all these dependencies are required as well.
=> KOGITO-936: Analyse why editor artefact had increased the size

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDHandlersState.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseUpHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/NodeMouseEventHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetCellSelectorMouseEventHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetCollapsedCellMouseEventHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetEditCellMouseEventHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetLinkedColumnMouseEventHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetPinnedModeMouseEventHandler.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseUpHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/NodeMouseEventHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetCellSelectorMouseEventHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetCollapsedCellMouseEventHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetEditCellMouseEventHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetLinkedColumnMouseEventHandlerTest.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetPinnedModeMouseEventHandlerTest.java
See https://issues.redhat.com/browse/DROOLS-3276
This PR adds support for resizing columns in the header too (currently you can only resize columns in the body). It also improves use by not selecting the cell next to the pointer when resizing a column (currently after the column resize drag ends a cell is often selected next to the pointer).
=> DROOLS-3276: [DMN Designer] All GRIDS: Add support for resizing columns using header

appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/ResourceContentService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/impl/EnvelopeResourceContentService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/impl/NoOpResourceContentService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/interop/Options.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/interop/ResourceContentEditorServiceWrapper.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/interop/ResourceContentOptions.java
Bridge GWT with the new ResourceContentService Options support. 
Right the only supported option is the content type, which can be `text`, the text representation of a content or `binary`, where the content binary is encoded in a base64 string. To retrieve binary content use:
~~~
resourceContentService.get("/path/to/resource", Options.binary());
~~~
Merge with: https://github.com/kiegroup/kogito-tooling/pull/60
=> KOGITO-862: Adding bridge to new resource content get method with Options

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupCreationWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupCreationWorkflowTest.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/authz/AuthorizationPolicy.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationPolicy.java
- Added the grant permission for reading Home perpective when a new group is added.
- An entry for new group will be made in security-properties.properties when a new group is created, earlier group entry was only made when that group is edited
=> AF-2424 :Issue with the group permissions for the Pages

uberfire-rest/uberfire-rest-backend/pom.xml, uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json
@adrielparedes @ederign 
fixes https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1193
Sorry for the broken build. Here's the fix.
The issue was that some time ago guvnor was migrated to appformer/uberfire and at that time it was cut from kie-parent so revapi configuration was not inherited. Because of that, the revapi plugin was not turned on. But once the appformer [inherited from kie-parent](https://github.com/kiegroup/appformer/pull/718) it began to work, only this time it showed just warning saying:
```
[WARNING] Failed to resolve old artifacts:
Failure to find org.uberfire:uberfire-rest-backend:jar:7.26.0.Final in https://repository.jboss.org/nexus/content/groups/public/
was cached in the local repository, resolution will not be reattempted
until the update interval of …
```
=> Use revapi version from kie-parent

appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/context/KogitoChannelTest.java
Adding test coverage for all channels.
=> KOGITO-866: Cover ONLINE, VSCODE, DEFAULT on Context Editor unit Testing

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-ace/src/main/java/org/uberfire/ext/widgets/common/client/ace/AceEditor.java
See https://issues.redhat.com/browse/KOGITO-1014
- https://github.com/kiegroup/appformer/pull/917
- https://github.com/kiegroup/kie-wb-common/pull/3204
=> KOGITO-1014: [DMN Designer] ACE Editor is not shown for invalid DMN content

pom.xml
- Upgraded moment, patternfly and bootstrap-select to fix the vulnerabilities in BC
- Vulnerablities were found as per this report https://snyk.io/test/npm/patternfly/3.18.1.
- We are using moment and bootstrap-select independantly in BC (not coming from patternfly), so I also upgraded them to their non-vulnerable versions.
upgraded bootstrap select to 1.13.6 (https://snyk.io/vuln/SNYK-JS-BOOTSTRAPSELECT-173741)
upgraded moment to 2.19.3 (https://snyk.io/vuln/npm:moment:20161019)
=> RHPAM-1954 :CVE in webjars used by business-central

uberfire-api/src/main/java/org/uberfire/lifecycle/GetContent.java, uberfire-api/src/main/java/org/uberfire/lifecycle/GetPreview.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/WorkbenchClientEditorActivity.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/GWTEditorNativeRegister.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/java/org/uberfire/annotations/processors/WorkbenchClientEditorProcessorTest.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchClientEditorTest7.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest7.expected, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/ClientEditorActivityGenerator.java, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/facades/APIModule.java, uberfire-workbench/uberfire-workbench-processors/src/main/resources/org/uberfire/annotations/processors/templates/activityClientEditor.ftl
New annnotation `@GetPreview` to bridge GetPreview functionality in Kogito Tooling side.
The new annotation GetPreview works just like GetContent: editors must have a method that returns String, which is the SVG representation of the asset being edited. 
Part of an ensemble, merge with: 
https://github.com/kiegroup/kogito-tooling/pull/67
https://github.com/kiegroup/kie-wb-common/pull/3192
=> KOGITO-1236: Adding GetPreview support on editor side

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/WorkbenchClientEditorActivity.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/GWTEditorNativeRegister.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/java/org/uberfire/annotations/processors/WorkbenchClientEditorProcessorTest.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchClientEditorTest5.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchClientEditorTest6.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchClientEditorTest7.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest6.expected, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest7.expected, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java, uberfire-workbench/uberfire-workbench-processors/src/main/resources/org/uberfire/annotations/processors/templates/activityClientEditor.ftl
This PR changes the set content method to return a Promise instead of void.
The goal of this change is to be able to make the loading of editors predictable and remove the need for double set content call.
Merge together with:
https://github.com/kiegroup/kogito-tooling/pull/95
https://github.com/kiegroup/kie-wb-common/pull/3246
=> [KOGITO-1436]Remove double setContent call

uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationPolicy.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultPermissionManager.java, uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DotNamedPermission.java, uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/DefaultPermissionManagerTest.java
- fix the issue with caching of permissions for resources. Now, after using a resource (Screens, Spaces etc), the permissions corresponding to that resource will be cached and subsequent use will be faster.
- Optimized fetching of groups and roles permissions. Replaced HashSet based collection with HashMap to provide faster retrival of roles/group permissions.
- Please note the initial home page load might still be little slower when we use elevated number of groups since it calculates and merges permissions of all the groups. however, subsequent page load should be faster since it fetches from the permission cache
=> RHPAM-2708 : RHPAM 7.x Business Central latency correlated with number of groups memberships

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/main/java/org/uberfire/ext/editor/commons/version/CurrentBranch.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/main/java/org/uberfire/ext/editor/commons/version/VersionService.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/main/java/org/uberfire/ext/editor/commons/backend/version/VersionServiceImpl.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/version/VersionServiceImplTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/RestorePopUpPresenter.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/VersionRecordManager.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilder.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilderImpl.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/RestoreVersionCommandProvider.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/common/CurrentBranchProducer.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/common/DefaultCurrentBranch.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/popups/RestorePopUpPresenterTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionHistoryPresenterTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionRecordManagerOpenOlderVersionTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionRecordManagerTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionServiceMock.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilderTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/common/CurrentBranchProducerTest.java, uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/common/DefaultCurrentBranchTest.java
* Added CurrentBranch class to track current modifying branch in the editor  
Related PR : 
kie-wb-common [#3238](https://github.com/kiegroup/kie-wb-common/pull/3238)
=> AF-2432 :  Restoring an old asset version doesn't work outside master branch

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/main/java/org/uberfire/java/nio/fs/k8s/K8SFileChannel.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/test/java/org/uberfire/java/nio/fs/k8s/K8SFileChannelTest.java
In case of the occurrences of kubAPI or fabric8 client error when opening or closing a K8SFileChannel, the backing InMemoryByteChannel MUST be closed properly so as to be ready for garbage collection.  
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
=> [AF-2058] Improve resiliency for K8SFileChannel

appformer-js/pom.xml
They are now managed by kie-parent.
PR group:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1273
- https://github.com/kiegroup/appformer/pull/943
- https://github.com/kiegroup/droolsjbpm-integration/pull/2064
- https://github.com/kiegroup/kie-wb-common/pull/3269
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/296
- https://github.com/kiegroup/optaweb-employee-rostering/pull/425
=> BXMSPROD-741: Remove Node and npm versions

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystem.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImpl.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProxy.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/http/HTTPSupport.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManager.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitUpdateFSCacheWithHostnameTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManagerTest.java
- Http wasn't enabled for the repositories because the project public URI's (ssh, http) are stored at project basis. During initialisation these project info are initialised with default values (without http/https) and stored in cache. Later on http/https support was added to the provider, making the existing projects unaware of http support.
- Implemented update cache functionality, which will update all the file system caches with hostnames whenever http support is added.
=> RHPAM-2721 :Clone project via http can not be re-enabled

uberfire-m2repo-editor/uberfire-m2repo-editor-client/pom.xml
This PR removes unused compile dependencies of 'uberfire-m2repo-editor-client' module identiefied by 'mvn dependency:analyze'
For more details see https://issues.redhat.com/browse/DROOLS-5265
=> DROOLS-5265: Remove unused dependencies

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/wizards/WizardViewImpl.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/wizards/WizardViewImplTest.java
During investigation of DROOLS-5255 a memory leak was found. This PR itself doesn't fix the issue. It fixes just the memory leak.
Wizard page titles can be changed dynamically in runtime. See WizardViewImpl#setPageTitles method.
In such case we release original title and replace with new title. However we didn't release new title them when dialog is closed.
=> DROOLS-5255: Release wizard page titles when hide is called

dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/migration/DashbuilderDataMigration.java, dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/migration/DashbuilderDataMigrationTest.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IndexerDispatcher.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/api/FileSystemUtils.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/test/java/org/uberfire/java/nio/fs/k8s/FileSystemProvidersTest.java, uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/migration/ACLMigrationTool.java, uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/migration/ACLMigrationToolTest.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/FileSystemDeleteWorker.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/LoadReposOnAppInit.java, uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/FileSystemDeleteWorkerTest.java, uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/LoadReposOnAppInitTest.java
* Disable JGit specific features when JGit is not the default FS
* Add a switch to choose between Monitoring and Simplified Monitoring
Simplified monitoring is the K8S FS based solution. This can't use JGit specific parts so they are disabled (Like _Pages_)
Possible values:
* -Dorg.appformer.server.simplified.monitoring.enabled=true/false
* https://github.com/kiegroup/appformer/pull/882
* https://github.com/kiegroup/kie-wb-common/pull/3128
* https://github.com/kiegroup/drools-wb/pull/1363
* https://github.com/kiegroup/jbpm-designer/pull/881
=> AF-2410: Added switch to disable Business Central Features

pom.xml
After the update to Widlfly 18 the DMR version in `appformer/pom.xml` was not updated, which broke running some webapps in dev mode (dashbuilder and uberfire showcase). In this PR we simply remove the dmr version declaration from pom.xml (1.4.1.Final) and let appformer use the one from parent bom (1.5.0.Final)
=> AF-2509: Remove DMR version

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/test/java/org/uberfire/java/nio/fs/k8s/K8SFileChannelTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/test/java/org/uberfire/java/nio/fs/k8s/K8SFileSystemInitTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/test/java/org/uberfire/java/nio/fs/k8s/K8SFileSystemTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/test/java/org/uberfire/java/nio/fs/k8s/K8SWatchServiceTest.java
To workaround a known [issue](fabric8io/kubernetes-client#1243) of f8 k8s client, which is that if in CRUD mode the OpenShift mock server uses HTTPS as always.
It causes certificate issues in JDK 11 on RHEL 8, and IBM JDK1.8.
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
Related JIRAs:
https://issues.redhat.com/projects/AF/issues/AF-2522
Related PRs:
https://github.com/kiegroup/droolsjbpm-integration/pull/2090
=> AF-2522: org.uberfire.java.nio.fs.k8s tests are failing on IBM JDK1.8

uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/upload/UploadFormViewImpl.java, uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/test/java/org/guvnor/m2repo/client/upload/UploadFormViewImplTest.java
This PR clear the last selected file from file selector widget when the dialog for artifact upload is closed or canceled.
For more details see: https://issues.redhat.com/browse/DROOLS-5264
=> DROOLS-5264: Clear selected file when dialog is closed

appformer-client-api/src/main/java/org/appformer/client/context/Channel.java, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/context/ChannelTest.java
See https://issues.redhat.com/browse/FAI-173
Cousin of https://github.com/kiegroup/kogito-tooling/pull/165 for `appformer`.
=> FAI-173: Embed kogito-tooling editors in trusty-ai. Part 2 (trusty-ai changes)

dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/DataTransferServicesImpl.java
* Fixed URI schemes for file (:///)
* Fixed windows path by replacing "\\" to "/"
=> AF-2534 : Dashbuilder Data Transfer feature does not work on Windows

dashbuilder/dashbuilder-runtime/pom.xml, dashbuilder/dashbuilder-webapp/pom.xml, uberfire-showcase/uberfire-webapp/pom.xml
This is a change for having always directory for Errai Wildfly unpacked distribution to be on the same name as original wildfly distribution as Errai just repackaged it so naming directory to that version is not confusing
=> fixed real directory for Errai Wildfly distribution

appformer-kogito-bridge/pom.xml, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourBridge.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourCustomSelectorPositionProvider.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourObserver.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/observers/GlobalHTMLObserver.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/GuidedTourService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/GuidedTourServiceEnvelope.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/GuidedTourServiceNativeEnvelope.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/GuidedTourServiceProducer.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/AutoMode.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/BlockMode.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/DemoMode.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/Mode.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/Rect.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/Step.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/SubTutorialMode.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/Tutorial.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/guided/tour/service/api/UserInteraction.java, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourBridgeTest.java, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourCustomSelectorPositionProviderTest.java, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourObserverTest.java, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/observers/GlobalHTMLObserverTest.java, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/service/GuidedTourServiceEnvelopeTest.java, appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/service/GuidedTourServiceProducerTest.java
See https://issues.redhat.com/browse/KOGITO-764
---
- https://github.com/kiegroup/appformer/pull/988
- https://github.com/kiegroup/kie-wb-common/pull/3336
- https://github.com/kiegroup/kogito-tooling/pull/182
---
Assumptions:
- This PR does not include i18n for any tour. It will be separately implemented by https://issues.redhat.com/browse/KOGITO-2471;
- This PR does not include the final version of the tour, and the steps are a mix of the preliminary input provided by Liz and the Learn DMN in 15 minutes (as accordingly with @ederign).
=> KOGITO-764: Create a Guided Tour for first time users on DMN editor

dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/resources/api/DashbuilderRuntimeResource.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/services/RuntimeInfoService.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/services/impl/RuntimeInfoServiceImpl.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/services/impl/RuntimeModelParserImpl.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/services/impl/RuntimeModelRegistryImpl.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/shared/model/DashboardInfo.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/shared/model/DashbuilderRuntimeInfo.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/shared/service/RuntimeModelRegistry.java, dashbuilder/dashbuilder-runtime/src/main/webapp/WEB-INF/web.xml, dashbuilder/dashbuilder-runtime/src/test/java/org/dashbuilder/backend/services/impl/RuntimeInfoServiceImplTest.java
REST API for Dashbuilder Runtime.
The goal of this API is be a support for developers using dashboards outside of Dashbuilder Runtime:
* Inside React components (AF-2546);
* To compose embedded dashboards (see AF-2529);
The Available endpoints are:
`GET /api`: Provides server information: Runtime Mode and list of available models;
`POST /api/dashboard/`: Received a POST ZIP with dashboards and register it for use (upload);
`GET /api/dashboard/{id}`: Retrieves information about the dashboard {id}
=> AF-2547: REST API for Dashbuilder Runtime

appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/stateControl/interop/StateControl.java
See https://issues.redhat.com/browse/KOGITO-2601
Related PRs:
https://github.com/kiegroup/kogito-tooling/pull/200
https://github.com/kiegroup/appformer/pull/997
=> KOGITO-2601: Move State Control API to kie-bc-editors

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/ColumnIndexUtilities.java, uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/ColumnIndexUtilitiesTest.java
[See](https://issues.redhat.com/browse/DROOLS-5384).
=> DROOLS-5384: Clicking rightmost column's header in DMN decision table raises an error

dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/rest/DataTransferResource.java, dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/transfer/rest/DataTransferResourceTest.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/RuntimeOptions.java, dashbuilder/dashbuilder-webapp/src/main/java/org/dashbuilder/backend/RuntimeJaxApp.java
Exposing export feature in a REST endpoint.
Testing:
* Start Business Central
* Using a browser access http://localhost:8080/business-central/rest/dashbuilder/export
* A ZIP should be downloaded with pages, datasets and navigation
* Do the same with the Data Transfer UI - it should be the same ZIP.
=> AF-2576: Allow users to export dashboards using REST API

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/JAASAuthenticationService.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java, uberfire-extensions/uberfire-security/uberfire-servlet-security/src/main/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationService.java, uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationServiceTest.java
Removed username entry as part of user groups.
Due to this entry,  BC was creating an entry for user in security-policy.properties file. In absence of such entries, user with dot (.) character shouldn't throw any error.
backport PR: https://github.com/kiegroup/appformer/pull/1008
=> RHPAM-2981 :Unable to access business-central after user containing dot(.) character changes role settings

appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/i18n/I18nApi.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/i18n/I18nApiInteropWrapper.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/i18n/I18nService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/i18n/I18nServiceProducer.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/i18n/LocaleChangeCallback.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/i18n/NoOpI18nService.java
https://issues.redhat.com/browse/KOGITO-2120
Add the bridge to the i18n service on kogito-tooling.
Provides two methods:
- onLocaleChange
Subscribes to locale changes with a callback.
- getLocale
Get the current locale.
=> KOGITO-2120: Kogito Tooling i18n

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/provider/LuceneIndexProvider.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedTest.java
@RishiRajAnand @ederign 
The change is simple, I'm resolving a single path for the project to be deleted. The deletion already exist, I just did a small change to resolve the Path before the physical directory is deleted.
=> AF-2587: Indexes are removed when project is deleted

pom.xml
merge together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1427
https://issues.redhat.com/browse/JBPM-9216
=> JBPM-9216: upgrade of postgresql JDBC driver to 42.2.14

pom.xml
https://issues.redhat.com/browse/JBPM-9216
parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1428
=> [7.39.x] JBPM-9216: upgrade of postgresql JDBC driver to 42.2.14

dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/RuntimeOptions.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/client/screens/RouterScreen.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/client/screens/RuntimeScreen.java, dashbuilder/dashbuilder-runtime/src/test/java/org/dashbuilder/client/screens/RuntimeScreenTest.java
**JIRA**: 
[AF-2611: Allow default pages in Dashbuilder Runtime](https://issues.redhat.com/browse/AF-2611)
[AF-2612: Fix components partition system property](https://issues.redhat.com/browse/AF-2612)
In this PR we address the two JIRAs mentioned above. In AF-2611 we have functional changes, it works
1) A page called "index" will be used when opening a runtime model (import);
2) If you have a single page in your import than this page will be the index;
3) If none of this is done than there's no index/default page.
Thanks!
=> AF-2611: Allow default pages in Dashbuilder Runtime

appformer-js/package.json, appformer-js/yarn.lock
Adding write-file-atomic dependencies to fix Appformer-js build failures in the Windows environment
**JIRA**:  
[AF-2602](https://issues.redhat.com/browse/AF-2602)
<details>
<summary>
</summary>
</details>
=> AF-2602 Adding write-file-atomic dependencies to fix Appformer-js build failures in the windows environment

dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/client/perspective/generator/RuntimePerspectiveGenerator.java
[AF-2638](https://issues.redhat.com/browse/AF-2638)
SyncBeanManager does not override registered beans, hence we need to replace the page content instead register it again and again
=> AF-2638: Index page is not updated when changing models

dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/DataTransferServicesImpl.java, dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/ExportModelValidationServiceImpl.java, dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/transfer/DataTransferServicesTest.java, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/resources/i18n/ContentManagerConstants.java, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/transfer/DataTransferScreen.java, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/transfer/DataTransferView.java, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/transfer/export/wizard/ExportSummaryWizardPage.java, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/transfer/export/wizard/ExportSummaryWizardPageView.html, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/transfer/export/wizard/ExportSummaryWizardPageView.java, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/transfer/export/wizard/ExportWizard.java, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/resources/org/dashbuilder/client/cms/resources/i18n/ContentManagerConstants.properties, dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/test/java/org/dashbuilder/client/cms/screen/transfer/export/wizard/ExportSummaryWizardPageTest.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/ExternalComponentsContentListener.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/RuntimeOptions.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/remote/services/RuntimeModelServiceImpl.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/services/impl/RuntimeModelParserImpl.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/shared/model/RuntimeModel.java, dashbuilder/dashbuilder-runtime/src/test/java/org/dashbuilder/client/ClientRuntimeModelLoaderTest.java, dashbuilder/dashbuilder-shared/dashbuilder-services-api/src/main/java/org/dashbuilder/transfer/DataTransferServices.java, dashbuilder/dashbuilder-shared/dashbuilder-services-api/src/main/java/org/dashbuilder/transfer/ExportInfo.java, dashbuilder/dashbuilder-webapp/pom.xml
Link BC to DB
**JIRA**: 
[AF-2555](https://issues.redhat.com/browse/AF-2555)
This is a new feature for 7.44. It links BC/Dashbuilder Webapp with Dashbuilder Runtime. It introduces in Dashbuilder Runtime the Refresh mode, which is turned on by default, and allow users from BC to call dashbuilder runtime by setting the following system properties:
* **dashbuilder.import.base.dir**. The location in Runtime configured to store dashbuilder models. In runtime the same system property is used, but it has a default value, but in BC you must set it, even if it points to the default value. Sample value: `/tmp/dashbuilder/models`;
*  **dashbuilder.runtime.location**: Dashbuilder Runtime root URL. Sample value: `http://localhost:8280`
To test it:
* Start Dashbuilder Runtime with multi mode and …
=> AF-2555: Link BC <-> DB

dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/health/HealthService.java, dashbuilder/dashbuilder-runtime/src/main/webapp/WEB-INF/web.xml
**JIRA**:
[AF-2625](https://issues.redhat.com/browse/AF-2625)
I think that initially this is all for the ready and liveness probes.
*/rest/ready*: Indicates that the server is ready to be accessed;
*/rest/healthy*: Successful response only if the server is ready.
=> AF-2625: Create Liveness and Readiness Probe on Dashbuilder Runtimes

dashbuilder/dashbuilder-runtime/pom.xml, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/RuntimeOptions.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/resources/UploadResourceImpl.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/resources/api/DashbuilderRuntimeResource.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/services/impl/RuntimeModelRegistryImpl.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/shared/service/RuntimeModelRegistry.java, dashbuilder/dashbuilder-runtime/src/test/java/org/dashbuilder/backend/services/impl/RuntimeModelRegistryImplTest.java, dashbuilder/dashbuilder-runtime/src/test/java/org/dashbuilder/shared/service/RuntimeModelRegistryTest.java
**JIRA**: 
[AF-2658](https://issues.redhat.com/browse/AF-2658)
Adds an option to unregister models. By default it won't delete the file, if users want the file to be removed then they must set the property `dashbuilder.removeModelFile` as true.
=> AF-2658: Option to clean all registered models

dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/main/java/org/dashbuilder/external/impl/BackendComponentFunction.java, dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/main/java/org/dashbuilder/external/impl/BackendComponentFunctionServiceImpl.java, dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/main/java/org/dashbuilder/external/impl/BackendDateFunction.java, dashbuilder/dashbuilder-backend/dashbuilder-kie-server-backend/pom.xml, dashbuilder/dashbuilder-backend/dashbuilder-kie-server-backend/src/main/java/org/dashbuilder/kieserver/backend/KieServerConnectionInfoProviderImpl.java, dashbuilder/dashbuilder-backend/dashbuilder-kie-server-backend/src/main/java/org/dashbuilder/kieserver/backend/function/ProcessSVGFunction.java, dashbuilder/dashbuilder-backend/dashbuilder-kie-server-backend/src/main/java/org/dashbuilder/kieserver/backend/rest/KieServerQueryClient.java, dashbuilder/dashbuilder-backend/dashbuilder-kie-server-backend/src/test/java/org/dashbuilder/kieserver/backend/KieServerConnectionInfoProviderImplTest.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/ExternalComponentDispatcher.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/function/BackendFunctionLoader.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/function/ComponentFunctionLocator.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/function/GWTVersion.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/function/ListFunctions.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/component/ExternalComponentDispatcherTest.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/component/function/ComponentFunctionLocatorTest.java, dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/external/ExternalComponentFunction.java, dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/external/ExternalComponentMessageHelper.java, dashbuilder/dashbuilder-shared/dashbuilder-services-api/src/main/java/org/dashbuilder/external/service/BackendComponentFunctionService.java, dashbuilder/dashbuilder-webapp/pom.xml
[AF-2637](https://issues.redhat.com/browse/AF-2637)
Part of an ensemble, merge with:
https://github.com/kiegroup/jbpm-wb/pull/1467
--------------------------------------------------------------------------------
This PR:
* Extends components functions (AF-2636) to backend;
* Add a function to retrieve a process SVG.
The way it was implemented was using a proxy mechanism. The class BackendFunctionLoaderService is responsible to look for backend functions, then the class BackendFunctionLoader calls the service to list the registered functions and register it on client side and also proxy calls to backend funcions.
Along with this we created ProcessSVGFunction, it uses Kie Server API to retrieve a process SVG. Notice it requires two parameters: containerId, process Id. It is also possible to …
=> AF-2637: Implement SVG backend Service for Kie Server

dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/ExternalComponentPropertiesEditor.java, dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/resources/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.properties, dashbuilder/dashbuilder-shared/dashbuilder-services-api/src/main/java/org/dashbuilder/external/model/ComponentParameter.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-properties-editor/uberfire-widgets-properties-editor-api/src/main/java/org/uberfire/ext/properties/editor/model/validators/MandatoryValidator.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-properties-editor/uberfire-widgets-properties-editor-api/src/main/java/org/uberfire/ext/properties/editor/model/validators/PropertyFieldValidator.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-properties-editor/uberfire-widgets-properties-editor-api/src/test/java/org/uberfire/ext/properties/editor/model/validators/MandatoryValidatorTest.java
**JIRA**: 
[AF-2702](https://issues.redhat.com/browse/AF-2702)
This is a PR for the mentioned JIRA above. It gives the options to make a field mandatory. However, bear in mind the limitation we currently have, for example, I can't lock user into the form until the user fill the mandatory field for now, this could be done in future, but this task would get too big if I add this.
What I did is basically visual warns to let users know that the field they are modifying is mandatory. I can't also modify the component editor properties pane right now because it is a shared API, so I just added this visual warning.
=> AF-2702: Support for component mandatory fields

uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json, uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java, uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java, uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/CreateProjectCmd.java, uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/ProjectResourceJobTest.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/LocaleContext.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/hooks/impl/MessageReader.java
* Added HeaderParam to include accept-language in Rest calls for createProject
**Issue:** The issue is caused by a failure to get custom post-commit notification messages while using the REST API to create the project. Currently, messages are fetched with RpcContext which is not active in REST calls.
**Solution:** Added a HttpHeader option in REST API to set a Locale. If Locale isn't available in Header param, default Locale will be used to get the custom messages.
**JIRA**: [RHDM-1354](https://issues.redhat.com/browse/RHDM-1354)
<details>
<summary>
</summary>
* <b>a compile downstream …
=> RHDM-1354: NPE creating a project using Decision Central REST API and githook configured

uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json, uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java, uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java, uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/CreateProjectCmd.java, uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/ProjectResourceJobTest.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/LocaleContext.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/hooks/impl/MessageReader.java
* RHDM-1354: NPE creating a project using Decision Central REST API and githook configured
* Added HeaderParam to include accept-language in Rest calls for createProject
(cherry picked from commit 6cd7da9a4beeeda93dc0a5e0048f43f7b637bc87)
**JIRA**: [RHDM-1354](https://issues.redhat.com/browse/RHDM-1354)
<details>
<summary>
</summary>
</details>
=> RHDM-1354: NPE creating a project using Decision Central REST API and githook configured (#1064)

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/DefaultKeyCloakTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManagerTest.java
… 
(cherry picked from commit f687e538ea0a1dd2a2d11aabf7b83f72f5fb7b36)
**RHPAM-2984**: https://issues.redhat.com/browse/RHPAM-2984 
**referenced Pull Requests**:https://github.com/kiegroup/appformer/pull/1066
</summary>
</details>
=> [Backport-7.44.x] RHPAM-2984 :RHPAM with RHSSO shows reserved roles as a groups as well 

appformer-js-monaco/pom.xml, dashbuilder/dashbuilder-shared/dashbuilder-js/pom.xml
Add appformer-js dependency to prevent js projects from building in parallel.
<details>
<summary>
</summary>
</details>
=> Add appformer-js dependency to prevent js projects from building in parallel

uberfire-extensions/uberfire-preferences-ui-client/src/main/resources/org/uberfire/ext/preferences/client/resources/i18n/Constants.properties, uberfire-preferences/uberfire-preferences-api/src/main/java/org/uberfire/preferences/shared/impl/validation/NumberPropertyValidator.java, uberfire-preferences/uberfire-preferences-api/src/test/java/org/uberfire/preferences/shared/impl/validation/NumberPropertyValidatorTest.java
- Added NumberPropertyValidator
**JIRA**: [AF-2693](https://issues.redhat.com/browse/AF-2693)
**referenced Pull Request**: https://github.com/kiegroup/kie-wb-common/pull/3511
**Business Central War**: [Download](https://drive.google.com/file/d/1U95fsGvygHVs8xTMwzcKtZ9Ji4gbt4jw/view?usp=sharing)
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: …
=> AF-2693: Add a system parameter to customize the number of assets in each page

uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/security/ProjectController.java, uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/security/ProjectControllerTest.java
**AF-2694**: https://issues.redhat.com/browse/AF-2692
Related PR's
https://github.com/kiegroup/kie-wb-common/pull/3510
https://github.com/kiegroup/kie-wb-distributions/pull/1076
- Added 3 new security permissions under Workbench permission to hide/show the project toolbar, Metrics tab and change request tab.
<details>
<summary>
</summary>
* <b>an upstream build</b> please …
=> AF-2692 : Add a security permission to show project toolbar, Metrics tab and change request tab

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-api/src/main/java/org/uberfire/ext/security/management/api/exception/ClientNotFoundException.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/BaseKeyCloakManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/CredentialsClientFactory.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KCAdapterClientFactory.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakUserManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/Keycloak.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/resource/ClientResource.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/resource/ClientsResource.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/BaseKeyCloakTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/DefaultKeyCloakTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManagerTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakUserManagerTest.java
**BAPL-1735**: _https://issues.redhat.com/browse/BAPL-1735_ 
- Added a new system property **-Dorg.uberfire.ext.security.management.keycloak.use-resource-role-mapping=true** that allows the client roles in RHSSO to be fetched and used inside business central.
- All the operations like add,remove,assign user etc will be supported in business central for these client roles.
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: …
=> BAPL-1735 :[GSS-RFE] RHPAM + RHSSO customer asking for support of Client Roles

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/BaseKeyCloakManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/CredentialsClientFactory.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KCAdapterClientFactory.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/Keycloak.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/TokenManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/adapter/KCAdapterContextTokenManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/credentials/AuthSettings.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/credentials/AuthTokenManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/client/auth/credentials/AuthTokenManagerTest.java
**RHPAM-3396**: https://issues.redhat.com/browse/RHPAM-3396
- Allows RHPAM to use any configure clients with any resource name which allows flexibility while configuring clients.
related to - https://github.com/kiegroup/appformer/pull/1085
<details>
<summary>
</summary>
</details>
=> RHPAM-3396: Ability to use any client name instead of "kie" while configuring client roles with RHSSO

dashbuilder/dashbuilder-backend/dashbuilder-kie-server-backend/src/main/java/org/dashbuilder/kieserver/backend/RuntimeKieServerDataSetProvider.java, dashbuilder/dashbuilder-runtime/pom.xml, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/DataSetContentListener.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/helper/PartitionHelper.java, dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/services/impl/RuntimeModelParserImpl.java, dashbuilder/dashbuilder-runtime/src/test/java/org/dashbuilder/backend/helper/PartitionHelperTest.java, dashbuilder/dashbuilder-runtime/src/test/java/org/dashbuilder/backend/services/impl/RuntimeModelParserImplTest.java, dashbuilder/dashbuilder-shared/dashbuilder-kie-server-api/src/main/java/org/dashbuilder/kieserver/RemoteDataSetDef.java, dashbuilder/dashbuilder-shared/dashbuilder-kie-server-api/src/main/java/org/dashbuilder/kieserver/RuntimeKieServerDataSetProviderType.java
JIRA:
https://issues.redhat.com/browse/AF-2757
If you have a dataset with ID X, create on Kie Server Y, then when importing in Dashbuilder with dataset partition the  ID X will become "X| RuntimeModel=runtimeModel". The problem is that on Kie Server Y the query for X was created with name "X" (it uses the dataset UUID), so an error will be throws.
This PR fixes this issue by creating a new field in the dataset definition to set the correct query name after the partition.
=> AF-2757: Kie Server DataSet lookup fails in multi mode with dataset partition

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUpload.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultFileEditorPresenter.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultFileEditorView.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUploadParametersTest.java, uberfire-server/src/main/java/org/uberfire/server/FileUploadServlet.java, uberfire-server/src/main/java/org/uberfire/server/UploadUriProvider.java, uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
* Added isUpdate parameter to DefaultEditorFileUpload to bypass file exist check in FileUploadServlet
**JIRA**: 
[AF-2781](https://issues.redhat.com/browse/AF-2781) 
[RHPAM-3277](https://issues.redhat.com/browse/RHPAM-3277) 
Summary: While we use the Default file upload editor to update any file in a project/repo, the upload fails due to a check that if the file already it should send a failed response back. This prevents us to update any file with the editor. These changes ensure that file upload is successful in the editor.
With this approach, if we have multiple users trying to edit the same file, the latest change overrides the previous change.
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins …
=> AF-2781: "project.repositories" upload function doens't work

appformer-kogito-bridge/pom.xml, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/notifications/NoOpNotificationsService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/notifications/NotificationsApi.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/notifications/NotificationsApiInteropWrapper.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/notifications/NotificationsService.java, appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/notifications/NotificationsServiceProducer.java, appformer-kogito-bridge/src/main/resources/org/appformer/kogito/bridge/AppformerKogitoBridge.gwt.xml, uberfire-api/src/main/java/org/uberfire/lifecycle/Validate.java, uberfire-api/src/main/java/org/uberfire/workbench/model/bridge/Notification.java, uberfire-api/src/main/java/org/uberfire/workbench/model/bridge/NotificationSeverity.java, uberfire-api/src/main/java/org/uberfire/workbench/model/bridge/NotificationType.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/WorkbenchClientEditorActivity.java, uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/GWTEditorNativeRegister.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/java/org/uberfire/annotations/processors/WorkbenchClientEditorProcessorTest.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchClientEditorTest8.java, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest6.expected, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest8.expected, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/ClientEditorActivityGenerator.java, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java, uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/facades/APIModule.java, uberfire-workbench/uberfire-workbench-processors/src/main/resources/org/uberfire/annotations/processors/templates/activityClientEditor.ftl
**JIRA**: 
https://issues.redhat.com/browse/KOGITO-3846
* https://github.com/kiegroup/appformer/pull/1092
* https://github.com/kiegroup/kie-wb-common/pull/3538
* https://github.com/kiegroup/kogito-tooling/pull/374
**Details:**
This PR adds the Notification API that let GWT send notifications to Channels. There are two main notifications: Alerts and Problems. 
* Alerts: ephemeral notification, i.e: Popup. If the notification contains a non empty path it will display a button to open that path. Alerts severity can be INFO, ERROR or WARNING.
* Problems: Notifications that needs to be informed to the users an keep persisted until the problem is fixed. i.e: Problems tab in VSCode. Problems severity can be INFO, …
=> KOGITO-3846: Added Notifications API to Editors

appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/notifications/NotificationsApi.java
You are welcome! ^
@adrielparedes there is an issue running kie-wb-common-dmn-webapp-kogito-testing with notifications API.
Looks like now we need to explicitly declare JS interop on interfaces from other modules. (but I'm 100% not sure: https://github.com/google/jsinterop-annotations/issues/2)(and maybe we need to add global or window for it)
What I know that this fixed the gwt:run  on kie-wb-common-dmn-webapp-kogito-testing and also both dmn and bpmn kogito showcase, but  I didn't try if this breaks anything on notification API.
@adrielparedes can you please take a look at this Monday morning?
=> JS interop fix on kie-wb-common-dmn-webapp-kogito-testing

dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/main/java/org/dashbuilder/external/impl/ComponentAssetProviderImpl.java, dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/test/java/org/dashbuilder/external/impl/ComponentAssetProviderImplTest.java
https://issues.redhat.com/browse/RHPAM-3412
Fix for RHPAM-3412
*Reproduce the issue*
* Setup RHPAM/jbpm on Windows
* Start the server, login, go to Pages;
* Create a new page and you should see the issue (Not Found error)
This is caused due the classic issue with inverted in Windows. It works for external components, but fails with internal components, which are loaded from the classpath.
The solution is simply replace Window slashes when loading internal components.
=> RHPAM-3412: Getting not found error for heatmap on windows

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUpload.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultFileEditorPresenter.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultFileEditorView.java, uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUploadParametersTest.java, uberfire-server/src/main/java/org/uberfire/server/FileUploadServlet.java, uberfire-server/src/main/java/org/uberfire/server/UploadUriProvider.java, uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
* Added isUpdate parameter to DefaultEditorFileUpload to bypass file exist check in FileUploadServlet
(cherry picked from commit c2f748de045a00f98ca06e69826798345679aae0)
**JIRA**: 
[AF-2781](https://issues.redhat.com/browse/AF-2781)
[RHPAM-3277](https://issues.redhat.com/browse/RHPAM-3277)
<details>
<summary>
</summary>
</details>
=> AF-2781: "project.repositories" upload function doens't work (#1094)

uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest6.expected, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest7.expected, uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchClientEditorTest8.expected, uberfire-workbench/uberfire-workbench-processors/src/main/resources/org/uberfire/annotations/processors/templates/activityClientEditor.ftl
**JIRA**: https://issues.redhat.com/browse/KOGITO-4399
A null was sent instead of a Promise, that makes the editor that doesn't implement (yet) the validation to break.
* https://github.com/kiegroup/appformer/pull/1101
* https://github.com/kiegroup/kogito-tooling/pull/417
<details>
<summary>
</summary>
</details>
=> KOGITO-4399: Activity Client Editor template returns a Promise instead of null

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/BaseKeyCloakManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/CredentialsClientFactory.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KCAdapterClientFactory.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/Keycloak.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/TokenManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/adapter/KCAdapterContextTokenManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/credentials/AuthSettings.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/credentials/AuthTokenManager.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/client/auth/credentials/AuthTokenManagerTest.java
**RHPAM-3396**: _https://issues.redhat.com/browse/RHPAM-3396_ 
Master branch PR : https://github.com/kiegroup/appformer/pull/1095
<details>
<summary>
</summary>
</details>
=> [backport-7.48.x] RHPAM-3396: Ability to use any client name instead of "kie" while configuring client roles with RHSSO

uberfire-message-console/uberfire-message-console-api/src/main/java/org/guvnor/messageconsole/events/PublishBaseEvent.java, uberfire-message-console/uberfire-message-console-api/src/main/java/org/guvnor/messageconsole/events/UnpublishMessagesEvent.java, uberfire-message-console/uberfire-message-console-backend/src/main/java/org/guvnor/messageconsole/backend/BuildResultsObserver.java, uberfire-message-console/uberfire-message-console-client/pom.xml, uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleService.java, uberfire-message-console/uberfire-message-console-client/src/test/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceTest.java, uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/builder/model/BuildResults.java, uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/builder/model/IncrementalBuildResults.java, uberfire-project/uberfire-project-builder/src/main/java/org/guvnor/common/services/builder/ResourceChangeIncrementalBuilder.java
**RHPAM-2647**: _https://issues.redhat.com/browse/RHPAM-2647_ 
**Current Behaviour**: Error message in a project was shown to all users, irrespective of the opened project and branch.
**Expected Behaviour** : Error message is only shown to users who are in same project and same branch. This is done since BC projects are shared in nature and users access the same version of a project repository.
Related PR:
https://github.com/kiegroup/kie-wb-common/pull/3546
<details>
<summary>
</summary>
* <b>a full production …
=> RHPAM-2647 :[GSS](7.z) Errors when building a project are shown to all users

uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/file/upload/AbstractFileServlet.java
As part of DROOLS-6213 we cleaned up codebase for uploading XLS decision tables and scorecards. During review of drools-wb changes, the same technical debt was found in the appformer abstract class, that is overriden by drools-wb classes, enhanced as part of DROOLS-6213
For more details see:
- https://issues.redhat.com/browse/DROOLS-6213
https://github.com/kiegroup/drools-wb/pull/1477
=> DROOLS-6213: Apply try with resources for file upload

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/CommitTime.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitBasicAttributeView.java
- some code level optimization to help with this
**RHPAM-3557**: https://issues.redhat.com/browse/RHPAM-3557
<details>
<summary>
</summary>
</details>
=> RHPAM-3557 :Slow performance opening assets in projects with large commit history

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/index/directory/DirectoryLuceneIndex.java
**JIRA**:
[AF-2821](https://issues.redhat.com/browse/AF-2821)
This configuration was made to reduce the number of threads Lucene uses since all the indexing operations are serial and not parallel. Thanks @porcelli for the findings
<details>
<summary>
</summary>
</details>
=> AF-2821: Added SerialMergeScheduler to Lucene Directory configuration

uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java, uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/JobRequestHelperCreateModuleTest.java
* Updated the JobStatus result with correct project name when the project is successfully created by REST
**JIRA**: 
[AF-2850](https://issues.redhat.com/browse/AF-2850)
[RHPAM-3519](https://issues.redhat.com/browse/RHPAM-3519)
<details>
<summary>
</summary>
</details>
=> AF-2850: Create project rest api should include project name in the response

uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json
**JIRA**: [BAQE-1904](https://issues.redhat.com/browse/BAQE-1904)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1665
=> BAQE-1904 - Change revapi to check against 7.52.0.Final

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/CommitTime.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitBasicAttributeView.java
(cherry picked from commit 3c80b8735158335ea227f67cd754789cf828b401)
**RHPAM-3557**: _https://issues.redhat.com/browse/RHPAM-3557_ 
main PR: https://github.com/kiegroup/appformer/pull/1131
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: <b>Jenkins …
=> [7.52.x] : RHPAM-3557: Slow performance opening assets in projects with large commit history

dashbuilder/dashbuilder-runtime/pom.xml
*JIRA*:  https://issues.redhat.com/browse/AF-2894
There's a WARN in server logs coming from DB Runtime:
```
WARN  [org.jboss.modules.define] (MSC service thread 1-8) Failed to define class org.uberfire.ext.preferences.processors.WorkbenchPreferenceProcessor in Module "deployment.dashbuilder-runtime.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link org/uberfire/ext/preferences/processors/WorkbenchPreferenceProcessor (Module "deployment.dashbuilder-runtime.war" from Service Module Loader): org/uberfire/annotations/processors/AbstractErrorAbsorbingProcessor
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1096)
at …
```
=> AF-2894: java.lang.NoClassDefFoundError WARN messages when starting Dashbuilder Runtime

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/elytron/DefaultElytronIdentityHelper.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/elytron/ElytronIdentityHelperProducer.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/elytron/ElytronIdentityHelperProducerTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelper.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelperProducer.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelperProducerTest.java
- fix CDI issue that was bypassing the producer and injecting by default KeyCloakElytronIdentityHelper
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
=> [7.59.x] AF-2904: Cloning repository from BC with SSH does not work

uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationServiceImpl.java
Cherry-pick of: https://github.com/kiegroup/appformer/pull/1190
[RHPAM-3462](https://issues.redhat.com/browse/RHPAM-3462)
[RHPAM-3845](https://issues.redhat.com/browse/RHPAM-3845)
=> [7.59.x] RHPAM-3845 : Imported projects not visible after migration from RHPAM 6.4 to 7.11

pom.xml, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/ElytronAuthenticationService.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/IOServiceSecuritySetup.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/elytron/DefaultElytronIdentityHelper.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/elytron/ElytronIdentityHelper.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/elytron/ElytronIdentityHelperProducer.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/ElytronAuthenticationServiceTest.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/elytron/DefaultElytronIdentityHelperTest.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/elytron/ElytronIdentityHelperProducerTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/pom.xml, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KCAdapterUserManagementService.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KCCredentialsUserManagementService.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelper.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelperProducer.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelperProducerTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelperTest.java
Added a `ElytronIdentityHelper` interface to help `ElytronAuthenticationService` to obtain the user credentials in different platform settings. The implementations are:
- `DefaultElytronIdentityHelper`: Keeps the same behaviour that the old `ElytronAuthenticationService`, uses the `WorkbenchUserManager` to obtain the `User` when the credentials are validated.
- `KeyCloakElytronIdentityHelper`: Only available when Keycloak extension is there, it does a login on Keycloak and if the login is successful it returns a valid `User`. It requires a *keycloak-config-file* to exist (as specified in the [documentation](https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.8/html-single/integrating_red_hat_process_automation_manager_with_red_hat_single_sign-on/index#sso-rem …
=> AF-2911: Cannot clone project by ssh when business central is integrated with Keycloak

dashbuilder/dashbuilder-runtime/pom.xml
**JIRA**: [_KOGITO-6404_ ](https://issues.redhat.com/browse/KOGITO-6404)
Log4J is not used with Dashbuilder, hence we are removing this dependency.
Merge with:
https://github.com/kiegroup/kie-soup/pull/239
=> KOGITO-6404: Remove unused loggers in Dashbuilder

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderConfiguration.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitSSHConfigSessionFactory.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitSSHConfigSessionFactoryTest.java
- this adds a new system property (**org.uberfire.nio.git.proxy.type**) to choose between 3 proxy types i.e http, sock5, sock4.
- For ex: to connect to a proxy server on sock5 protocol and with host 127.0.0.1 and port 8888 it looks like this. 
**-Dorg.uberfire.nio.git.proxy.ssh.over.http=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888 -Dorg.uberfire.nio.git.proxy.type=sock5**
- Default  value of this property is "http" for backward compatibility
**RHPAM-3954**: [_(please edit the JIRA link if it exists)_ ](https://issues.redhat.com/browse/RHPAM-3954)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories …
=> RHPAM-3954 :Import a project via SSH is not working over a proxy

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderConfiguration.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitSSHConfigSessionFactory.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitSSHConfigSessionFactoryTest.java
- This adds a new system property (org.uberfire.nio.git.proxy.type) to choose between 3 proxy types i.e http, sock5, sock4.
For ex: to connect to a proxy server on sock5 protocol and with host 127.0.0.1 and port 8888 it looks like this.
-Dorg.uberfire.nio.git.proxy.ssh.over.http=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888 -Dorg.uberfire.nio.git.proxy.type=sock5
- Default value of this property is "http" for backward compatibility
RHPAM-3954: (https://issues.redhat.com/browse/RHPAM-3954)
Main branch PR: 
https://github.com/kiegroup/appformer/pull/1223
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any …
=> [7.59.x] RHPAM-3954 :Import a project via SSH is not working over a proxy

uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json
**JIRA:** [BAQE-2254](https://issues.redhat.com/browse/BAQE-2254)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1923
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
=> BAQE-2254 - Change revapi to check against 7.67.0.Final

uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json
**JIRA**: [BAQE-2253](https://issues.redhat.com/browse/BAQE-2253)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1925
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
=> [7.67.x] BAQE-2253 - Change revapi to check against 7.59.0.Final

appformer-js-monaco/yarn.lock, appformer-js/yarn.lock
JIRA: [AF-2936](https://issues.redhat.com/browse/AF-2936)
This PR will upgrade following dependancies :
[Bump https-proxy-agent from 2.2.1 to 2.2.4](https://github.com/kiegroup/appformer/pull/1271/commits/0ed5d0cd339e16151768c3b5ae4a87b3618bb90b)
[Bump acorn from 5.7.3 to 5.7.4 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/a66b61e3c5d24cea28e41bc66092327277fa6571)
[Bump ini from 1.3.5 to 1.3.8 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/cba3aa75ab96984fddc98e87cb46aec079570b32)
[Bump mixin-deep from 1.3.1 to 1.3.2 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/80a101be9dae2e679a0a81f7c80eef75e7a7368b)
[Bump lodash.template from 4.4.0 to 4.5.0 in …
=> AF-2936: dependabot upgrades on appformer

appformer-js-monaco/package.json, appformer-js-monaco/pom.xml, appformer-js/package.json, appformer-js/pom.xml, appformer-js/yarn.lock, dashbuilder/dashbuilder-shared/dashbuilder-js/package.json, dashbuilder/dashbuilder-shared/dashbuilder-js/pom.xml, dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
https://issues.redhat.com/browse/BXMSPROD-1700
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2110
* https://github.com/kiegroup/appformer/pull/1320
* https://github.com/kiegroup/process-migration-service/pull/80
* https://github.com/kiegroup/kie-wb-common/pull/3785
=> [7.67.x] [BXMSPROD-1700] @kie/lock-treatment-tool removed from package.json

appformer-js-monaco/package.json, appformer-js-monaco/pom.xml, appformer-js/package.json, appformer-js/pom.xml, appformer-js/yarn.lock, dashbuilder/dashbuilder-shared/dashbuilder-js/package.json, dashbuilder/dashbuilder-shared/dashbuilder-js/pom.xml, dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
https://issues.redhat.com/browse/BXMSPROD-1700
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2109
* https://github.com/kiegroup/appformer/pull/1321
* https://github.com/kiegroup/process-migration-service/pull/81
* https://github.com/kiegroup/kie-wb-common/pull/3786
=> [7.67.x-blue] [BXMSPROD-1700] @kie/lock-treatment-tool removed from package.json

uberfire-rest/uberfire-rest-backend/pom.xml, uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java, uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/ProjectResourceJobTest.java, uberfire-structure/uberfire-structure-backend/pom.xml, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/InputEscapeUtils.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java, uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java, uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/InputEscapeUtilsTest.java, uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java, uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryServiceImplTest.java
Fixes RHPAM-4716 & RHPAM-4717 by using `StringEscapeUtils:: escapeHtml4()` meth
od in `ProjectResource` and by implementing helper method, using `escapeHtml4()`, to escape contributors names in `OrganizationalUnitServiceImpl`
**JIRA**: [RHPAM-4719](https://issues.redhat.com/browse/RHPAM-4719) 
Resulted contributor page after calling update with XSS valid name.
=> RHPAM-4719: Persistent Cross-Site Scripting (XSS)

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/elytron/DefaultElytronIdentityHelper.java, uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/elytron/ElytronIdentityHelperProducer.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/elytron/DefaultElytronIdentityHelperTest.java, uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/elytron/ElytronIdentityHelperProducerTest.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelperProducer.java, uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/elytron/KeyCloakElytronIdentityHelperProducerTest.java
**JIRA**: 
[DROOLS-7558](https://issues.redhat.com/browse/DROOLS-7558)
WorkbenchUserManager depends on the Elytron file system realm and for that reason can not find or log in the user.
[war](https://drive.google.com/file/d/1C19LaBOiX7hPvyJOo6_G9ATN05MxpT_v/view?usp=drive_link)
<details>
<summary>
</summary> …
=> DROOLS-7558 : SSH clone: Fetch roles for the logged in user from the realm itself

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingService.java, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java
Updates the version of infinispan to fix several CVEs.
Related PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2485
=> [7.67.x-blue] Update infinispan to 14.0.27.Final.

uberfire-io/src/test/java/org/uberfire/io/CommonIOExceptionsServiceDotFileTest.java, uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-fs/src/test/java/org/uberfire/java/nio/fs/file/SimpleFileSystemProviderTest.java
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2490
* https://github.com/kiegroup/appformer/pull/1424
* https://github.com/kiegroup/kie-wb-common/pull/3832
<details>
<summary>
</summary>
[build-chain …
=> Changed commons-io exception due upgrade of dependency

pom.xml, uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …
=> [7.67.x-blue] Bump `protostream` to 4.6.5
