- pom.xml
Based on https://github.com/uberfire/uberfire-extensions/commit/526c84d9b23f6174da22e8503367507094a17583
> BZ-1066962: upgrade JGit version (override BOM) in order to add standard git hooks

- livespark-form-modeler/livespark-form-modeler-api/src/main/java/org/livespark/formmodeler/model/FieldDefinition.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/java/org/livespark/formmodeler/renderer/client/rendering/FieldRenderer.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/FormEditorHelper.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/FormEditorPresenter.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/FormEditorViewImpl.html
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/FormEditorViewImpl.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/dataHolder/DataObjectsAdminViewImpl.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/preview/PreviewFormPresenter.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/preview/PreviewFormPresenterViewImpl.html
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/preview/PreviewFormPresenterViewImpl.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/rendering/DraggableFieldComponent.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/resources/i18n/FormEditorConstants.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/resources/org/livespark/formmodeler/editor/client/resources/i18n/FormEditorConstants.properties
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/test/java/org/livespark/formmodeler/editor/client/editor/preview/PreviewFormPresenterTest.java
- Fixed UI issue on form previews ( temporary removed tabs and added a modal to display the preview).
- Fixed error loading Components Palette
> Fixed issues on form previews & initializing editor

- livespark-form-modeler/livespark-form-modeler-codegen/livespark-form-modeler-codegen-impl/src/main/java/org/livespark/formmodeler/codegen/model/impl/ConstructorGenerator.java
- livespark-form-modeler/livespark-form-modeler-codegen/livespark-form-modeler-codegen-impl/src/main/java/org/livespark/formmodeler/codegen/model/impl/RoasterFormModelSourceGenerator.java
- livespark-form-modeler/livespark-form-modeler-codegen/livespark-form-modeler-codegen-impl/src/test/java/org/livespark/formmodeler/codegen/model/impl/RoasterFormModelSourceGeneratorTest.java
Unit test for RoasterFormModelSourceGenerator class, small refactoring and a fix of situation where empty dataHolders set is passed to the generator and two constructors are generated.
> RoasterFormModelSourceGeneratorTest & related changes

- livespark-common-widgets/livespark-crud-component/src/main/java/org/livespark/widgets/crud/client/component/CrudComponent.java
- livespark-common-widgets/livespark-crud-component/src/main/java/org/livespark/widgets/crud/client/component/CrudComponentViewImpl.java
- livespark-common-widgets/livespark-crud-component/src/test/java/org/livespark/widgets/crud/client/component/AbstractCrudComponentTest.java
- livespark-common-widgets/livespark-crud-component/src/test/java/org/livespark/widgets/crud/client/component/CrudComponentTest.java
- livespark-common-widgets/livespark-crud-component/src/test/java/org/livespark/widgets/crud/client/component/mock/CrudComponentMock.java
- livespark-form-modeler/livespark-form-modeler-rendering/livespark-form-modeler-rendering-api/src/main/java/org/livespark/formmodeler/rendering/client/view/ListView.java
- livespark-form-modeler/livespark-form-modeler-rendering/livespark-form-modeler-rendering-api/src/test/java/org/livespark/formmodeler/rendering/test/ListViewTest.java
- livespark-form-modeler/livespark-form-modeler-rendering/livespark-form-modeler-rendering-api/src/test/java/org/livespark/formmodeler/rendering/test/res/TestFormView.java
- livespark-form-modeler/livespark-form-modeler-rendering/livespark-form-modeler-rendering-api/src/test/java/org/livespark/formmodeler/rendering/test/res/TestListView.java
This refactoring is a required step towards decoupling generated list views, form views, and rest services from each other.
@pefernan could you please review this?
> Refactor CrudComponentView to move more logic to presenter.

- livespark-integration-tests/pom.xml
- livespark-showcase/livespark-webapp/src/test/java/org/livespark/client/LiveSparkEntryPointTest.java
Fixes a broken test in LiveSparkEntryPointTest and moves the BuildAndDeploymentTests to a maven profile so that they do not run on Jenkins, but can be run locally.
> Test fixes

- livespark-form-modeler/livespark-form-modeler-api/src/main/java/org/livespark/formmodeler/model/impl/basic/slider/IntegerSliderDefinition.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/AbstractFormRenderingContext.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/DynamicGenerator.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/FormRenderingContext.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/FormRenderingContextGenerator.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/FormRenderingContextGeneratorService.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/SelectorDataProviderManager.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/StaticGenerator.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/main/java/org/livespark/formmodeler/renderer/service/impl/DynamicRenderingContext.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-api/src/test/java/org/livespark/formmodeler/renderer/test/util/MockFormRenderingContext.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/main/java/org/livespark/formmodeler/renderer/backend/service/impl/DMOBasedTransformerContext.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/main/java/org/livespark/formmodeler/renderer/backend/service/impl/FormRenderingContextGeneratorImpl.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/main/java/org/livespark/formmodeler/renderer/backend/service/impl/FormRenderingContextGeneratorServiceImpl.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/main/java/org/livespark/formmodeler/renderer/backend/service/impl/processors/SliderAnnotationProcessor.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/test/java/org/livespark/formmodeler/renderer/backend/service/impl/AbstractFormRenderingContextGeneratorTest.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/test/java/org/livespark/formmodeler/renderer/backend/service/impl/BasicFormRenderingContextGeneratorTest.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/test/java/org/livespark/formmodeler/renderer/backend/service/impl/InheritanceFormRenderingContextGeneratorTest.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-backend/src/test/java/org/livespark/formmodeler/renderer/backend/service/impl/NestedFormsFormRenderingContextGeneratorTest.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/pom.xml
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/java/org/livespark/formmodeler/renderer/client/DynamicFormRenderer.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/java/org/livespark/formmodeler/renderer/client/DynamicFormRendererViewImpl.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/java/org/livespark/formmodeler/renderer/client/rendering/FieldLayoutComponent.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/java/org/livespark/formmodeler/renderer/client/rendering/FieldRenderer.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/resources/org/livespark/formmodeler/renderer/FormModelerDynamicRendererClient.gwt.xml
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/test/java/org/livespark/formmodeler/renderer/client/DynamicFormRendererMock.java
- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/test/java/org/livespark/formmodeler/renderer/client/DynamicFormRendererTest.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-backend/src/main/java/org/livespark/formmodeler/editor/backend/dataProviders/VFSSelectorFormProvider.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-backend/src/main/java/org/livespark/formmodeler/editor/backend/service/impl/FieldPropertiesServiceImpl.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/FormEditorPresenter.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/preview/PreviewFormPresenter.java
This fixes some CDI issues when injecting FormRenderingContextGenerator.
> Moved annotation processing mechanism to use DMO instead of reflection II. Fixing integration issues.

- livespark-form-modeler/livespark-form-modeler-dynamic-renderer/livespark-form-modeler-dynamic-renderer-client/src/main/java/org/livespark/formmodeler/renderer/client/rendering/FieldLayoutComponent.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/editor/FormEditorPresenter.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/java/org/livespark/formmodeler/editor/client/resources/i18n/FormEditorConstants.java
- livespark-form-modeler/livespark-form-modeler-editor/livespark-form-modeler-editor-client/src/main/resources/org/livespark/formmodeler/editor/client/resources/i18n/FormEditorConstants.properties
Depends on https://github.com/uberfire/uberfire/pull/459
> [UF-348] Apply UX design on new Layout Editor

- livespark-showcase/livespark-webapp/pom.xml
- livespark-showcase/livespark-webapp/src/main/java/org/livespark/backend/server/preferences/LiveSparkPreferencesLoader.java
- livespark-showcase/livespark-webapp/src/main/java/org/livespark/client/LiveSparkEntryPoint.java
- livespark-showcase/livespark-webapp/src/main/java/org/livespark/client/resources/i18n/AppConstants.java
- livespark-showcase/livespark-webapp/src/main/resources/datasource-management.properties
- livespark-showcase/livespark-webapp/src/main/resources/org/livespark/LiveSpark.gwt.xml
- livespark-showcase/livespark-webapp/src/main/resources/org/livespark/client/resources/i18n/AppConstants.properties
- Integrates the data source management perspective in the LS WB.
> JBPM-5233: Data source management

- livespark-form-modeler/livespark-form-modeler-rendering/livespark-form-modeler-rendering-api/src/main/java/org/livespark/formmodeler/rendering/server/rest/BaseEntityService.java
Fixes a compilation issue in the generated LS app.
> Add back mistakenly deleted method in BaseEntityService.

- livespark-deployment/pom.xml
- livespark-deployment/src/main/java/org/livespark/backend/server/service/CDIPipelineEventListener.java
- livespark-deployment/src/main/java/org/livespark/backend/server/service/GwtWarBuildServiceImpl.java
- livespark-deployment/src/test/java/org/livespark/deployment/tests/RestPipelineImplTest.java
- livespark-deployment/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
- livespark-deployment/src/test/resources/arquillian.xml
- livespark-deployment/src/test/resources/logback-test.xml
- livespark-deployment/src/test/resources/wildfly/Dockerfile
- livespark-showcase/livespark-webapp/src/main/java/org/livespark/backend/server/AppSetup.java
- livespark-showcase/livespark-webapp/src/main/java/org/livespark/backend/server/HTTPSessionGWTCodeServerPortLeaser.java
- livespark-showcase/livespark-webapp/src/main/java/org/livespark/backend/server/PipelineEventsObserverOutput.java
- livespark-showcase/livespark-webapp/src/main/resources/mgmt-groups.properties
- livespark-showcase/livespark-webapp/src/main/resources/mgmt-users.properties
This PR is adding the pipelines to support Dev and SuperDevMode in LS via the pipelines. 
This pull request depends on this PR in Guvnor: 
https://github.com/droolsjbpm/guvnor/pull/380
@mbarkley please test this.
> Pipelines for DevMode and SuperDevMode

- livespark-showcase/livespark-webapp/pom.xml
- livespark-showcase/livespark-webapp/src/main/java/org/livespark/client/LiveSparkEntryPoint.java
- livespark-showcase/livespark-webapp/src/main/resources/datasource-management.properties
- adds the by default drivers
- removes duplicated datasources perspective from extensions menu
- adds the dashbuilder integration component
> Data sources configurations update

- appformer-showcase/appformer-webapp/pom.xml
Preference API changed, so I needed to make some minor changes here.
Dependes on: uberfire/uberfire#605
> [UF-459]: Refactor - Extract Preference API from extensions

- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/navbar/AppNavBar.html
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/navbar/AppNavBar.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/navbar/LogoNavBar.html
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/navbar/LogoNavBar.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/navbar/LogoWidgetView.java
Depends on uberfire/uberfire#573
> [UF-443] - Header and Footer should support Errai UI

- appformer-form-modeler/appformer-form-modeler-rendering/appformer-form-modeler-rendering-api/src/main/java/org/kie/appformer/formmodeler/rendering/client/flow/FlowProducer.java
- appformer-provisioning/appformer-provisioning-backend/src/main/java/org/kie/appformer/provisioning/backend/service/GwtWarBuildServiceImpl.java
- fixes a problem when there 2 or more entities that breaks the RPCProxies initialization
- fixes the local deployment when an external datasource is selected
> Bug fixing

- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/AbstractNestedModelHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/ListBoxHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/ObjectSelectorBoxHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/PictureHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/RadioGroupHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/SubFormHelper.java
- appformer-form-modeler/appformer-form-modeler-rendering/appformer-form-modeler-rendering-api/src/main/java/org/kie/appformer/formmodeler/rendering/client/view/FormView.java
- appformer-showcase/appformer-webapp/pom.xml
This PR fixes issues on source generation that appeard after some the Roaster version upgrade. See https://github.com/droolsjbpm/appformer/pull/71 for more info.
It also includes:
- Fixing data binding issues on FormView's
- Adding right scope to appformer-provisioning-client
Comment merge with: https://github.com/droolsjbpm/kie-wb-common/pull/677
> Fixing Roaster upgrade issues

- appformer-flow/appformer-flow-lang/src/main/java/org/kie/appformer/flow/lang/Compiler.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/html/util/HTMLTemplateFormatter.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/AbstractNestedModelHelper.java
- Fixing compilation issue
@mbarkley as discussed today here is the change.
> Fixing small issues:

- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/DatePickerHelper.java
- appformer-provisioning/appformer-provisioning-backend/src/main/java/org/kie/appformer/provisioning/backend/service/GwtWarBuildServiceImpl.java
- Adding some control for DatePicker on static forms.
@wmedvede as talked on irc... can you please take a look?
> GUVNOR-2933: Refactor to use the right APIs

- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/FormSourcesGeneratorImpl.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-services/appformer-form-modeler-codegen-data-modeller/src/main/java/org/kie/appformer/formmodeler/codegen/services/datamodeller/impl/DataModellerFormGeneratorImpl.java
- appformer-form-modeler/appformer-form-modeler-editor/appformer-form-modeler-editor-backend/src/main/java/org/kie/appformer/formmodeler/editor/backend/service/impl/AppFormerFormEditorServiceImpl.java
> JBPM-5738: Add default configuration for fields that nest forms.

- appformer-ala-wildfly-provider/src/main/java/org/kie/appformer/ala/wildfly/executor/AppFormerWildflyRuntimeExecExecutor.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/backend/server/AppSetup.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/deployment/DevelopmentDeploymentExtension.java
Hi @pefernan would you mind review this PR?
Thanks
is required for the summit demo.
Depends on https://github.com/kiegroup/guvnor/pull/446
> Fixes and addings for the applications provisioning

- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/pom.xml
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/html/inputs/NumberBoxTemplateProvider.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/RoasterViewSourceGenerator.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/AbstractNumberBoxHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/RequiresValueConverter.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/DecimalBoxHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/IntegerBoxHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/resources/org/kie/appformer/formmodeler/codegen/view/impl/html/templates/numberbox.mv
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/test/java/org/kie/appformer/formmodeler/codegen/view/impl/inputs/impl/DecimalBoxHelperTest.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/test/java/org/kie/appformer/formmodeler/codegen/view/impl/inputs/impl/IntegerBoxHelperTest.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/test/java/org/kie/appformer/formmodeler/codegen/view/java/inputs/impl/BasicInputHelpersTest.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/test/java/org/kie/appformer/formmodeler/codegen/view/java/test/util/InputCreatorHelpersProvider.java
Added source generation components for new numeric field types
COMMENT: merge with https://github.com/kiegroup/kie-wb-common/pull/756
@pefernan can you review it?
> JBPM-5427: adding specific inputs types for numeric data to prevent number format exception

- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-api/src/main/java/org/kie/appformer/formmodeler/codegen/JavaSourceGenerator.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/rest/impl/RoasterRestImplSourceGenerator.java
This change is introduced by https://github.com/kiegroup/kie-wb-common/pull/830/files
> JBPM-5928: Removed unused classes

- appformer-deps/pom.xml
@porcelli @pefernan can you give a look?
> updating the uberfire version

- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/ListBoxHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/main/java/org/kie/appformer/formmodeler/codegen/view/impl/java/inputs/impl/RadioGroupHelper.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/test/java/org/kie/appformer/formmodeler/codegen/view/java/inputs/impl/RadioGroupHelperTest.java
- appformer-form-modeler/appformer-form-modeler-codegen/appformer-form-modeler-codegen-impl/src/test/java/org/kie/appformer/formmodeler/codegen/view/java/inputs/impl/SelectorsHelperTest.java
- appformer-showcase/appformer-webapp/pom.xml
> AF-553: Appformer showcase doesn't build

- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/AppFormerEntryPoint.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/editor/TextEditorPresenter.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/navbar/AppNavBar.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/navbar/LogoNavBar.java
- appformer-showcase/appformer-webapp/src/test/java/org/kie/appformer/client/AppFormerEntryPointTest.java
* Remove PlaceManagerActivityService
* Replace @AfterInitialization methods with @PostConstruct
> AF-546: Reduce startup time of AppFormer apps and workbenches

- appformer-form-modeler/appformer-form-modeler-editor/appformer-form-modeler-editor-backend/src/main/java/org/kie/appformer/formmodeler/editor/backend/service/impl/AppFormerFormEditorServiceImpl.java
- appformer-showcase/appformer-webapp/pom.xml
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/AppFormerEntryPoint.java
- appformer-showcase/appformer-webapp/src/main/java/org/kie/appformer/client/perspectives/M2RepoPerspective.java
- appformer-showcase/appformer-webapp/src/main/resources/org/kie/appformer/AppFormer.gwt.xml
- appformer-showcase/appformer-webapp/src/test/java/org/kie/appformer/client/AppFormerEntryPointTest.java
This PR fixes some issues caused by some changes on kie-wb-commons... to be merged before https://github.com/kiegroup/appformer/pull/93
@mbarkley can you take a look?
> Fixed issues 

- pom.xml
This commit was added to the uberfire repository after @porcelli reset this branch.
> Some pom clean-up and downgrade logback version to fix SDM error (#926)

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-api/src/main/java/org/uberfire/ext/security/management/api/exception/RealmManagementNotAuthorizedException.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-backend/src/main/java/org/uberfire/ext/security/management/service/UserManagerServiceImpl.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/main/java/org/uberfire/ext/security/management/client/ClientSecurityExceptionMessageResolver.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/main/java/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementClientConstants.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/main/resources/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementClientConstants.properties
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/test/java/org/uberfire/ext/security/management/client/ClientSecurityExceptionMessageResolverTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/README.md
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/BaseKeyCloakManager.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakUserManager.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/DefaultKeyCloakTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManagerTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakUserManagerTest.java
Hey @ederign  @tomasdavidorg 
This is the cherry pick for https://github.com/kiegroup/appformer/pull/113.
Tested in a Keycloak SSO environment as well.
Thanks!
> [7.5.x] AF-483: Security Management - Show friendly message when an operation is not authorized.

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementWidgetsConstants.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupCreationWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/BaseRoleEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/BaseUserEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/UserCreationWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowView.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.ui.xml
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/resources/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementWidgetsConstants.properties
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupCreationWorkflowTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflowTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/RoleEditorWorkflowTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/BaseUserEditorWorkflowTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/UserCreationWorkflowTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/UserEditorWorkflowTest.java
Hey @ederign @tomasdavidorg 
This is the cherry-pick for https://github.com/kiegroup/appformer/pull/112 into `7.5.x`, which has been already merged on master.
Thanks!
> [7.5.x] AF-467: Security management - Show a warning notification if user has no assignments set for both user edition/creation workflows.

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/Moment.java
Modified the Moment interface to allow initialize with a date formatted and also make available the relative time fromNow formatting.
> RHBPMS-4926: Added Moment builder and fromNow formatting

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProviderTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/BatchIndexSingleThreadTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/suite/ElasticSearchTestSuite.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/resources/elasticsearch.yml
All "/" inside index names are replaced with "_". 
@jhrcek
> [RHDM-217]: Error "Invalid index name [system_ou/plugins]" when using elastic search

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/pom.xml
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridColumn.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/CoordinateUtilities.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseUpHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/GridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMerged.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/GridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelper.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/CoordinateUtilitiesTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetTest.java
Moving my fork into ```kiegroup/master``` to facilitate improved ongoing development and contribution.
The DMN Editor is not added as a dependency to any downstream webapp so remains "invisible".
> DROOLS-1946: DMN Editor

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/EditorTreeProvider.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/authz/EditorTreeProviderTest.java
See https://issues.jboss.org/browse/DROOLS-2181
The problem was that two instances of the underlying View widget were being created; one for the actual editor (as seen by the User) and another hidden instance used to drive Editor permissions. The two instances both responded to various CDI events triggered from User interactions in the editor causing the unexpected behaviour.
An alternative approach was to simply make the Editor ```@ApplicationScoped``` but I thought to fix the cause of the issue (as other editors are subject to permissions by default - in BxMS - and any editor at the User's volition).
> DROOLS-2181: Icons (Edit, Collapse, Delete etc) do not respond to mouse clicks

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/EditorTreeProvider.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/authz/EditorTreeProviderTest.java
See https://issues.jboss.org/browse/DROOLS-2181
This is the corollary of https://github.com/kiegroup/appformer/pull/122 for 7.5.x
(cherry picked from commit b7bb7760edaf07a3f24fc29694d03732075f2289)
> [7.5.x] DROOLS-2181: Icons (Edit, Collapse, Delete etc) do not respond to mouse clicks

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridCellSelectionsTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridGroupingTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridRowsMergedTest.java
Fixes following https://github.com/kiegroup/appformer/pull/129
> DROOLS-1946: Change implementation of moving rows. Fixes.

- dashbuilder/dashbuilder-client/dashbuilder-navigation-client/pom.xml
- dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/NavigationManager.java
- dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/impl/NavigationManagerImpl.java
- dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/widget/editor/NavTreeEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/test/java/org/dashbuilder/client/navigation/widget/editor/NavTreeEditorTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/htmleditor/HtmlEditorPresenter.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/htmleditor/HtmlEditorView.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/ConfigurationContext.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditHTMLPresenter.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditHTMLView.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditHTMLPresenterTest.java
Cherry picked from https://github.com/kiegroup/appformer/pull/134
---
- https://github.com/kiegroup/appformer/pull/140
- https://github.com/kiegroup/kie-wb-distributions/pull/669
> RHDM-219: [Content Management] HTML panel causes errors when saving & when adding page to navigation tree

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/DateRangePickerOptions.java
Added a new configuration option to show a single datepicker
> RHBA-31:Unable to type Due Date when scheduling a Job

- uberfire-message-console/uberfire-message-console-client/pom.xml
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleService.java
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceRow.java
- uberfire-message-console/uberfire-message-console-client/src/test/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceRowTest.java
- uberfire-message-console/uberfire-message-console-client/src/test/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceTest.java
See https://issues.jboss.org/browse/AF-972
> AF-972: Wrong order of the validation messages

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/BearerAuthenticationInterceptor.java
Hey @ederign @tomasdavidorg 
This is the cherry-pick of https://github.com/kiegroup/appformer/pull/135 into `master` branch. I have tested it again and it works fine in master as well, anyway as commented before, please @tomasdavidorg would appreciate if you can give it a try too when you have a chance... :)
Thanks guys!!
> RHDM-233: Do not register the KC security management authentication client interceptor (for all requests)

- dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/layout/editor/PerspectiveDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DisplayerEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DisplayerEditorPopup.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/widgets/DisplayerEditorTest.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/pom.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/AreaChartDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/BarChartDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/BubbleChartDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/DisplayerDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/LineChartDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/MapChartDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/MeterChartDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/MetricDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/PerspectiveEditorReportingGroupProvider.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/PieChartDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/SelectorDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/TableDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/resources/i18n/Constants.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/resources/org/dashbuilder/client/editor/resources/i18n/Constants.properties
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/test/java/org/dashbuilder/client/editor/DisplayerDragComponentTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/LayoutDragComponent.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/widgets/LayoutDragComponentWidget.html
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/widgets/LayoutDragComponentWidget.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorPresenter.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/api/PerspectiveEditorComponentGroupProvider.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/api/PerspectiveEditorCoreGroupProvider.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/HTMLLayoutDragComponent.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/ScreenLayoutDragComponent.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorPresenterTest.java
@kkufova Ready for review => https://issues.jboss.org/secure/attachment/12429675/12429675_cms-displayerdragcomponents.mp4
> AF-927: [Layout Editor] Expose all the Displayer types as individual components

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/context/GridBodyColumnRenderContext.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/context/GridBoundaryRenderContext.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/context/GridHeaderColumnRenderContext.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/GridColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMerged.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/IntegerColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/StringColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/GridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelper.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/GridRendererTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/BlueTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/GreenTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/MultiColouredTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/RedTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTestUtils.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseColumnRendererTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/IntegerColumnRendererTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/StringColumnRendererTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/demo/grids/WiresGridsDemoPresenter.java
See https://issues.jboss.org/browse/DROOLS-2273
> DROOLS-2273: [DMN Editor] Contextual selection - Hover state

- pom.xml
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/pom.xml
(cherry picked from commit 3c72e8f3c48087bc5f82635f8ea8fb44ffde9dcb)
> RHDM-293: StatusLogger Log4j2 could not find a logging implementation

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMerged.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMergedTest.java
Dependent on #152 
@manstis please have a look
> DROOLS-2273: CleanUp the ColumnRenderingStrategyMerged class

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchDropDownView.java
@jhrcek @dgutierr could you please take a look?
> RHDM-277: Error appears when user filters items in dropdowns in SecurityManagementPerspective

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridCellSelectionsTest.java
@manstis please have a look
Sorry for the amount of changed lines, but in final I removed ~500 "test setup lines" from `GridCellSelectionsTest`
> DROOLS-2303: post review actions

- uberfire-organizationalunit-manager/src/main/java/org/guvnor/organizationalunit/manager/client/editor/OrganizationalUnitManagerPresenterImpl.java
- uberfire-organizationalunit-manager/src/main/java/org/guvnor/organizationalunit/manager/client/editor/OrganizationalUnitManagerViewImpl.java
- uberfire-organizationalunit-manager/src/test/java/org/guvnor/organizationalunit/manager/client/editor/OrganizationalUnitManagerPresenterTest.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/context/WorkspaceProjectContextChangeEvent.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/context/WorkspaceProjectContextChangeHandler.java
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/context/WorkspaceProjectContext.java
- uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/context/WorkspaceWorkspaceProjectContextTest.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryService.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
Fixes an issue introduced by AF-648 (Project Oriented).
> Fix UI issues when removing space with multiple projects.

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManager.java
(nio2) api to manipualte and extract repository name
> AF-989: the path manipulation was weak, now it's using direct path

- dashbuilder/dashbuilder-webapp/pom.xml
- dashbuilder/dashbuilder-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
- pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/pom.xml
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml
- uberfire-showcase/uberfire-webapp/pom.xml
https://issues.jboss.org/browse/RHDM-251
> [Do not MERGE yet] RHDM-251 Wildfly 11

- README.md
- uberfire-docs/docs/tutorial/ufTasks.md
- uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/screens/gadgets/GitHubCodeFrequencyStatsScreen.java
- uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/screens/gadgets/GitHubCommitActivityStatsScreen.java
- uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/screens/gadgets/GitHubPunchCardStatsScreen.java
Some URLs are pointing to the old uberfire repo and leading nowhere, updated to point in here.
> update GitHub URLs

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/GridCell.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/GridData.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridCell.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataSelectionsManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridRow.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/impl/CheckBoxDOMElement.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/impl/ListBoxDOMElement.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/impl/TextBoxDOMElement.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridCellSelectionsTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridColumnsTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridGroupingTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridMergingTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridRowsMergedTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/GridRowsUnmergedTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetKeyboardHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/GridCellSelectorMouseClickHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionStrategyTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/demo/grids/GridDataFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/demo/grids/WiresGridsDemoPresenter.java
See https://issues.jboss.org/browse/DROOLS-2272
> DROOLS-2272: [DMN Editor] Move Editor controls inline

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/FormStyleItem.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/FormStyleItem.ui.xml
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/FormStyleLayout.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/popups/FormStylePopup.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/FormStyleItemTest.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/FormStyleLayoutTest.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/popups/FormStylePopupTest.java
The issue [DROOLS-2323](https://issues.jboss.org/browse/DROOLS-2323)
@manstis 
This is ensemble:
- #189
- kiegroup/drools-wb#810
> DROOLS-2323: Provide method to add form attribute with help

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BoundingBoxPathClipperFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattenedTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayerTest.java
Dependent on #195 
@manstis  please have a look, I will rebase once your PR is in.
> DROOLS-2332: Increase coverage of column rendering strategy

- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/editor/MavenRepositoryPagedJarTable.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/upload/UploadFormViewImpl.java
https://issues.jboss.org/browse/AF-1037
https://github.com/kiegroup/appformer/pull/199
https://github.com/kiegroup/kie-docs/pull/694
https://github.com/kiegroup/optaplanner-wb/pull/258
https://github.com/kiegroup/drools-wb/pull/817
https://github.com/kiegroup/kie-tests/pull/18
https://github.com/kiegroup/kie-wb-distributions/pull/695
> AF-1037 : Business-central maven artifacts available at maven2wb without authorization

- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/editor/MavenRepositoryPagedJarTable.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/upload/UploadFormViewImpl.java
https://issues.jboss.org/browse/AF-1037
https://github.com/kiegroup/appformer/pull/200
https://github.com/kiegroup/kie-docs/pull/695
https://github.com/kiegroup/optaplanner-wb/pull/259
https://github.com/kiegroup/drools-wb/pull/818
https://github.com/kiegroup/kie-wb-distributions/pull/696
> [7.5.x] AF-1037 : Business-central maven artifacts available at maven2wb without authorization

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/GridColumn.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/context/GridBodyCellEditContext.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/CellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java
See JIRAs "Coding in progress" on https://issues.jboss.org/browse/DROOLS-2272
> DROOLS-2296: Inline controls: Undefined Expression selector

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/WorkspaceProjectService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryServiceImplTest.java
@paulovmr @ederign Can you review this please?
related to:
https://github.com/kiegroup/kie-wb-common/pull/1459
> [AF-1019]: Workspace and Repository service can rename project or repository if that name already exist

- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DataSetLookupEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/widgets/DataSetLookupEditorTest.java
@dgutierr here are the changes we talked about, hopefully that is all that is needed.
> DASHBUILDE-264 - Allow NUMBER columns to be used in displayers

- dashbuilder/dashbuilder-webapp/pom.xml
- dashbuilder/dashbuilder-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
- pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/pom.xml
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml
- uberfire-showcase/uberfire-webapp/pom.xml
Doing again reverted PR https://github.com/kiegroup/appformer/pull/145
> RHDM-251 - Wildfly 11 upgrade

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/KObjectUtil.java
@jhrcek could you review? I tried it importing a lot of example projects but I couldn't get the same result again, I will do a downstream build so you can test it.
Related to:
https://github.com/kiegroup/appformer/pull/213
https://github.com/kiegroup/kie-wb-common/pull/1464
> [AF-979]: Replaced MessageDigest with a Thread-Safe implementation

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayerTest.java
See https://issues.jboss.org/browse/DROOLS-2353
> DROOLS-2353: [DMN Editor] Add support for deleting expression type and revert to 'Undefined'

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/Layouts.java
See this https://github.com/kiegroup/lienzo-core/pull/7#issuecomment-369104382 discussion for more details.
> Disable blue border for panels in Google Chrome

- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
@tomasdavidorg could you review it please?
Related to:
https://github.com/kiegroup/appformer/pull/224
https://github.com/kiegroup/kie-wb-common/pull/1477
> [AF-1046]: Removed Repository created if the module couldn't be stored/created

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/util/Paths.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/util/PathsTest.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/util/TestPaths.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ConfiguredRepositoriesBySpace.java
https://issues.jboss.org/browse/AF-1035
Bundle consists of:
https://github.com/kiegroup/appformer/pull/209
https://github.com/kiegroup/kie-wb-common/pull/1462
https://github.com/kiegroup/optaplanner-wb/pull/260
> AF-1035 : [Project Oriented] Path trimming should be consistent with file:// and git://

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
AF-1072: Log the file system path in JGitFileSystemProvider
> AF-1072: Log the file system path in JGitFileSystemProvider

- uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/screens/MultiScreen.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multiscreen/MultiScreenMenuBuilder.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multiscreen/MultiScreenView.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/Button.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/Elemental2Producer.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/KebabMenu.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/multiscreen/MultiScreenMenuBuilderTest.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/KebabMenuTest.java
- Add drop position and separator helpers to KebabMenu
- Change button element to be used as ManagedInstance
- Update tests
> JBPM-7002 - Group action buttons in list table to kebab

- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/impl/git/GitRepository.java
Removes some unused fields (and warnings) found while working on another PR.
> Remove unused fields in GitRepository and JobRequestHelper.

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.ui.xml
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/resources/org/uberfire/ext/widgets/common/UberfireWidgetsCommons.gwt.xml
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/PagedTableTest.java
This reverts commit d76052c914374ad53382bf917012180a8dd50ada.
> Revert "JBPM-7003 - Update page size selector style to match PatterFly dropdown"

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multiscreen/MultiScreenView.less
Updated styles for multiscreen toolbar icons
> JBPM-6886: Update Dashboards layout. toolbar icons style

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/resources/i18n/Constants.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/Button.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/ConfirmPopup.html
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/ConfirmPopup.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/pfly/resources/i18n/Constants.properties
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/ConfirmPopupTest.java
- Adds the ability to optionally show an inline notification in the ConfirmPopup according to UX requeriment.
> JBPM-6876: Stunner - easy way to migrate from Stunner to current Designer

- dashbuilder/dashbuilder-client/dashbuilder-common-client/src/main/java/org/dashbuilder/common/client/editor/list/DropDownEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenter.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefExplorerScreen.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreen.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenterTest.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefExplorerScreenTest.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreenTest.java
- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/main/java/org/dashbuilder/client/widgets/dataset/editor/DataSetDefPreviewTable.java
- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/test/java/org/dashbuilder/client/widgets/dataset/editor/DataSetDefPreviewTableTest.java
- dashbuilder/dashbuilder-webapp/src/main/webapp/WEB-INF/datasets/expenseReports.dset
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
Fixes + tests
=> Depends on https://github.com/kiegroup/kie-soup/pull/37
@kkufova @romartin Can you verify please?
> Data set editor fixes

- uberfire-bom/pom.xml
- uberfire-project/uberfire-project-backend/src/test/resources/org/guvnor/common/services/project/backend/server/utils/pom3.xml
https://github.com/kiegroup/appformer/pull/247
https://github.com/kiegroup/kie-wb-common/pull/1511
https://github.com/kiegroup/kie-wb-distributions/pull/709
https://github.com/kiegroup/drools-wb/pull/832
https://github.com/kiegroup/optaplanner-wb/pull/264
> [AF-1074]: Removed unused OrganizationalUnitManager View that made connected clients crash.

- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
CRUD spaces should trigger a refresh on other users.
Child: https://github.com/kiegroup/appformer/pull/252
This is the first batch of https://issues.jboss.org/browse/AF-1108
drools-wb war https://www.dropbox.com/s/v6dnlrdlc4kibpg/drools-wb-webapp.war?dl=0
> CRUD space on one node should trigger a refresh on other nodes;

- uberfire-api/src/main/java/org/uberfire/workbench/type/FileNameUtil.java
- uberfire-api/src/test/java/org/uberfire/workbench/type/FileNameUtilTest.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectMigrationServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectMigrationServiceImplTest.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/server/config/ConfigGroup.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/server/config/ConfigType.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/server/config/ConfigurationFactory.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/server/config/ConfigurationService.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationFactoryImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ConfiguredRepositories.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ConfiguredRepositoriesImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/config/ConfigurationFactoryImplTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/config/ConfigurationServiceImplTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/ConfiguredRepositoriesTest.java
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/723
* https://github.com/kiegroup/appformer/pull/251
* https://github.com/kiegroup/kie-wb-common/pull/1520
> AF-1080: New project with the same name as another project in different space disappear after server restarts

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/DateRangePickerOptions.java
Issue: [AF-1110](https://issues.jboss.org/browse/AF-1110)
> AF-1110: expose "parentEl" option

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java
See https://issues.jboss.org/browse/DROOLS-2410
- https://github.com/kiegroup/appformer/pull/256
- https://github.com/kiegroup/kie-wb-common/pull/1530
> DROOLS-2410: [DMN Designer] Active entries not highlighted correctly when scrolling

- uberfire-server/src/main/java/org/uberfire/server/FileDownloadServlet.java
- uberfire-server/src/main/java/org/uberfire/server/FileUploadServlet.java
- uberfire-server/src/test/java/org/uberfire/server/FileDownloadServletTest.java
- uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
Cherry-picked from https://github.com/kiegroup/appformer/pull/117/commits/0ec7ab84fbc654a43c5963113161477749ff4404
> [7.5.x] AF-934 - Asset upload / download to not work inside projects which name contains spaces (#117)

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/CommonsEntryPoint.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.ui.xml
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/resources/org/uberfire/ext/widgets/common/UberfireWidgetsCommons.gwt.xml
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/PagedTableTest.java
> [7.7.x] JBPM-7003 - Update page size selector style to match PatternFly dropdown

- uberfire-api/src/main/java/org/uberfire/workbench/annotations/VisibleAsset.java
- uberfire-api/src/main/java/org/uberfire/workbench/type/TextResourceTypeDefinition.java
- uberfire-extensions/uberfire-wires/uberfire-wires-bpmn/uberfire-wires-bpmn-api/src/main/java/org/uberfire/ext/wires/bpmn/api/type/BpmnResourceTypeDefinition.java
Related to:
https://github.com/kiegroup/appformer/pull/269
https://github.com/kiegroup/kie-wb-common/pull/1550
https://github.com/kiegroup/drools-wb/pull/838
https://github.com/kiegroup/optaplanner-wb/pull/269
https://github.com/kiegroup/jbpm-designer/pull/760
> [AF-1087]: Added VisibleAssetQualifier to ResourceTypeDefinitions

- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenter.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenterTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/resources/i18n/CommonConstants.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/resources/org/uberfire/ext/editor/commons/client/resources/i18n/CommonConstants.properties
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorValidationTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/KieEditorTest.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/callbacks/CommandErrorCallback.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/callbacks/CommandErrorCallbackTest.java
(cherry picked from commit 87714f08a133ea127a238745644d45c71c459112)
https://issues.jboss.org/browse/AF-1079
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/731
https://github.com/kiegroup/appformer/pull/272
https://github.com/kiegroup/kie-wb-common/pull/1565
https://github.com/kiegroup/drools-wb/pull/841
> [7.7.x] AF-1079 : Empty 'Validation errors' popup in Decision/Business Central

- uberfire-api/src/main/java/org/uberfire/backend/vfs/PathFactory.java
- uberfire-client-api/src/main/java/org/uberfire/client/mvp/RenameInProgressEvent.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/common/SaveAndRenameCommandBuilder.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorRenameTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/common/SaveAndRenameCommandBuilderTest.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/LockManagerTest.java
Cherry picked from https://github.com/kiegroup/appformer/pull/275
---
- https://github.com/kiegroup/appformer/pull/284
- https://github.com/kiegroup/drools-wb/pull/844
> [7.7.x] RHBA-415: After rename, designer is not marked as dirty more

- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreen.java
- dashbuilder/dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreenTest.java
> AF-1119: "Are you sure you want to discard unsaved data?" Displayed

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/BaseIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/suite/ElasticSearchTestSuite.java
@mbiarnes @mareknovotny Would you mind to review?
> [AF-1145]: Container removed if exist before test

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/VFSServicesServerImpl.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/VFSServicesServerImplTest.java
Hey @ederign @hasys 
This is the cherry-pick for https://github.com/kiegroup/appformer/pull/283
Thanks!
> [7.7.x] RHPAM-777: Fix VFSService missing filter delegate

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumn.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/ColumnResizeEvent.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/RowResizeEvent.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/FullLayoutTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/container/ContainerTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java
@ederign @kkufova Can you review asap please? Trying to make the tomorrow cut.
> AF-1049: [Layout editor] Changing component width causes errors

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumn.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/ColumnResizeEvent.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/RowResizeEvent.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/FullLayoutTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/container/ContainerTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java
@ederign @kkufova Backport from master.
> [7.7.x] AF-1049: [Layout editor] Changing component width causes errors

- uberfire-api/src/main/java/org/uberfire/mvp/BiParameterizedCommand.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbs.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/widget/BreadcrumbsPresenter.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbsTest.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/mock/MockPlaceManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PerspectiveManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PerspectiveManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PluginPlaceManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/PerspectiveManagerTest.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
* https://github.com/kiegroup/appformer/pull/293
* https://github.com/kiegroup/kie-wb-common/pull/1628
* https://github.com/kiegroup/drools-wb/pull/850
* https://github.com/kiegroup/jbpm-designer/pull/768
> AF-1097: [Project Oriented] Endless asset loading appears when discarding unsaved data

- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/context/WorkspaceProjectContext.java
- uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/context/WorkspaceWorkspaceProjectContextTest.java
@ederign here is port for 7.7.x. Would you mind to review it and merge?
> [AF-1091]: Fixed error that appears after using the Contributors tab

- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/authz/AuthzPolicyMarshallerTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/PriorityDropDown.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditor.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/BaseRoleEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.ui.xml
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/authz/AuthorizationPolicy.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationEntry.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationPolicy.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DotNamedPermission.java
@kkufova @manstis Can you review please?
P.S: It also fixes a couple of look&feel issues:
1.- The lack of  pfly style of the warning message in the permissions editor.
2.- Removed the "Reset" option from both the priority and the permission item drop downs
> AF-1159: Permissions changes are not persistent

- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/authz/AuthzPolicyMarshallerTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/PriorityDropDown.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditor.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/BaseRoleEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/workflow/EntityWorkflowViewImpl.ui.xml
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/authz/AuthorizationPolicy.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationEntry.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationPolicy.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DotNamedPermission.java
Backport from master https://github.com/kiegroup/appformer/pull/300
@kkufova @manstis mind to review as well please?
> [7.7.x] AF-1159: Permissions changes are not persistent

- uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/engine/IndexerScheduler.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/provider/LuceneIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/ConstrainedIndexerScheduler.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/index/MetadataIndexEngine.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/common/IOServiceIndexedTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/common/MetadataIndexEngineBatchTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/common/util/TestFileSystemProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
* RHBA-593, AF-1106: Indexing is not started in recreated projects
* AF-1084+: Fix minor code-style issues.
> RHBA-593/AF-1106 fix + minor code-style fixes for AF-1084 (#281)

- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/ColumnFilterEditorView.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/ColumnFilterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DataSetFilterEditorView.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DataSetFilterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DateParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/LikeToFunctionEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/MultipleNumberParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/MultipleTextParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/NumberParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/TextParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/resources/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.properties
- Make filter take available width
- Change expand/collapse icon
- Change remove icon
> RHPAM-840 - Review filter editor styles

- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/ColumnFilterEditorView.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/ColumnFilterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DataSetFilterEditorView.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DataSetFilterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DateParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/LikeToFunctionEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/MultipleNumberParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/MultipleTextParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/NumberParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/TextParameterEditorView.ui.xml
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/resources/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.properties
- Make filter take available width
- Change expand/collapse icon
- Change remove icon
> [7.7.x] RHPAM-840 - Review filter editor styles

- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/main/java/org/dashbuilder/client/widgets/dataset/editor/csv/CSVDataSetDefAttributesEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/test/java/org/dashbuilder/client/widgets/dataset/editor/csv/CSVDataSetDefAttributesEditorTest.java
@kkufova @ederign Ready for review.
> AF-1169: [Data Sets] Uploading .csv file causes IllegalArgumentException

- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/main/java/org/dashbuilder/client/widgets/dataset/editor/csv/CSVDataSetDefAttributesEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/test/java/org/dashbuilder/client/widgets/dataset/editor/csv/CSVDataSetDefAttributesEditorTest.java
@kkufova @ederign Backport from https://github.com/kiegroup/appformer/pull/318
> [7.7.x] AF-1169: [Data Sets] Uploading .csv file causes IllegalArgumentException

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/SyncRemote.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/PathUtil.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectMigrationServiceImplTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/utils/PathUtilTest.java
Backport of fix reviewed on master.
> AF-1155: Error importing projects located in a folder inside the repo

- pom.xml
> DROOLS-2503 Switch Maven repository to repository.jboss.org.

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java
See https://issues.jboss.org/browse/JBPM-7167
Demo:
---
- https://github.com/kiegroup/appformer/pull/331
- https://github.com/kiegroup/kie-wb-common/pull/1727
> JBPM-7167: [Stunner] Does not support save and rename feature

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/AbstractLayoutEditorTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java
@kkufova @dgutierr could you please take a look?
> AF-1184: [Layout editor] Moving any component on canvas breaks Layout editor

- uberfire-testing-utils/src/main/java/org/uberfire/mocks/CallerProxy.java
- uberfire-testing-utils/src/test/java/org/uberfire/mocks/CallerMockTest.java
Port to master of this: https://github.com/kiegroup/appformer/pull/328
> [RHBA-685]: If invocation target exception is catched, target exception is extracted

- uberfire-testing-utils/src/main/java/org/uberfire/mocks/CallerProxy.java
- uberfire-testing-utils/src/test/java/org/uberfire/mocks/CallerMockTest.java
@mbarkley @cristianonicolai Would you mind to review? This is part of https://github.com/kiegroup/kie-wb-common/pull/1715
> [RHBA-685-7.7.x]: If invocation target exception is catched, target exception is extracted

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/RowView.java
Backport for https://github.com/kiegroup/appformer/pull/334
@ederign @kkufova  could you please take a look?
> [7.7.x] AF-1188: [Firefox] Business central disconnects on field drop.

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2S.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2D.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/IContext2D.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2DTest.java
JBPM-7145 cherry pick https://github.com/kiegroup/appformer/commit/b636f8341c4c4753a0dac9c67c3b4956035cd63d
@romartin
> [7.7.x] RHPAM-878 Stunner - SVG persisted on backend when saving a diagram

- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/DefaultPomEnhancer.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/POMServiceImpl.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/PomEnhancer.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/PomEnhancerProvider.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplCreateTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplLoadTest.java
This PR adds an extension mechanism to enhance POM file content. Usefull to make sure you have the correct dependencies, repositories and plugins.
This is used by kie to enforce a valid pom file
> AF 1140: Add extension mechanism to enhance POM content

- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/DefaultPomEnhancer.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/POMServiceImpl.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/PomEnhancer.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/PomEnhancerProvider.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplCreateTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplLoadTest.java
Add extension mechanism to enhance POM content
> AF 1140 7.7.x : Add extension mechanism to enhance POM content (#343)

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererNonSelectionLayerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererTest.java
See https://issues.jboss.org/browse/DROOLS-2539
> DROOLS-2539: [Guided Decision Table] Selected Cell highlight ignores hidden columns

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/WorkspaceProjectService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
* https://github.com/kiegroup/appformer/pull/357
* https://github.com/kiegroup/kie-wb-common/pull/1794
> AF-1089: [Project Oriented] It is possible to create two project with the same name when using Duplicate

- uberfire-m2repo-editor/uberfire-m2repo-editor-api/src/main/java/org/guvnor/m2repo/service/M2RepoService.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2RepoServiceImpl.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/ArtifactRepositoryService.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/JarPathTest.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2MavenRepositoryServiceImplTest.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2RepoServiceImplM2RepoURLTest.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/ModuleServiceCore.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/POMService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/POMServiceImpl.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractModuleServiceTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/ModuleServiceMock.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplCreateTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplNewWorkspaceWorkspaceProjectTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
(cherry picked from commit 0de598891ec6ec4f0026d3447bd7b8c665cfc6c1)
https://issues.jboss.org/browse/AF-1205
https://github.com/kiegroup/appformer/pull/366
https://github.com/kiegroup/kie-wb-common/pull/1817
> [7.7.x] AF-1205 : Use system property for default m2 repository

- pom.xml
aligned to a new errai branch 4.2.x and its SNAPSHOT
> upgraded errai version to next SNAPSHOT

- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/CloneRepositoryCmd.java
- uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/JobRequestHelperTest.java
(cherry picked from commit a800badcf5f3921e8b4fc94825a4f5828a08df66)
https://issues.jboss.org/browse/AF-1208
> [7.7.x] AF-1208 : Migrated project by pom migration tool can't be cloned into BC via REST clone

- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/CloneRepositoryCmd.java
- uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/JobRequestHelperTest.java
https://issues.jboss.org/browse/AF-1208
> AF-1208 : Migrated project by pom migration tool can't be cloned into BC via REST clone

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2S.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/jso/svg/C2SContext2D.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/exports/svg/IContext2D.java
Cherry pick commit bde876c54187eea6042d875f11a2201a64131d11 to 7.7.x
@romartin
> [7.7.x] RHPAM-1003 Stunner - Diagram SVG is not highlighted on the WB

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/WorkspaceProjectService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
Cherry-picked from https://github.com/kiegroup/appformer/pull/357
> [7.7.x] AF-1089: [Project Oriented] It is possible to create two project with the same name when using Duplicate

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/Build.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/Dependencies.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/GAV.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/Module.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/ModuleRepositories.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/POM.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/Plugin.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/WorkspaceProject.java
- uberfire-project/uberfire-project-api/src/test/java/org/guvnor/common/services/project/model/DependenciesTest.java
- uberfire-project/uberfire-project-api/src/test/java/org/guvnor/common/services/project/model/GAVTest.java
- uberfire-project/uberfire-project-api/src/test/java/org/guvnor/common/services/project/model/POMTest.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/MavenPluginUpdater.java
Just looked at ubefrife-project-api and found couple of lurking NPEs and ArrayIndexOutOfBoundsExceptions. Reproducers and fixes included + expanded a coverage a bit.
> AF-1230: Prevent couple of exceptions in uberfire-project-api

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/events/ModuleUpdatedEvent.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractModuleService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/POMServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractModuleServiceTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplCreateTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplLoadTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplSaveTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplSaveWithSubModulesTest.java
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/context/WorkspaceProjectContext.java
- uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/context/WorkspaceProjectContextTest.java
https://issues.jboss.org/browse/AF-1100
https://github.com/kiegroup/appformer/pull/379
https://github.com/kiegroup/kie-wb-common/pull/1846
> AF-1100 : [Project Oriented] After project is renamed, its breadcrumb and title are not updated

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/NumericIntegerTextBox.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/NumericIntegerTextBoxTest.java
This PR is a corollary of the selenium test migration into community, for more details see the:
https://issues.jboss.org/browse/AF-1229
> AF-1229: Cover NumericIntegerTextBox

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/GAV.java
- uberfire-project/uberfire-project-api/src/test/java/org/guvnor/common/services/project/model/GAVTest.java
My change from yesterday introduced a regression as commented [here](https://github.com/kiegroup/appformer/pull/388#discussion_r193716265). Fixing that. @yurloc please take a look. It was a mistake to merge that without 
Jenkins execute full downstream build
I won't make that mistake again :P
> Fix regression introduced by (#388)

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/metamodel/ElasticSearchMappingStore.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/metamodel/ElasticsearchMappingException.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/provider/MappingFieldFactory.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/metamodel/ElasticSearchMappingStoreTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/provider/MappingFieldFactoryTest.java
Mappings were not loaded ok, I changed some mapper, to have the correct mapping from elasticsearch.
@ederign @jhrcek would you mind to review it?
> [AF-1221]: Modified elastic search get mapping to avoid NPE

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Clone.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Fork.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/SubdirectoryClone.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitCloneTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderHookTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitForkTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitMirrorTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitSubdirectoryCloneTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitUtilTest.java
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
Fixes https://issues.jboss.org/browse/AF-1247
> [AF-1247] Add hooks when cloning/forking

- pom.xml
- uberfire-client-api/src/main/java/org/uberfire/client/promise/Promises.java
- uberfire-client-api/src/main/java/org/uberfire/client/util/Clipboard.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/elemental2/Elemental2Modal.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/callbacks/DefaultErrorCallback.java
Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/770
https://github.com/errai/errai/pull/350
https://github.com/kiegroup/appformer/pull/404
https://github.com/kiegroup/kie-wb-common/pull/1925
https://github.com/kiegroup/drools-wb/pull/878
https://github.com/kiegroup/jbpm-wb/pull/1162
https://github.com/kiegroup/optaplanner-wb/pull/288
https://github.com/kiegroup/kie-wb-distributions/pull/773
> AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/BootstrapTest.java
- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/org/dashbuilder/config/ConfigAnnotationTest.java
- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/org/dashbuilder/dataset/DataSetDefRegistryCDITest.java
- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/org/dashbuilder/dataset/DataSetProviderRegistryCDITest.java
- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/org/dashbuilder/dataset/DataSetSubsystemCDITest.java
- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/org/dashbuilder/dataset/SQLDataSourceLocatorCDITest.java
@hasys @kkufova backport from master.
> [7.7.x] RHPAM-832: Dashbuilder tests failing on windows

- uberfire-client-api/src/main/java/org/uberfire/client/promise/Promises.java
- uberfire-client-api/src/main/java/org/uberfire/client/util/Clipboard.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/elemental2/Elemental2Modal.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/callbacks/DefaultErrorCallback.java
This is already merged in 7.7.x. Cherry-picking to master.
Related:
https://github.com/errai/errai/pull/352
https://github.com/kiegroup/appformer/pull/412
https://github.com/kiegroup/kie-wb-common/pull/1951
https://github.com/kiegroup/drools-wb/pull/883
https://github.com/kiegroup/jbpm-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/290
https://github.com/kiegroup/kie-wb-distributions/pull/776
> [master] AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/DownloadMenuItem.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/MenuItems.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/resources/i18n/Constants.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/resources/org/uberfire/ext/editor/commons/client/resources/i18n/Constants.properties
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/DownloadMenuItemTest.java
- uberfire-server/src/main/java/org/uberfire/server/FileDownloadServlet.java
- uberfire-server/src/test/java/org/uberfire/server/FileDownloadServletTest.java
See:
- https://issues.jboss.org/browse/RHPAM-1248
- https://issues.jboss.org/browse/AF-1405
---
- https://github.com/kiegroup/appformer/pull/419
- https://github.com/kiegroup/kie-wb-common/pull/1976
- https://github.com/kiegroup/drools-wb/pull/889
> AF-1405: Can No Longer Download Text Files From Business Central

- uberfire-rest/uberfire-rest-backend/pom.xml
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
- uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/ProjectResourceJobTest.java
https://issues.jboss.org/browse/AF-1412
Bundle:
https://github.com/kiegroup/appformer/pull/422
https://github.com/kiegroup/kie-wb-distributions/pull/782
> AF-1412 : Kie WB REST getJob randomly return 410 Gone after previous REST call

- uberfire-rest/uberfire-rest-backend/pom.xml
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
- uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/ProjectResourceJobTest.java
(cherry picked from commit 58e73ea749ee9acbfd3cf165fdc81f4aaa53f861)
> [7.7.x] AF-1412 : Kie WB REST getJob randomly return 410 Gone after previous REST call

- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
- uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/JobRequestHelperTest.java
- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/test/TestRunnerService.java
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/test/TestRunnerServiceImpl.java
- uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/test/TestRunnerServiceImplTest.java
https://issues.jboss.org/browse/DROOLS-2785
Bundle:
https://github.com/kiegroup/appformer/pull/430
https://github.com/kiegroup/drools-wb/pull/906
> DROOLS-2785 : Create run scenario test pipeline

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/categories/Optimization.java
Related PRs:
kiegroup/appformer/pull/438
kiegroup/kie-wb-common/pull/2048
kiegroup/drools-wb/pull/914
kiegroup/optaplanner-wb/pull/296
> PLANNER-1159: Add Optimization category

- uberfire-docs/docs/gettingStarted/5minIntroduction.md
From 1.0.0-SNAPSHOT to 2.8.0-SNAPSHOT
> Update Uberfire version

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/GridColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java
See https://issues.jboss.org/browse/DROOLS-2913
> DROOLS-2913: [DMN Designer] Data-types: Grid: FunctionDefinition

- uberfire-io/src/test/java/org/uberfire/io/impl/BatchTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystem.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImpl.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemLock.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderConfiguration.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProxy.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsCache.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsCacheDataStructure.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManager.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitCacheInvalidationTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderBytemanTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemLockTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsCacheTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManagerTest.java
Enhancement of our FS cache, in general, the issue is that the lock was not shared between the lazy instances.
> [AF-1267] JGit Filesystem cache improvements

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedTest.java
AF-1421: Allow the removal of a branch
AF-1276: Persist current branch per project of each user
* https://github.com/kiegroup/appformer/pull/442
* https://github.com/kiegroup/kie-wb-common/pull/2074
> Multiple branches support - new features

- uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/extensions/FileSystemHooks.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystem.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImpl.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProxy.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManager.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/extensions/JGitFSHooks.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderSSHTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsCacheTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManagerTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/util/extensions/JGitFSHooksTest.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryExternalUpdate.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryExternalUpdateEvent.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryUpdatedEvent.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ConfiguredRepositories.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ConfiguredRepositoriesImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelper.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/ConfiguredRepositoriesTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperNoIndexTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperTest.java
* https://github.com/kiegroup/appformer/pull/455
* https://github.com/kiegroup/kie-wb-common/pull/2108
> [7.11.x] AF-1502: Update project branches on runtime even when they are modified out of the workbench

- uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/extensions/FileSystemHooks.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystem.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImpl.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProxy.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManager.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/extensions/JGitFSHooks.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderSSHTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsCacheTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/manager/JGitFileSystemsManagerTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/util/extensions/JGitFSHooksTest.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryExternalUpdateEvent.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryUpdatedEvent.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ConfiguredRepositories.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ConfiguredRepositoriesImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelper.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/ConfiguredRepositoriesTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperNoIndexTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperTest.java
Cherry-picked from https://github.com/kiegroup/appformer/pull/455
* https://github.com/kiegroup/appformer/pull/460
* https://github.com/kiegroup/kie-wb-common/pull/2124
> AF-1502: Update project branches on runtime even when they are modified out of the workbench

- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/test/TestRunnerService.java
- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/test/TestService.java
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/test/TestRunnerServiceImpl.java
- uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/test/TestRunnerServiceImplTest.java
https://issues.jboss.org/browse/DROOLS-2940
Bundle:
https://github.com/kiegroup/appformer/pull/463
https://github.com/kiegroup/drools-wb/pull/935
> DROOLS-2940 : It is not possible to run all scenarios in the old test scenarios.

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/FixNotMavenizedArtifactInfo.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2ServletContextListener.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/FixNotMavenizedArtifactInfoTest.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2ServletContextListenerTest.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/resources/not-mavenized-artifacts.properties
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ModuleRepositoryResolverImpl.java
FIxing some issues on offline behavior, the PRs that compose the changes are:
https://github.com/kiegroup/kie-soup/pull/64
https://github.com/kiegroup/appformer/pull/465
https://github.com/kiegroup/kie-wb-common/pull/2131
https://github.com/kiegroup/kie-wb-distributions/pull/816
Docs Updated:
https://github.com/kiegroup/kie-docs/pull/1072
> AF-1528: improvements and consitency on web tooling behavior if offline

- pom.xml
> RHDM-588 Add support for PME dependency overwriting for freemarker.

- pom.xml
> RHDM-373 jackson-databind version update from 2.8.9 to 2.8.11.

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2ServletContextListener.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2ServletContextListenerTest.java
This PR turns off M2ServletContextListener if tooling is not running in offline mode, so avoiding touching local maven repo.
This aims to bring more stability for kie web developers, avoiding potential override of their local maven repo.
> AF-1528: Turn off M2ServletContextListener by default and some logging improvements

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2ServletContextListener.java
(not good, but we'll be… fixed on maven integratio)
right now just leave as is to fix the build
> AF-1528: kie-wb-common/**/BuilderTest uses it 

- pom.xml
> RHDM-373 jackson-databind version downgrade from 2.8.11 to 2.8.10.

- pom.xml
> RHDM-373 jackson-databind version downgrade from 2.8.11 to 2.8.10 - 7.11.x

- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java
A try to improve REST tests reliability
> AF-1587: a quick try to make the rest tests not lagging on volume, using an ummanaged service executor

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/resources/org/uberfire/ext/wires/core/grids/WiresCoreGrids.gwt.xml
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java
See https://issues.jboss.org/browse/DROOLS-2922
> DROOLS-2922: CSS: Pop-over menu for DMN decision tables

- uberfire-extensions/uberfire-social-activities/uberfire-social-activities-backend/src/main/java/org/ext/uberfire/social/activities/persistence/SocialClusterMessaging.java
- uberfire-extensions/uberfire-social-activities/uberfire-social-activities-backend/src/test/java/org/ext/uberfire/social/activities/persistence/SocialClusterMessagingTest.java
This PR fix possible null dereference revealed by the **infer** tool
@ederign @jhrcek would you mind to have a look?
> BAQE-678: Prevent possible NULL dereference

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/KIEColours.java
See https://issues.jboss.org/browse/DROOLS-3151
> DROOLS-3151: [DMN Designer] Decision Table: Improve contrast of Input- and OutputClause columns

- uberfire-experimental/uberfire-experimental-client/src/main/java/org/uberfire/experimental/client/service/impl/ClientExperimentalFeaturesRegistryServiceImpl.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/service/impl/ClientExperimentalFeaturesRegistryServiceImplTest.java
@jhrcek @ederign could you please review?
> AF-1665: all drag & drop components missing in pages perspective

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/GridCellValue.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridCellValue.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridColumn.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/IntegerColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/StringColumnRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/GridRendererTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/KIEColours.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/KIEStyles.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseColumnRendererTest.java
@manstis @Rikkola 
Scope of the present PR is to move inside appformer the "placeholder" logic for body grid cell
> [DROOLS-3074] Implement placeholder on body cells

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/spaces/SpacesAPIImpl.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/spaces/SpacesAPIImplTest.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/PathUtil.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/utils/PathUtilTest.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitPathUtil.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitPathUtilTest.java
* https://github.com/kiegroup/appformer/pull/511
* https://github.com/kiegroup/kie-wb-common/pull/2228
>  AF-1669: Support slashes in branch names

- uberfire-extensions/uberfire-preferences-ui-client/src/main/java/org/uberfire/ext/preferences/client/central/tree/TreeHierarchyInternalItemPresenter.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/panels/support/PartManager.java
@porcelli  and @paulovmr (your code involved) please check
> Fix 3 cases of equals() between objects of inconvertible types

- uberfire-experimental/uberfire-experimental-client/src/main/java/org/uberfire/experimental/client/workbench/type/ExperimentalAwareClientTypeRegistryImpl.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/ExperimentalAwareClientTypeRegistryImplTest.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/api/DiagramResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/api/FormResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/api/JavaResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/api/SpreadSheetResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/api/TextFileResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/api/WrongClientResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/client/ClientDiagramResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/client/ClientFormResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/client/ClientJavaResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/client/ClientSpreadSheetResourceType.java
- uberfire-experimental/uberfire-experimental-client/src/test/java/org/uberfire/experimental/client/workbench/type/test/client/ClientTextFileResourceType.java
- Fixed issue when ClientResourceTypes are annotated as experimental.
@ederign @tomasdavidorg  could you please take a look?
https://github.com/kiegroup/appformer/pull/527
https://github.com/kiegroup/kie-wb-common/pull/2272
> AF-1704: Case Management & Experimental integration

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/LayoutDragComponentHelper.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/infra/LayoutDragComponentHelperTest.java
7.14 version of https://github.com/kiegroup/appformer/pull/535
> [AF-1721] Adding "Target Div" component to a page causes Unexpected error to appear (#535)

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/RemoveRemote.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectMigrationServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectMigrationServiceImplTest.java
With @pefernan found that after clone (in migration process), origin was not removed, so was impossible to import into workbench because origin don't exist.
* https://github.com/kiegroup/appformer/pull/545
* https://github.com/kiegroup/kie-wb-common/pull/2305
@pefernan @ederign would you mind to review?
> [AF-1715-migration-import]: Migrated project cannot be imported to the workbench

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
Backport of https://github.com/kiegroup/appformer/pull/546
@nmirasch @cristianonicolai @ederign could any of you take a look?
> [7.14.x] JBPM-7990: Missing filters after redirection between Manage screens

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/RemoveRemote.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectMigrationServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectMigrationServiceImplTest.java
With @pefernan found that after clone (in migration process), origin was not removed, so was impossible to import into workbench because origin don't exist.
@ederign would you mind to review?
Child: https://github.com/kiegroup/kie-wb-common/pull/2312
> [AF-1715-7.14.x] Migrated project cannot be imported to the workbench

- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
Adding missing test for https://github.com/kiegroup/appformer/pull/546
@ederign @jsoltes would you mind take a look?
> JBPM-7990: Missing filters after redirection between Manage screens

- uberfire-api/src/main/java/org/uberfire/backend/vfs/impl/ObservablePathImpl.java
- uberfire-api/src/test/java/org/uberfire/backend/vfs/impl/ObservablePathImplTest.java
Moving selenium tests specifically GitDelete/GitRename. This is QE initiative to reduce selenium test suite
> Add ObservablePathImpl tests

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridCellValue.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridColumn.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelper.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/GridRendererTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/KIEStyles.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTestUtils.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseColumnRendererTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererTest.java
See https://issues.jboss.org/browse/DROOLS-3381
This PR adds support for columns with zero headers.
> DROOLS-3381: [DMN Designer] Do not add Header to nested ContextGrid

- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/workbench/widgets/popups/activities/notfound/ActivityNotFoundPresenter.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/workbench/widgets/popups/activities/notfound/ActivityNotFoundView.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/workbench/widgets/popups/activities/notfound/ActivityNotFoundView.ui.xml
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/resources/org/uberfire/ext/widgets/core/client/resources/i18n/CoreConstants.properties
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/workbench/widgets/popups/activities/notfound/ActivityNotFoundPresenterTest.java
This PR
- removes duplicit OK button from ActivityNotFoundView
- update message to be more self-explanatory
@manstis @sterobin @kkufova would you mind to review updated message?
> RHDM-797: Update ActivityNotFound view

- uberfire-ssh/uberfire-ssh-backend/src/test/java/org/uberfire/ssh/service/backend/auth/impl/SSHKeyAuthenticatorImplTest.java
- uberfire-ssh/uberfire-ssh-backend/src/test/java/org/uberfire/ssh/service/backend/editor/SSHKeyEditorServiceImplTest.java
- uberfire-ssh/uberfire-ssh-backend/src/test/java/org/uberfire/ssh/service/backend/keystore/impl/storage/DefaultSSHKeyStoreTest.java
- uberfire-ssh/uberfire-ssh-backend/src/test/java/org/uberfire/ssh/service/backend/test/SSHKeyStoreTestUtils.java
- uberfire-ssh/uberfire-ssh-backend/src/test/resources/.security/pkeys/john/.john-key.pub.meta
- uberfire-ssh/uberfire-ssh-backend/src/test/resources/.security/pkeys/katy/.katy-key-one.pub.meta
- uberfire-ssh/uberfire-ssh-backend/src/test/resources/.security/pkeys/katy/.katy-key-two.pub.meta
- uberfire-ssh/uberfire-ssh-backend/src/test/resources/custom_security/pkeys/john/.john-key.pub.meta
- uberfire-ssh/uberfire-ssh-backend/src/test/resources/custom_security/pkeys/katy/.katy-key-one.pub.meta
- uberfire-ssh/uberfire-ssh-backend/src/test/resources/custom_security/pkeys/katy/.katy-key-two.pub.meta
Pere, this is some leftovers from ssh. After running the tests I got:
The changes are related with ssh key last usage timestamp.
> Project Cleanup. This test files are changed by ssh tests

- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/RendererManager.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DisplayerTypeSelector.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/widgets/DisplayerTypeSelectorTest.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/PerspectiveEditorReportingGroupProvider.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/test/java/org/dashbuilder/client/editor/PerspectiveEditorReportingGroupProviderTest.java
Not only from the pallet, had also to remove from the displayer editor popup.
> AF-1742: Hide non supported components from Pallet when creating a page

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/GridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/RangeSelectionStrategy.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/RowSelectionStrategy.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/RangeSelectionStrategyUnmergedDataTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/RowSelectionStrategyUnmergedDataTest.java
See https://issues.jboss.org/browse/DROOLS-3207
Part of an ensemble:-
- https://github.com/kiegroup/appformer/pull/572
- https://github.com/kiegroup/kie-wb-common/pull/2346
> DROOLS-3207: [DMN Designer] Cell/header selection improvements

- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/events/AfterDeleteOrganizationalUnitEvent.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/organizationalunit/RemoveOrganizationalUnitEvent.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
Added Clustered events.
* https://github.com/kiegroup/appformer/pull/575
* https://github.com/kiegroup/kie-wb-common/pull/2348
> [AF-1750]: Added Clusted event to sync spaces

- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
* https://github.com/kiegroup/appformer/pull/588
* https://github.com/kiegroup/kie-wb-common/pull/2365
* https://github.com/kiegroup/jbpm-wb/pull/1266
> AF-1639: Permission to read/write spaces and projects now should be based in their collaborators

- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3DisplayerView.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3Renderer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3XYDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/area/C3AreaChartDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/area/C3AreaChartView.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/bar/C3BarChartDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/jsbinding/C3ChartConf.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/test/java/org/dashbuilder/renderer/c3/client/C3BaseTest.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/test/java/org/dashbuilder/renderer/c3/client/C3RendererTest.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/test/java/org/dashbuilder/renderer/c3/client/charts/area/C3AreaChartDisplayerTest.java
(adding also stacked area chart support)
> AF-1739: C3 Area Chart is not displayed

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderConfiguration.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Clone.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/CreateRepository.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Fork.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/SubdirectoryClone.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitCloneTest.java
A version of https://github.com/kiegroup/appformer/pull/555 with tests added.
@ghjboss could you please also take a look?
Docs: https://github.com/kiegroup/kie-docs/pull/1261
> [AF-1733] Turn off the ssl verification when cloning a git project

- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryExternalUpdateEvent.java
* https://github.com/kiegroup/appformer/pull/598
* https://github.com/kiegroup/kie-wb-common/pull/2386
> AF-1753: Project branches created on one cluster node are not visible on other nodes

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/GuvnorM2Repository.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
Complete set of PRs 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/907
https://github.com/kiegroup/appformer/pull/591
https://github.com/kiegroup/kie-wb-common/pull/2374
https://github.com/kiegroup/jbpm-work-items/pull/88
https://github.com/kiegroup/jbpm-wb/pull/1268
https://github.com/kiegroup/kie-wb-distributions/pull/860
> JBPM-8000 - Work item repository administration in business central

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java
It seems that this cache (_Cache persistent_file_store already exists_) was already created and It tried to create it again.
Instead of using createCache first and then getCache, we are now using getOrCreateCache method. So if that cache already exist it will be returned instead of trying to create it again. 
@jhrcek would you mind to review?
> [AF-1795]: If the cache exist is returned if not, it is created

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/helpers/HttpPostHelper.java
just a refactor to allow it to be extended for another upload file scenario
> JBPM-8008 - Add single service task into the repository

- dashbuilder/dashbuilder-distros/pom.xml
- dashbuilder/dashbuilder-distros/src/main/assembly/assembly-tomcat-8.xml
- pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-parent-with-dependencies/pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml
- uberfire-bom/pom.xml
- uberfire-showcase/showcase-distribution-wars/pom.xml
- uberfire-showcase/showcase-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml
- uberfire-structure/uberfire-structure-backend/src/main/resources/DependencyTypesMapper.json
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/pom/PomEditorDefaultTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/pom/PomStructureEditorTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/pom/TestUtil.java
- uberfire-structure/uberfire-structure-backend/src/test/resources/DependencyTypesMapper.json
- uberfire-structure/uberfire-structure-backend/src/test/resources/dummy/pom.xml
- uberfire-structure/uberfire-structure-backend/src/test/resources/dummyOverride/pom.xml
for hibernate upgrade & jboss-ip-bom upgrade
> Jboss ip bom 8.4.0.final

- dashbuilder/dashbuilder-distros/src/main/assembly/assembly-tomcat-8.xml
- dashbuilder/dashbuilder-webapp/pom.xml
- uberfire-rest/uberfire-rest-backend/pom.xml
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/900 (Please comment on this PR if you have any questions)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/352
* https://github.com/kiegroup/drools/pull/2191
* https://github.com/kiegroup/jbpm/pull/1394
* https://github.com/kiegroup/optaplanner/pull/469
* https://github.com/kiegroup/droolsjbpm-integration/pull/1667
* https://github.com/kiegroup/appformer/pull/574
* https://github.com/kiegroup/optaplanner-wb/pull/319
* https://github.com/kiegroup/jbpm-wb/pull/1257
* https://github.com/kiegroup/kie-wb-distributions/pull/858
* https://github.com/kiegroup/optaweb-employee-rostering/pull/215
> Align JAXB and JAXWS APIs with Wildfly

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/D3.java
added the access to some controls of D3.js
> JBPM-8108:Improve zoom action on process diagram

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java
In ISPN server might exists other caches that are not created by AppFormer Backend, so now, those caches contains a prefix to identify what caches are from AppFormer and those who are not. This way search and cache creation will only be on platform created caches. Nothing changed on Indexing API.
> [AF-1795]: Improved cache naming

- uberfire-client-api/src/main/java/org/uberfire/client/promise/Promises.java
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/repositories/ConflictingRepositoriesPopup.java
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/repositories/ConflictingRepositoriesPopupView.java
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/repositories/ConflictingRepositoriesPopupViewImpl.java
- uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/repositories/ConflictingRepositoriesPopupTest.java
AF-1686: Authoring 'dev mode'
AF-1778: Adding 'mvn clean install' functionality into the 'Build' button
Adding extra callback of the ok action in the popup.
@ederign @tomasdavidorg could you please take a look?
https://github.com/kiegroup/appformer/pull/614
https://github.com/kiegroup/jbpm/pull/1424
https://github.com/kiegroup/droolsjbpm-integration/pull/1698
https://github.com/kiegroup/kie-wb-common/pull/2422
> AF-1685: Development Lifecycle Streamline

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/index/directory/DirectoryFactory.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/test/java/org/uberfire/ext/metadata/backend/lucene/index/directory/DirectoryFactoryTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IndexerDispatcher.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/index/MetadataIndexEngine.java
The problem occur because branch name was not being concatenated to index name during initial set up. Also log message was improved because not real indexing happens at that point
@ederign @porcelli would you mind to review?
> [AF-1797]: Added branch to index name

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/proto/KObjectMarshaller.java
Change the order protobuf fields are read.
@jhrcek @ederign would you mind to review?
> [AF-1603]: Decrease amount of ISPN Warn messages

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/util/gzip/GzipFilter.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/util/gzip/GzipHttpServletResponseWrapper.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/util/gzip/GzipResponseServletOutputStream.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/util/gzip/GzipFilterTest.java
Adds a filter that can compress a servlet response as Gzip. Please see a detailed explanation on the related kiegroup/kie-wb-distributions PR.
Related PRs:
https://github.com/kiegroup/appformer/pull/631
https://github.com/kiegroup/kie-wb-distributions/pull/877
https://github.com/kiegroup/kie-docs/pull/1395
> AF-1817: Gzip filter

- uberfire-extensions/uberfire-widgets/uberfire-widgets-table/src/main/java/org/uberfire/ext/widgets/table/client/UberfireColumnPicker.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-table/src/test/java/org/uberfire/ext/widgets/table/client/UberfireColumnPickerTest.java
Cherry pick https://github.com/kiegroup/appformer/pull/639 into 7.18.x
> [7.18.x] Fix ConcurrentModificationException in TaskListViewImplTest test

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/pom.xml
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/ws/JGitFileSystemsEventsManager.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderBytemanTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitForkTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitMirrorTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/ws/JGitFileSystemsEventsManagerTest.java
Includes tests in ` uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit` to be run by surefire
@ederign @adrielparedes @porcelli please check
> [AF-1862] Include missing tests in maven build

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/pom.xml
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/ws/JGitFileSystemsEventsManager.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderBytemanTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitForkTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitMirrorTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/ws/JGitFileSystemsEventsManagerTest.java
Cherry-pick of #637 
* Include missing tests in maven build
* Remove include completely to use default surefire regex for test
* [fix-jgit-tests]: Fixed tests
> [7.18.x] [AF-1862] Include missing tests in maven build (#637)

- uberfire-workbench/uberfire-workbench-client-backend/src/main/java/org/uberfire/client/WorkbenchBackendEntryPoint.java
- uberfire-workbench/uberfire-workbench-client-backend/src/test/java/org/uberfire/client/WorkbenchBackendEntryPointTest.java
When connection is reestablished, the retries counter is reset. In tests you can see the behavior
@porcelli Would you mind to review?
> [AF-1842]: Added 5 retries before showing disconnection error

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderBytemanTest.java
@domhanak @ederign @mareknovotny
> fix the build failing test

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/elemental2/Elemental2Modal.java
Cherry pick https://github.com/kiegroup/appformer/pull/647
> [7.18.x] JBPM-8267 - Expose modal object for event handling

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/megamenu/WorkbenchMegaMenuView.less
See Also: https://github.com/kiegroup/kie-wb-distributions/pull/886
> RHPAM-1948: Fixing brand logo for IE

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/megamenu/WorkbenchMegaMenuView.less
Cherry pick of https://github.com/kiegroup/appformer/pull/657
Merge together with: https://github.com/kiegroup/kie-wb-distributions/pull/887
> RHPAM-1948: Fixing brand logo for IE (#657)

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilities.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/CoordinateUtilities.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/GridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetKeyboardHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationInvokeContextMenuForSelectedCell.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelper.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilitiesTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetLinkedColumnMouseEventHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/DefaultGridWidgetPinnedModeMouseEventHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationInvokeContextMenuForSelectedCellTest.java
- kiegroup/kie-wb-common#2408
- https://github.com/kiegroup/drools-wb/pull/1042
> DROOLS-3175: Add invoke context menu keyboard operation

- dashbuilder/dashbuilder-distros/pom.xml
- dashbuilder/dashbuilder-distros/src/main/assembly/assembly-tomcat-8.xml
- dashbuilder/dashbuilder-webapp/pom.xml
- pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-parent-with-dependencies/pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/pom.xml
- uberfire-bom/pom.xml
- uberfire-rest/uberfire-rest-backend/pom.xml
- uberfire-showcase/showcase-distribution-wars/pom.xml
- uberfire-showcase/showcase-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml
updated to org.dom4j
upgraded to jboss-jaxrs-api_2.1_spec
> BAPL-1148: upgraded jboss-ip-bom

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/MomentDuration.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/MomentDurationObject.java
See:
- https://issues.jboss.org/browse/DROOLS-3754
- https://issues.jboss.org/browse/DROOLS-3760
---
---
- https://github.com/kiegroup/appformer/pull/668
- https://github.com/kiegroup/kie-wb-common/pull/2548
> DROOLS-3754: [DMN Designer] Data Types - Constraints (Range/Enumeration) - Add 'Day/Time Duration' component when the type is 'Day/Time Duration'

- pom.xml
- uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/analyzer/ElasticSearchAnalyzer.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/search/InfinispanSearchIndex.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/pom.xml
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOSearchServiceImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/analyzer/KiePerFieldAnalyzerWrapper.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BatchIndexConcurrencyTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BatchIndexSingleThreadTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/ComplexFieldsTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/FullTextSearchIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/IOServiceIndexedDeleteFileTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/IOServiceIndexedDotFileGitImplTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/IOServiceIndexedDotFileGitInternalImplTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/IOServiceIndexedGitImplTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/IOServiceIndexedSortingTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/IndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/ReplaceIndexedObjectTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/suite/InfinispanTestProperties.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/suite/InfinispanTestSuite.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/resources/ispn.properties
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/resources/log4j.properties
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/resources/logback-test.xml
Upgrading ISPN to last version because it contains some new analyzers we need. Also changed **simple** for **filename** analyzer.
@ederign @porcelli @tomasdavidorg 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/938
* https://github.com/kiegroup/appformer/pull/663
* https://github.com/kiegroup/kie-wb-common/pull/2531
> [AF-1904]: Changed simple for filename analyzer

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/widget/DefaultBreadcrumbsView.css
Added string cut for breadcrumb Links to avoid breaking html layout due long names
> AF-1875-Add string cut for breadcrumb Links and toolbar title

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/selectpicker/JQuery.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/selectpicker/JQueryElementOffset.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/Moment.java
This PR is required for:
https://github.com/kiegroup/kie-wb-common/pull/2553
> DROOLS-3665: [DMN Designer] Data Types - Constraints (Range/Enumeration) - Add "Time" component when the type is "Time"

- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/test/TestRunnerService.java
- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/test/TestService.java
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/test/TestResultMessageAggregator.java
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/test/TestRunnerServiceImpl.java
- uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/test/TestResultMessageAggregatorTest.java
- uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/test/TestRunnerServiceImplTest.java
https://issues.jboss.org/browse/DROOLS-3103
@kkufova @danielezonca @gitgabrio If you could please take a look.
Bundle:
https://github.com/kiegroup/appformer/pull/667
https://github.com/kiegroup/kie-wb-common/pull/2568
https://github.com/kiegroup/drools-wb/pull/1115
> DROOLS-3103 : Support run test at project level

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilities.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/CellContextUtilitiesTest.java
See https://issues.jboss.org/browse/DROOLS-3896
This came about from the [review](https://github.com/kiegroup/kie-wb-common/pull/2592#pullrequestreview-229490024) of the original fix.
> DROOLS-3896: [DMN Designer] Editing a merged header cell positions editor at the wrong location

- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3AbstractDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/bar/C3BarChartDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/meter/C3MeterChartDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/jsbinding/C3AxisY.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/jsbinding/C3ChartConf.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/jsbinding/C3Format.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/jsbinding/C3JsTypesFactory.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/jsbinding/C3Tooltip.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/test/java/org/dashbuilder/renderer/c3/client/charts/meter/C3MeterDisplayerTest.java
Small changes so Meter and Bar chart will look better during Displayer preview
> AF-1911: Implement better default values for Meter and Bar Chart

- uberfire-extensions/uberfire-widgets/uberfire-widgets-service/uberfire-widgets-service-api/src/main/java/org/uberfire/ext/services/shared/preferences/MultiGridPreferencesStore.java
Added defaultGridId to MultiGridPreferencesStore to store the default active filter
> JBPM-8346: Allow users to select a default filter

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/DOMElementFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/multiple/impl/BaseDOMElementFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/multiple/impl/CheckBoxDOMElementFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/multiple/impl/TextBoxDOMElementFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/BaseSingletonDOMElementFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/ListBoxSingletonDOMElementFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/TextBoxSingletonDOMElementFactory.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommon.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/BaseSingletonDOMElementFactoryTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/ListBoxSingletonDOMElementFactoryTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/TextBoxSingletonDOMElementFactoryTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommonTest.java
- kiegroup/drools-wb#1120
- kiegroup/kie-wb-common#2590
> DROOLS-3438: Unify Cell Dom Element factories

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommon.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/BaseKeyDownHandlerCommonTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommonEnterKeyTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommonEscapeKeyTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/keyboard/KeyDownHandlerCommonTabKeyTest.java
See https://issues.jboss.org/browse/DROOLS-3895
- https://github.com/kiegroup/appformer/pull/684
- https://github.com/kiegroup/kie-wb-common/pull/2615
> DROOLS-3895: [DMN Designer] TextAreas can no longer be multi-line

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/utils/NewWorkspaceProjectUtils.java
- uberfire-project/uberfire-project-api/src/main/resources/org/guvnor/common/services/project/GuvnorProjectAPI.gwt.xml
- uberfire-project/uberfire-project-api/src/test/java/org/guvnor/common/services/project/utils/NewWorkspaceProjectUtilsTest.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplNewWorkspaceWorkspaceProjectTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
* https://github.com/kiegroup/appformer/pull/692
* https://github.com/kiegroup/kie-wb-common/pull/2619
> AF-1930: Either enable spaces in project names or disallow import of projects with spaces in the project name

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/security/ProjectPermissionsService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/security/ProjectPermissionsServiceImpl.java
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/security/ProjectController.java
- uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/security/ProjectControllerTest.java
* https://github.com/kiegroup/appformer/pull/697
* https://github.com/kiegroup/kie-wb-common/pull/2637
> AF-1963: [Branch Management] Only list branches the user has write access to

- appformer-js/jest.config.js
- appformer-js/package.json
@tiagobento @ederign please take a look and merge if ok
> AF-1900: Make jest-junit report more jenkins friendly

- appformer-js/package.json
Adding filename to distinguish between duplicate name in different files
@tiagobento @ederign
> AF-1900: Some test cases are not unique

- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-google/README.md
Part of an ensemble: 
https://github.com/kiegroup/kie-docs/pull/1538
> AF-1680: Adding instructions to build and use gcharts

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchCustomStandalonePerspectiveDefinition.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/WorkbenchStandaloneModeTest.java
* https://github.com/kiegroup/appformer/pull/710
* https://github.com/kiegroup/kie-wb-distributions/pull/931
Fixes the JIRAs:
* https://issues.jboss.org/browse/DROOLS-4016
* https://issues.jboss.org/browse/DROOLS-4015
* https://issues.jboss.org/browse/RHPAM-2116
> DROOLS-4016: [Guided Rules Editor] Missing toolbar buttons in standalone mode

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorImpl.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdowns.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdowns.ui.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/static/uberfire-patternfly.css
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdownsTest.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/multipage/MultiPageEditor.java
Assembly:
https://github.com/kiegroup/appformer/pull/709
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/958
https://github.com/kiegroup/kie-wb-common/pull/2650
https://github.com/kiegroup/kie-wb-distributions/pull/927
> JBPM-8168: Support adding custom widgets on the tab bar

- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/NewBranchEvent.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryCopierImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryCopierImplTest.java
- uberfire-structure/uberfire-structure-client/src/test/java/org/guvnor/structure/client/editors/repository/list/RepositoriesPresenterTest.java
* https://github.com/kiegroup/appformer/pull/712
* https://github.com/kiegroup/kie-wb-common/pull/2678
> JBPM-8532 - add original branch name to NewBranchEvent

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/main/java/org/uberfire/ext/layout/editor/api/editor/LayoutColumn.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/main/java/org/uberfire/ext/layout/editor/api/editor/LayoutComponent.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/main/java/org/uberfire/ext/layout/editor/api/editor/LayoutRow.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/main/java/org/uberfire/ext/layout/editor/api/editor/LayoutTemplate.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/test/org/uberfire/ext/layout/editor/api/editor/LayoutTemplateTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumn.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java
https://github.com/kiegroup/kie-wb-common/pull/2709
This PR goal is allow access to a component column layout drag component.
> JBPM-8523: access to the component column layout drag component

- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/organizationalunit/config/SpaceConfigStorageBatch.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/FileSystemDeleteWorker.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigStorageRegistryImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigStorageRegistryImplTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryServiceImplTest.java
Looks like some operations, like adding a repo were not added into a batch, so when multiple repos were added at same time SpaceInfo was being overwritten instead of updated.
@adrielparedes @tomasdavidorg could you please take a look?
> AF-2066: Project is not visible after more projects are created at the same time

- pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyBootstrapper.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyClientBundle.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/InputAutocomplete.html
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/InputAutocomplete.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/InputAutocompleteOptions.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/JQueryElementalProducer.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/PatternFly.gwt.xml
Used to solve:
AF-2057: Verify graceful degradation for users list on authoring
* https://github.com/kiegroup/appformer/pull/727
* https://github.com/kiegroup/kie-wb-common/pull/2736
> Added jquery-ui and autocomplete input widget wrapper

- dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/dataset/service/DataSetExportServicesImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitPathImpl.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/GetRef.java
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/file/FileDiscoveryServiceImpl.java
- uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/AbstractErrorAbsorbingProcessor.java
Fixes couple of blockers from - https://sonarcloud.io/project/issues?id=org.uberfire%3Auberfire-parent&open=AWQnNkiDbXXTsx7OMm_N&resolved=false&severities=BLOCKER&types=BUG
to start increasing our mark from E to something green.
@triceo @ederign @tomasdavidorg @barboras7 
Please take a look.
> Sonar blocker fixes round 1

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/DownloadMenuItemBuilder.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/BaseEditorTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/DownloadMenuItemBuilderTest.java
https://issues.jboss.org/browse/DROOLS-4357
https://github.com/kiegroup/appformer/pull/745
https://github.com/kiegroup/kie-wb-common/pull/2777
https://github.com/kiegroup/drools-wb/pull/1196
> DROOLS-4357 : Two download buttons are in Guided Decision Tables

- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryServiceImplTest.java
Original commit: https://github.com/kiegroup/appformer/pull/723
Changed branch name 
@ederign
> [AF-2063]: Notification is thrown once the project is created in FS.

- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplNewWorkspaceWorkspaceProjectTest.java
@adrielparedes @tomasdavidorg could you please take a look?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/748
https://github.com/kiegroup/kie-wb-common/pull/2779
> AF-2087: Error is displayed when creating project at the same time

- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/main/java/org/dashbuilder/dataset/DataSetDefRegistryCDI.java
- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/org/dashbuilder/dataset/DataSetDefRegistryCDITest.java
- dashbuilder/dashbuilder-backend/dashbuilder-navigation-backend/src/main/java/org/dashbuilder/navigation/service/PerspectivePluginServicesImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-navigation-backend/src/main/java/org/dashbuilder/navigation/storage/NavTreeStorage.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/pom.xml
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/migration/DashbuilderDataMigration.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/migration/DashbuilderDataMigrationTest.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/main/java/org/dashbuilder/client/widgets/dataset/editor/csv/CSVDataSetDefAttributesEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-widgets/src/test/java/org/dashbuilder/client/widgets/dataset/editor/csv/CSVDataSetDefAttributesEditorTest.java
- dashbuilder/dashbuilder-webapp/.gitignore
- uberfire-api/src/main/java/org/uberfire/spaces/SpacesAPI.java
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/SystemConfigProducer.java
- uberfire-backend/uberfire-backend-cdi/src/test/java/org/uberfire/backend/server/cdi/SystemConfigProducerTest.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-backend/src/main/java/org/uberfire/ext/layout/editor/impl/PerspectiveServicesImpl.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-backend/src/test/java/org/uberfire/ext/layout/editor/impl/PerspectiveServicesImplTest.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-api/src/main/java/org/uberfire/ext/plugin/model/PluginType.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-api/src/main/java/org/uberfire/ext/plugin/service/PluginServices.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/main/java/org/uberfire/ext/plugin/backend/PluginServicesImpl.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/test/java/org/uberfire/ext/plugin/backend/PluginServicesImplTest.java
- uberfire-io/src/test/java/org/uberfire/io/GitIOServiceDotFileTest.java
- uberfire-testing-utils/src/main/java/org/uberfire/mocks/FileSystemTestingUtils.java
Fixing system config produces FS to uses GIT as scheme, fixing some pom deps and also deploy files created automatically.
Also undo the reverting in the gabriel's commit.
@pefernan is that everything right?
> AF 1957 fixes

- uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/engine/BatchIndexListener.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/BatchIndex.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/elasticsearch/BatchIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BatchIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/BatchIndexTest.java
- Added listener to get notifications when the project indexing has started or finished
https://github.com/kiegroup/appformer/pull/755
https://github.com/kiegroup/kie-wb-common/pull/2794
> AF-2116: Verify Async load of Projects and Spaces Cards

- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/LoadReposOnAppInit.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/LoadReposOnAppInitTest.java
making the repos available via http, ssh or git without requiring any UI interaction
> AF-2138: initialized the repositories on app initialization

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/GridHighlightHelper.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/GridHighlightHelperTest.java
Part of an ensemble. This is are new PRs since the older was broken.
https://github.com/kiegroup/kie-wb-common/pull/2801
https://github.com/kiegroup/appformer/pull/759
https://github.com/kiegroup/drools-wb/pull/1206
> DROOLS-4319: [DMN Designer] Search feature - Implement search feature in the GDT graphs editor

- uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorImpl.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorSelectedPageEvent.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorViewImpl.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorImplTest.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorViewImplTest.java
See: https://issues.jboss.org/browse/DROOLS-4321
---
- https://github.com/kiegroup/appformer/pull/762
- https://github.com/kiegroup/kie-wb-common/pull/2791
- https://github.com/kiegroup/drools-wb/pull/1207
> DROOLS-4321: [DMN Designer] Search feature - DMN Data Types must be searchable elements

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/exceptions/RetryException.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/utils/Retry.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContextTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/utils/RetryTest.java
@ederign would you mind to review?
> [AF-2049]: Added retries to fix slow connection problems

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/util/GridHighlightHelper.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/GridRendererTheme.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/KIEColours.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/GridHighlightHelperTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererTest.java
This PR is part of an ensemble and also covers [DROOLS-4406](https://issues.jboss.org/projects/DROOLS/issues/DROOLS-4406).
https://github.com/kiegroup/drools-wb/pull/1214
https://github.com/kiegroup/appformer/pull/767
https://github.com/kiegroup/kie-wb-common/pull/2815
> DROOLS-4407: [DMN Designer] Search feature - Highlight the current result with colors that follow the PF standard

- pom.xml
Reverts kiegroup/appformer#806
> Revert "javax.validation-api needs to keep older version"

- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/metadata/MetadataService.java
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataServiceImpl.java
- uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/MetadataServiceImplTest.java
https://issues.jboss.org/browse/DROOLS-4569
Bundle:
https://github.com/kiegroup/appformer/pull/809
https://github.com/kiegroup/kie-wb-common/pull/2922
https://github.com/kiegroup/drools-wb/pull/1234
> DROOLS-4569 : XLS editor should have a save button

- uberfire-message-console/uberfire-message-console-api/src/main/java/org/guvnor/messageconsole/events/FilteredMessagesEvent.java
- uberfire-message-console/uberfire-message-console-api/src/main/java/org/guvnor/messageconsole/utils/CSVConverter.java
- uberfire-message-console/uberfire-message-console-api/src/main/resources/org/guvnor/messageconsole/GuvnorMessageConsoleAPI.gwt.xml
- uberfire-message-console/uberfire-message-console-api/src/test/java/org/guvnor/messageconsole/utils/CSVConverterTest.java
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleScreen.java
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleService.java
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleView.java
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleViewImpl.java
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleViewImpl.ui.xml
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/resources/i18n/MessageConsoleConstants.java
- uberfire-message-console/uberfire-message-console-client/src/main/resources/org/guvnor/messageconsole/client/console/resources/i18n/MessageConsoleConstants.properties
- uberfire-message-console/uberfire-message-console-client/src/test/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceTest.java
Implements [AF-2176](https://issues.jboss.org/browse/AF-2176)
> [AF-2176] Error messages need to be able to be copied

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedTest.java
**Jira**: [RHPAM-2308](https://issues.jboss.org/browse/RHPAM-2308)
**Backport**: 
- [JBPM-8780](https://issues.jboss.org/browse/JBPM-8780)
- [JBPM-8825](https://issues.jboss.org/browse/JBPM-8825)
- [JBPM-8784](https://issues.jboss.org/browse/JBPM-8784)
- https://github.com/kiegroup/appformer/pull/816
- https://github.com/kiegroup/kie-wb-common/pull/2938
> [7.5.1] Backport: JBPM-8780, JBPM-8825, JBPM-8784

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/ickl/IckleConverter.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/ickl/converters/RegexpQueryConverter.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/ickl/IcklConverterTest.java
Backport of [AF-2223](https://issues.jboss.org/browse/AF-2223) https://github.com/kiegroup/appformer/pull/780
> Backport of [AF-2223] #780

- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/metadata/MetadataService.java
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataServiceImpl.java
- uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/MetadataServiceImplTest.java
(cherry picked from commit 47ba3be5871046f07672a850438e100b5f23aed2)
https://issues.jboss.org/browse/DROOLS-4569
https://github.com/kiegroup/appformer/pull/823
https://github.com/kiegroup/kie-wb-common/pull/2970
https://github.com/kiegroup/drools-wb/pull/1249
> [7.26.x] DROOLS-4569 : XLS editor should have a save button

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedTest.java
This issue is addressed by the following JIRA: 
https://issues.jboss.org/browse/JBPM-8784
> [JBPM-8784] Avoid indexing dot files

- uberfire-api/src/main/java/org/uberfire/workbench/events/NotificationEvent.java
- uberfire-project/uberfire-project-client/pom.xml
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/security/ProjectController.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/NotificationPopupView.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/NotificationPopupsManagerView.java
Implement [AF-2244](https://issues.jboss.org/projects/AF/issues/AF-2244) UX support/guidance after new deployment
Depends on https://github.com/kiegroup/kie-wb-common/pull/2986
> [AF-2244] UX support/guidance after new deployment

- uberfire-commons/src/main/java/org/uberfire/commons/cluster/ClusterJMSService.java
- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/ExecutorServiceProducer.java
- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/Indexing.java
- uberfire-commons/src/test/java/org/uberfire/commons/cluster/ClusterJMSServiceTest.java
* Fixed JMS Listener creation
* Added indexing threads limit
Related to: 
* https://github.com/kiegroup/appformer/pull/822
* https://github.com/kiegroup/kie-wb-common/pull/2957
> [AF-2269]: Fixed JMS Listener

- uberfire-backend/uberfire-backend-server/pom.xml
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/BasicAuthorizationPrincipal.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSourceTest.java
- uberfire-security/uberfire-security-backend/.gitignore
- uberfire-security/uberfire-security-backend/pom.xml
- uberfire-security/uberfire-security-backend/src/main/java/org/uberfire/security/backend/BasicAuthorizationPrincipal.java
**Task**: [AF-2328](https://issues.jboss.org/browse/AF-2328)
- https://github.com/kiegroup/appformer/pull/837
- https://github.com/kiegroup/droolsjbpm-integration/pull/1936
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1101
> [AF-2328] Removing BasicAuthorizationPrincipal from user's groups

- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/BackendExperimentalFeaturesRegistryServiceImpl.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/impl/ExperimentalFeaturesStorageImpl.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/migration/StorageMigration.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/migration/StorageMigrationService.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/migration/impl/StorageMigrationServiceImpl.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/migration/impl/migrations/V2StorageMigration.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/scoped/ExperimentalStorageScope.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/scoped/ScopedExperimentalFeaturesStorage.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/scoped/impl/AbstractScopedExperimentalFeaturesStorage.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/scoped/impl/GlobalExperimentalFeaturesStorageImpl.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/scoped/impl/UserExperimentalFeaturesStorageImpl.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/util/ExperimentalConstants.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/BackendExperimentalFeaturesRegistryServiceImplTest.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/storage/impl/ExperimentalFeaturesStorageImplTest.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/storage/migration/impl/StorageMigrationServiceImplTest.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/storage/migration/impl/migrations/V2StorageMigrationTest.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/storage/scoped/impl/AbstractExperimentalFeaturesStorageTest.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/storage/scoped/impl/GlobalExperimentalFeaturesStorageImplTest.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/storage/scoped/impl/UserExperimentalFeaturesStorageImplTest.java
- uberfire-experimental/uberfire-experimental-backend/src/test/java/org/uberfire/experimental/service/util/TestUtils.java
@tomasdavidorg @paulovmr could you please take a look?
> AF-1768: Errors on Windows when login user account contains special character

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2ServletContextListener.java
- uberfire-services/uberfire-services-backend/src/test/java/org/guvnor/common/services/backend/archive/ArchiverTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/pom/PomEditorDefaultTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/pom/PomStructureEditorTest.java
In these tests `File.separator` is not necessary, because META-INF are inside jars, so the dir structure will be using this "/"
> AF-2264-fix_tests_on_w2k16

- uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/engine/MetaIndexEngine.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/provider/IndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/main/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/pom.xml
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/exceptions/InfinispanException.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingService.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/utils/Retry.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/provider/LuceneIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/BatchIndex.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/index/MetadataIndexEngine.java
* https://github.com/kiegroup/appformer/pull/838
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1092
* https://github.com/kiegroup/kie-wb-common/pull/2991
* https://github.com/kiegroup/jbpm-wb/pull/1401
* https://github.com/kiegroup/drools-wb/pull/1256
* https://github.com/kiegroup/kie-wb-distributions/pull/986
* https://github.com/kiegroup/optaplanner-wb/pull/349
> [AF-2310]: Added infinispan ping service to prevent spawning threads

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/DownloadMenuItemBuilder.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/DownloadMenuItemBuilderTest.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUpload.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUploadParametersTest.java
- uberfire-server/src/main/java/org/uberfire/server/FileUploadServlet.java
- uberfire-server/src/main/java/org/uberfire/server/UploadUriProvider.java
- uberfire-server/src/main/java/org/uberfire/server/util/FileServletUtil.java
- uberfire-server/src/test/java/org/uberfire/server/UploadUriProviderTest.java
https://issues.jboss.org/browse/AF-2252
https://github.com/kiegroup/appformer/pull/804
https://github.com/kiegroup/kie-wb-common/pull/2967
https://github.com/kiegroup/drools-wb/pull/1262
> AF-2252 : File download does not work with & character

- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/EnvironmentParameters.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryEnvironmentConfiguration.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryEnvironmentConfigurations.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationFactoryImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelper.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryServiceImplTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperBaseTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperNoIndexTest.java
Backport of https://github.com/kiegroup/appformer/pull/852
@adrielparedes @ederign @tomasdavidorg  could you please take a look??
https://github.com/kiegroup/appformer/pull/853
https://github.com/kiegroup/kie-wb-common/pull/3031
> [7.30.x] RHPAM-2531: Cloning from remote git repo that requires credentials does not work

- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/EnvironmentParameters.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryEnvironmentConfiguration.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryEnvironmentConfigurations.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationFactoryImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelper.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryServiceImplTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperBaseTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperNoIndexTest.java
This PR fixes an issue that was making the user credentials not being correctly generated. 
@adrielparedes @ederign @tomasdavidorg  could you please take a look??
https://github.com/kiegroup/appformer/pull/852
https://github.com/kiegroup/kie-wb-common/pull/3030
> AF-2384: Cloning from remote git repo that requires credentials does not work

- pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyBootstrapper.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyClientBundle.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/MomentTimeZone.java
See https://issues.jboss.org/browse/BAPL-1376
(Although manifested itself in https://issues.jboss.org/browse/KOGITO-523).
- https://github.com/kiegroup/appformer/pull/858
- https://github.com/kiegroup/kie-wb-common/pull/2990
> KOGITO-523: [DMN Designer] Cannot define Time Data Type Range constraint

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanelTest.java
See https://issues.jboss.org/browse/DROOLS-4791
> DROOLS-4791: [DMN Designer] Not able to edit by double click after scroll

- appformer-js/pom.xml
> BXMSPROD-580: frontend-maven-plugin version pointing to the centralised one

- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/WorkspaceProjectService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplResolveWorkspaceWorkspaceProjectTest.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/CompileProjectCmd.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/DeployProjectCmd.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/InstallProjectCmd.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/cmd/TestProjectCmd.java
- uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/JobRequestHelperTest.java
- uberfire-rest/uberfire-rest-backend/src/test/java/org/guvnor/rest/backend/ProjectResourceJobTest.java
- uberfire-rest/uberfire-rest-client/src/main/java/org/guvnor/rest/client/CompileProjectRequest.java
- uberfire-rest/uberfire-rest-client/src/main/java/org/guvnor/rest/client/DeployProjectRequest.java
- uberfire-rest/uberfire-rest-client/src/main/java/org/guvnor/rest/client/InstallProjectRequest.java
- uberfire-rest/uberfire-rest-client/src/main/java/org/guvnor/rest/client/TestProjectRequest.java
[[AF-2332] Add Branch support to Business Central REST API](https://issues.jboss.org/browse/AF-2332)
The following existing URLs were not changed and points to master branch:
```
/spaces/${spaceName}/projects/${projectName}/maven/compile
/spaces/${spaceName}/projects/${projectName}/maven/deploy
/spaces/${spaceName}/projects/${projectName}/maven/install
/spaces/${spaceName}/projects/${projectName}/maven/test
```
The following URLs were created to add branch parameter:
```
/spaces/${spaceName}/projects/${projectName}/branches/${branchName}/maven/compile
/spaces/${spaceName}/projects/${projectName}/branches/${branchName}/maven/deploy
/spaces/${spaceName}/projects/${projectName}/branches/${branchName}/maven/install
/spaces/${spaceName}/projects/${projectName}/branches/${branchName}/maven/test …
```
> [AF-2332] Add Branch support to Business Central REST API

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/main/java/org/uberfire/ext/editor/commons/backend/version/VersionServiceImpl.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/version/VersionServiceImplTest.java
https://issues.jboss.org/browse/AF-2341
> AF-2341 : Not able to restore files where dot file (metadata) has been edited

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchCloseHandler.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchCloseHandlerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchCloseHandlerImplFallback.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/WorkbenchCloseHandlerImplTest.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/WorkbenchStartupTest.java
* https://github.com/kiegroup/appformer/pull/864
* https://github.com/kiegroup/kie-wb-common/pull/3062
> KOGITO-436: DMN editor prevents page from closing with a warning popup in `window.alert` style

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/PanelManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/PanelManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/panels/impl/StaticWorkbenchPanelView.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/StaticWorkbenchPanelViewTest.java
See https://issues.redhat.com/browse/KOGITO-724
Before
After
> KOGITO-724: [DMN Designer] Data Types are not editable in online editors

- uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/api/FileSystemProviders.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-k8s/src/test/java/org/uberfire/java/nio/fs/k8s/FileSystemProvidersTest.java
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
> [AF-2058] Fixing incomplete logic for setting k8s filesystem provider as default if it is installed

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/GitImpl.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/WorkspaceProjectService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/POMServiceImpl.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplNewWorkspaceWorkspaceProjectTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplResolveWorkspaceWorkspaceProjectTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplTest.java
- uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/preferences/SpaceScopedResolutionStrategySupplier.java
- uberfire-project/uberfire-project-client/src/test/java/org/guvnor/common/services/project/client/preferences/SpaceScopedResolutionStrategySupplierTest.java
- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/preferences/DefaultWorkbenchPreferenceScopeResolutionStrategies.java
- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/preferences/GuvnorPreferenceScopes.java
- uberfire-services/uberfire-services-api/src/main/java/org/guvnor/common/services/shared/preferences/WorkbenchPreferenceScopeResolutionStrategies.java
- uberfire-services/uberfire-services-api/src/test/java/org/guvnor/common/services/shared/preferences/DefaultWorkbenchPreferenceScopeResolutionStrategiesTest.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryEnvironmentConfigurations.java
**Task**: [AF-2366](https://issues.redhat.com/browse/AF-2366)
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1151
- https://github.com/kiegroup/kie-soup/pull/124
- https://github.com/kiegroup/appformer/pull/872
- https://github.com/kiegroup/kie-wb-common/pull/3098
- https://github.com/kiegroup/jbpm-wb/pull/1406
- https://github.com/kiegroup/drools-wb/pull/1278
- https://github.com/kiegroup/optaplanner-wb/pull/352
- https://github.com/kiegroup/kie-wb-distributions/pull/1005
**DEMO**
**Notes**
The maven archetype used on the demo is available at [this link](https://drive.google.com/open?id=1k-7SJPtGIXc8-lK74Q3oZKgpgPGDfwfM).
Unzip it and execute `mvn clean install`, then the archetype will be available to be added into BC.
> [AF-2366] BC Maven Archetype Support

- pom.xml
https://issues.redhat.com/browse/AF-2413
> AF-2413: upgrade of elasticsearch to 5.6.15

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorViewImpl.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorViewImplTest.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/multipage/MultiPageEditorView.java
https://github.com/kiegroup/kie-wb-common/pull/3123
> AF-2418: Add logic for editor page index computation

- uberfire-client-api/src/main/java/org/uberfire/client/util/Cookie.java
- uberfire-client-api/src/test/java/org/uberfire/client/util/CookieTest.java
[AF-2382 Store last space opened in browser cookie](https://issues.redhat.com/browse/AF-2382)
* https://github.com/kiegroup/appformer/pull/870
* https://github.com/kiegroup/kie-wb-common/pull/3090
> [AF-2382] Store last space opened in browser cookie

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/GitImpl.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/AddRemote.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitAddRemoteTest.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/ModuleServiceCore.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/WorkspaceProjectService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractModuleService.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractModuleServiceTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/ModuleServiceMock.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplNewWorkspaceWorkspaceProjectTest.java
**Task**: [AF-2363](https://issues.redhat.com/browse/AF-2363)
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1171
- https://github.com/kiegroup/appformer/pull/881
- https://github.com/kiegroup/kie-wb-common/pull/3126
- https://github.com/kiegroup/drools-wb/pull/1293
- https://github.com/kiegroup/optaplanner-wb/pull/353
- https://github.com/kiegroup/jbpm-wb/pull/1410
- https://github.com/kiegroup/kie-wb-distributions/pull/1009
> [AF-2363] Be able to create projects from empty repositories

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/GitImpl.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Merge.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitMergeTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitRevertMergeTest.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/changerequest/ChangeRequestService.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/changerequest/portable/ChangeRequestCommit.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ChangeRequestServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/ChangeRequestServiceTest.java
Finishing the work that has been started in https://github.com/kiegroup/appformer/pull/871.
**Task**:
[AF-2373](https://issues.redhat.com/browse/AF-2373)
- https://github.com/kiegroup/appformer/pull/884
- https://github.com/kiegroup/kie-wb-common/pull/3132
> [AF-2373] Squash Commits on Change request

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
For more details see: https://issues.redhat.com/browse/DROOLS-4793
> DROOLS-4793: Reduce RenderingInformation computation for cell editing

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseKeyboardOperation.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseKeyboardOperationTest.java
For more details see https://issues.redhat.com/browse/DROOLS-4792
> DROOLS-4792: Reduce RenderingInformation computation

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMove.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveDown.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveLeft.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveRight.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveUp.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetKeyboardHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveDownTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveLeftTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveRightTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/KeyboardOperationMoveUpTest.java
https://github.com/kiegroup/kie-wb-common/pull/3135
https://github.com/kiegroup/appformer/pull/885
This may affect others editors, so I created a new constructor and called it in DMN editor only.
> RHDM-1016: [DMN Designer] Scroll Bars are not updated when keyboard is used for navigation

- uberfire-testing-utils/src/main/java/org/uberfire/mocks/FileSystemTestingUtils.java
* changed to fetch existing File System when setting up JGit repo
> AF-2444 : Fixed failing test for prod build

- uberfire-experimental/uberfire-experimental-client/src/main/resources/org/uberfire/experimental/client/resources/i18n/UberfireExperimentalConstants_es.properties
- uberfire-experimental/uberfire-experimental-client/src/main/resources/org/uberfire/experimental/client/resources/i18n/UberfireExperimentalConstants_fr.properties
- uberfire-ssh/uberfire-ssh-client/src/main/resources/org/uberfire/ssh/client/resources/i18n/AppformerSSHConstants_es.properties
- uberfire-ssh/uberfire-ssh-client/src/main/resources/org/uberfire/ssh/client/resources/i18n/AppformerSSHConstants_fr.properties
(cherry picked from commit a34a4d639e4c78dc9b4b3a3c44809ae6a0e74cf5)
added missing FR and SP translations
> added missing translations

- pom.xml
Reverts kiegroup/appformer#901
See https://issues.redhat.com/browse/RHPAM-1954?focusedCommentId=14000696&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14000696
See https://issues.redhat.com/browse/DROOLS-5170
> Revert "RHPAM-1954 :CVE in webjars used by business-central"

- pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
See https://issues.redhat.com/browse/DROOLS-5157
> DROOLS-5157: [DMN Designer] Monaco editor: Scrolling inside LiteralExpression editor breaks users ability to input data

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoStandaloneCodeEditor.java
See https://issues.redhat.com/browse/DROOLS-5006
---
- https://github.com/kiegroup/appformer/pull/929
- https://github.com/kiegroup/kie-wb-common/pull/3229
> DROOLS-5006: [DMN Designer] Code Completion - When users leave it opened, it never disappears

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/GitHookSupport.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/CreateRepository.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImpl.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/WorkspaceProjectServiceImplNewWorkspaceWorkspaceProjectTest.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/ChangeRequestServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/ChangeRequestServiceTest.java
The primary goal of this PR is to resolve [AF-2434](https://issues.redhat.com/browse/AF-2434).
However, I have also included some other minor related fixes to improve the development workflow, which are:
- Trigger the post commit hook after a change request is merged.
- Trigger the post commit hook after an empty repository is imported.
> [AF-2434] Git hook mechanism improvements

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/GitImpl.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryUtils.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/server/config/ConfigurationService.java
- uberfire-structure/uberfire-structure-api/src/test/java/org/guvnor/structure/repositories/RepositoryUtilsTest.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigCleanUp.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/config/ConfigurationServiceImplTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigCleanUpTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperBaseTest.java
- https://github.com/kiegroup/appformer/pull/921
- https://github.com/kiegroup/kie-wb-common/pull/3219
> [AF-2445] Cleanup credentials

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/pom.xml
For more details see https://issues.redhat.com/browse/AF-2466
> AF-2466: Remove unused dependency of uberfire-nio2-jgit

- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/ResourceContentService.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/impl/EnvelopeResourceContentService.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/impl/NoOpResourceContentService.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/interop/ResourceContentEditorServiceWrapper.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/resource/interop/ResourceListOptions.java
Adding missing bits of the JSInterop Layer
@jesuino could you please take a look?
This is part of an ensemble please merge with:
> KOGITO-1426: Re-enable Resource Content API

- uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/api/FileSystemUtils.java
Keep insync with the system property name change
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
> [RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken

- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationPolicy.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultPermissionManager.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DotNamedPermission.java
- uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/DefaultPermissionManagerTest.java
Original PR : https://github.com/kiegroup/appformer/pull/926
> [7.7.1] RHPAM-2708 : RHPAM 7.x Business Central latency correlated with number of groups memberships

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/Git.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/GitImpl.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryUtils.java
- uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/server/config/ConfigurationService.java
- uberfire-structure/uberfire-structure-api/src/test/java/org/guvnor/structure/repositories/RepositoryUtilsTest.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigCleanUp.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/config/ConfigurationServiceImplTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigCleanUpTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperBaseTest.java
(cherry picked from commit c63c402cf3052b9f753d225247933a7d6cbfb82c)
original PR: https://github.com/kiegroup/appformer/pull/921
merge with : https://github.com/kiegroup/kie-wb-common/pull/3275
> [7.7.1] RHPAM-2838 :Credentials not cleaned up after git repo import

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/WorkbenchServicesImpl.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-service/uberfire-widgets-service-backend/src/main/java/org/uberfire/ext/services/backend/preferences/UserPreferencesServiceImpl.java
- uberfire-extensions/uberfire-wires/uberfire-wires-bayesian-parser/uberfire-wires-bayesian-parser-backend/pom.xml
- uberfire-extensions/uberfire-wires/uberfire-wires-bayesian-parser/uberfire-wires-bayesian-parser-backend/src/main/java/org/uberfire/ext/wires/bayesian/network/parser/backend/BayesianServiceImpl.java
- uberfire-extensions/uberfire-wires/uberfire-wires-bpmn/uberfire-wires-bpmn-backend/src/main/java/org/uberfire/ext/wires/bpmn/backend/BpmnPersistence.java
- uberfire-nio2-backport/uberfire-nio2-model/pom.xml
- uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/Properties.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ModuleRepositoriesContentHandler.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectConfigurationContentHandler.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigGroupMarshaller.java
part of https://github.com/kiegroup/kie-soup/pull/137
> KOGITO-1546 XStreamUtils kie-soup refactoring

- dashbuilder/dashbuilder-webapp/pom.xml
- pom.xml
- uberfire-showcase/uberfire-webapp/pom.xml
For more details see https://issues.redhat.com/browse/AF-2487
> AF-2487: Reuse errai.wildfly property form kie-parent

- dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/migration/DashbuilderDataMigration.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/DataTransferServicesImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/transfer/DataTransferServicesTest.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
- dashbuilder/dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/transfer/DataTransferView.java
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/SystemConfigProducer.java
- uberfire-backend/uberfire-backend-cdi/src/test/java/org/uberfire/backend/server/cdi/SystemConfigProducerTest.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/LockClientNotifier.java
- uberfire-experimental/uberfire-experimental-backend/src/main/java/org/uberfire/experimental/service/storage/impl/ExperimentalFeaturesStorageImpl.java
- uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/api/FileSystemUtils.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFSPath.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImpl.java
- uberfire-preferences/uberfire-preferences-backend/src/main/java/org/uberfire/preferences/backend/PreferenceStorageImpl.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/PathUtil.java
- uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/backend/server/impl/ExperimentalEditorServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigCleanUp.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/LoadReposOnAppInit.java
- uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/SystemRepository.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/config/SpaceConfigCleanUpTest.java
- uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/LoadReposOnAppInitTest.java
Replace all the references to JGit filesystem using Default Schema. That way other file system providers can be used.
* https://github.com/kiegroup/appformer/pull/880
* https://github.com/kiegroup/kie-wb-common/pull/3289
> AF-2253: Schema.GIT replaced by default

- dashbuilder/dashbuilder-backend/dashbuilder-dataset-cdi/pom.xml
- dashbuilder/dashbuilder-distros/pom.xml
- dashbuilder/dashbuilder-webapp/pom.xml
- uberfire-api/pom.xml
- uberfire-backend/uberfire-backend-cdi/pom.xml
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyGroupPropertiesManager.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyUserPropertiesManager.java
- uberfire-project/uberfire-project-backend/pom.xml
- uberfire-project/uberfire-project-client/pom.xml
- uberfire-security/uberfire-security-api/pom.xml
- uberfire-services/uberfire-services-api/pom.xml
- uberfire-services/uberfire-services-backend/pom.xml
- uberfire-structure/uberfire-structure-backend/pom.xml
- uberfire-test-utils/pom.xml
https://issues.redhat.com/browse/JBPM-9044
Parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1203
> JBPM-9044: wildfly 18.x upgrade

- pom.xml
For more details see: https://issues.redhat.com/browse/AF-2489
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1287
> AF-2489: Consolidate wildfly.security version

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderConcurrentOperationsTest.java
https://issues.redhat.com/browse/BXMSPROD-744
> BXMSPROD-744 JGitFileSystemProviderConcurrentOperationsTest.testConcurrentGitCreation ignored

- uberfire-backend/uberfire-backend-api/src/main/java/org/uberfire/backend/fs/FileSystemService.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/fs/FileSystemServiceImpl.java
Related to:
* https://github.com/kiegroup/appformer/pull/895
* https://github.com/kiegroup/kie-wb-common/pull/3314
* https://github.com/kiegroup/drools-wb/pull/1379
* https://github.com/kiegroup/jbpm-wb/pull/1436
* https://github.com/kiegroup/optaplanner-wb/pull/371
* https://github.com/kiegroup/kie-wb-distributions/pull/1010
> AF-2411: Added service to consume file system properties

- uberfire-distro/pom.xml
- uberfire-showcase/showcase-distribution-wars/pom.xml
- uberfire-showcase/showcase-distribution-wars/src/main/assembly/assembly-showcase-wildfly.xml
Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1347
> BXMSPROD-685: changed assembly for uberfire-showcase

- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/workspace/WorkspaceService.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/workspace/impl/DefaultWorkspaceServiceImpl.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/workspace/impl/WorkspaceServiceImpl.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/workspace/interop/WorkspaceServiceWrapper.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/workspace/producer/WorkspaceServiceProducer.java
**Task**: [KOGITO-2076](https://issues.redhat.com/browse/KOGITO-2076)
- https://github.com/kiegroup/appformer/pull/961
- https://github.com/kiegroup/kogito-tooling/pull/151
> KOGITO-2076: Open File API

- dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/DataTransferServicesImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/transfer/DataTransferServicesTest.java
With this change private datasets are not displayed anymore in Gradual Export screen.
> AF-2561: Gradual Export shows internal datasources

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java
For more details see: https://issues.redhat.com/browse/DROOLS-5442
> DROOLS-5442: Asume column visibility during keyboard navigation

- uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json
depends on kiegroup/droolsjbpm-build-bootstrap#1404
> BAQE-1488 - Change revapi to check against 7.39.0.Final

- uberfire-api/src/main/java/org/uberfire/backend/vfs/impl/ObservablePathImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/CoreIndexer.java
Ensemble PR:
kie-wb-common [#3331](https://github.com/kiegroup/kie-wb-common/pull/3331)
> AF-2552 : [Data Modeler] Cannot save file if it was moved from other package

- dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/DataTransferServicesImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/transfer/DataTransferServicesTest.java
RHPAM-3021: Gradual Export shows internal datasources
Backport of AF-2561. With this change internal datasources won't be displayed in Gradual Export.
Thanks.
> RHPAM-3021: Gradual Export shows internal datasources

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/JAASAuthenticationService.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
- uberfire-extensions/uberfire-security/uberfire-servlet-security/src/main/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationService.java
- uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationServiceTest.java
(cherry picked from commit a3ab6d1199a8fa4cf93b6ff635e8881a9c7e61c8)
original PR : https://github.com/kiegroup/appformer/pull/1000
> RHPAM-2981 :Unable to access business-central after user containing dot(.) character changes role settings

- dashbuilder/dashbuilder-runtime/src/main/java/org/dashbuilder/backend/security/BasicAuthSecurityFilter.java
- dashbuilder/dashbuilder-runtime/src/main/webapp/WEB-INF/web.xml
This is a requirement for build the react components, it makes the REST API authentication type BASIC instead FORM.
The filter responsible for this was taken from Business Central, so not my code. 
The REST API should be accessible by any role. We can change this later.
To test this change simply access dashbuilder runtime REST API using basic credentials:
```
curl -u 'admin:admin' http://localhost:8080/rest/api
```
> AF-2546: React components for embedded dashboards

- dashbuilder/dashbuilder-runtime/pom.xml
Wrong version kept after rebase
> Update Runtime version

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java
For more details see https://issues.redhat.com/browse/DROOLS-5521
> DROOLS-5521: Handle pressing TAB when editing last cell

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java
> [7.39.x] DROOLS-5442: Asume column visibility during keyboard navigation

- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/map/D3MapConf.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/map/D3MapDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/map/widgets/D3Map.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/map/widgets/MapTooltip.css
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/map/widgets/MapTooltip.java
This is a quick fix for an issue I found which would impact a demo I am working on.
With this fix:
* Tooltips will be displayed again;
* There's the option to hide the bad legend
> AF-2581: Maps tooltip is gone

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/provider/LuceneIndexProvider.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedTest.java
@paulovmr cherry-picked from:
* https://github.com/kiegroup/appformer/pull/1018
> AF-2587: Indexes are removed when project is deleted

- appformer-client-api/src/main/java/org/appformer/client/context/DefaultEditorContextProviderImpl.java
- appformer-client-api/src/main/java/org/appformer/client/context/EditorContextProvider.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/context/impl/KogitoEditorContextProviderImpl.java
- appformer-kogito-bridge/src/main/java/org/appformer/kogito/bridge/client/context/interop/EditorContextWrapper.java
**JIRA**:
[link](https://issues.redhat.com/browse/KOGITO-543)
https://github.com/kiegroup/kie-wb-common/pull/3361
> KOGITO-543: DMN - Read Only mode

- pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/MonacoEditorInitializer.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoStandaloneCodeEditor.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/monaco/MonacoEditorInitializerTest.java
hey @karreiro @LuboTerifaj 
Just a quick improvement to make the Monaco Editor work properly in the BPMN editor.
See https://issues.redhat.com/browse/BAPL-678
Assembly:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1429
- https://github.com/kiegroup/appformer/pull/1012
- https://github.com/kiegroup/kie-wb-common/pull/3372
Thanks!
> BAPL-678: BPMN Editor - Syntax Highlighting Editor

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanContext.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/main/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingService.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java
I fail to connect to a remote server without increasing this timeout
* link 2
* link 3 etc.
<pre>
* <b>an upstream build</b> please add comment: <b>Jenkins run …
> Increase connection timeout and retries

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitBasicAttributeView.java
**Description** :
- Added feature to show corresponding last modification date and creation date for assets in  asset list.
**RHPAM-2865**: https://issues.redhat.com/browse/RHPAM-2865
**AF-2497**: https://issues.redhat.com/browse/AF-2497
<pre>
</pre>
> RHPAM-2865 : Wrong created date on asset list

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-996
Related with:
* https://github.com/kiegroup/appformer/pull/1047
* https://github.com/kiegroup/drools/pull/3096
* https://github.com/kiegroup/kie-wb-common/pull/3416
<pre>
</pre>
> BXMSPROD-996 maven connection timeout

- uberfire-client-api/src/main/java/org/uberfire/client/util/Cookie.java
JIRA: https://issues.redhat.com/browse/RHPAM-2957 
- Setting max age field on browser Cookie 
https://github.com/kiegroup/kie-wb-common/pull/3402
<pre>
</pre>
> RHPAM-2957 : Business Central does not remember the last branch used on log out

- dashbuilder/dashbuilder-backend/dashbuilder-services/src/main/java/org/dashbuilder/transfer/DataTransferServicesImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-services/src/test/java/org/dashbuilder/transfer/DataTransferServicesTest.java
In this PR we improved how components are exported from BC and fixed AF-2627
**JIRA**: 
https://issues.redhat.com/browse/AF-2627
> AF-2627: Data transfer fails when components are disabled

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/pom.xml
https://issues.redhat.com/browse/RHDM-1338
Related to:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1461
- https://github.com/kiegroup/kie-soup/pull/156
- https://github.com/kiegroup/appformer/pull/1049
<pre>
</pre>
> RHDM-1338 org.apache.logging.log4j:log4j-api and log4j-core 2.13.2

- pom.xml
**Description**
ISPN version upgraded to match RHDG 7.3.6
**JIRA**: 
* https://issues.redhat.com/browse/AF-2604
* https://issues.redhat.com/browse/RHPAM-3089
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1444
* https://github.com/kiegroup/appformer/pull/1031
> AF-2604: Infinispan version upgraded to 9.4.19

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/BatchIndex.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/BatchIndexKeepFileTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/BaseIndexTest.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/ModuleResourceResolver.java
- uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ResourceResolver.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/ModuleServiceMock.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/ResourceResolverResolvePackagesTest.java
https://issues.redhat.com/browse/AF-2582
https://github.com/kiegroup/appformer/pull/1010
https://github.com/kiegroup/kie-wb-common/pull/3365
> AF-2582 : Package list dropdown should load faster

- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/charts/map/widgets/MapTooltip.java
[AF-2633](https://issues.redhat.com/browse/AF-2633)
Sorry again for breaking it, I was testing a better tooltip, but I forgot to remove the hidden. Now it is fixed
> AF-2633: Map Tooltip not completely showing

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-996
https://github.com/kiegroup/appformer/pull/1056
https://github.com/kiegroup/drools/pull/3118
https://github.com/kiegroup/kie-wb-common/pull/3429
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1476
<details>
<summary>
</summary>
</details>
> BXMSPROD-996 http arguments for upstream commands

- uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json
**JIRA**: [BAQE-1567](https://issues.redhat.com/browse/BAQE-1567)
depends on kiegroup/droolsjbpm-build-bootstrap#1485
> BAQE-1567 - Change revapi to check against 7.44.0.Final

- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/ExternalComponentDispatcher.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/ExternalComponentListener.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/ExternalComponentMessageHelperProducer.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/function/ComponentFunctionLocator.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/function/ExternalComponentFunction.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/component/function/GWTVersion.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/ExternalComponentEditor.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/ExternalComponentPresenter.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/ExternalComponentView.html
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/ExternalComponentView.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/resources/org/dashbuilder/displayer/client/resources/i18n/CommonConstants.properties
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/component/ExternalComponentDispatcherTest.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/component/function/ComponentFunctionLocatorTest.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/widgets/ExternalComponentPresenterTest.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/DisplayerDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/external/ExternalDragComponent.java
- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/main/java/org/dashbuilder/renderer/client/external/ExternalComponentDisplayer.java
- dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/pom.xml
- dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/external/ExternalComponentMessageHelper.java
- dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/external/ExternalComponentMessageType.java
- dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/external/FunctionCallRequest.java
- dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/external/FunctionResponse.java
- dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/external/FunctionResultType.java
- dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/test/java/org/dashbuilder/displayer/external/ExternalComponentMessageHelperTest.java
[AF-2636](https://issues.redhat.com/browse/AF-2636)
This is a major change for components protocol to allow us to plug reusable functions that can be called by components. To achieve this we had first to formalize the messages exchange between custom components and DB, so we introduced Message type and class ExternalComponentDispatcher, that listen for all messages, look for the component and deliver the message.
This is a breaking change because now we support messages of type "INIT", which are sent without DATASET so users can find its own ID.
If a message is a function call then we have a function lookup and its execution. The function is currently made internally, but we could extend it to users so they can register their own function.
To a component invoke a function it must:
* First …
> AF-2636: Dashbuilder Pluggable Service Interface

- pom.xml
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/pom.xml
**JIRA**: https://issues.redhat.com/browse/RHDM-1338
<details>
<summary>
</summary>
</details>
> RHDM-1338 log4j-core excluded and log4j-to-slf4j upgraded to 2.13.2

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/DefaultKeyCloakTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManagerTest.java
**RHPAM-2984**: https://issues.redhat.com/browse/RHPAM-2984
</summary>
</details>
> RHPAM-2984 :RHPAM with RHSSO shows reserved roles as a groups as well in business central

- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/AbstractDisplayerTest.java
* Added check for possible cast to number
**JIRA**: [RHPAM-2867](https://issues.redhat.com/browse/RHPAM-2867)
<details>
<summary>
</summary>
</details>
> RHPAM-2867: Pie chart return error when a column use integer number

- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
- dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/AbstractDisplayerTest.java
* Added check for possible cast to number
(cherry picked from commit e6366b5956cae80c923e5f7e18a58ebe7e52b546)
**JIRA**: [RHPAM-2867](https://issues.redhat.com/browse/RHPAM-2867)
<details>
<summary>
</summary>
</details>
> RHPAM-2867: Pie chart return error when a column use integer number (#1070)

- dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/main/java/org/dashbuilder/external/impl/ComponentServiceImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/test/java/org/dashbuilder/external/impl/ComponentServiceImplTest.java
FIX for https://issues.redhat.com/browse/AF-2762
> AF-2762: UI exception when creating a new Page

- uberfire-client-api/src/main/java/org/uberfire/client/workbench/ouia/OuiaAttribute.java
- uberfire-client-api/src/main/java/org/uberfire/client/workbench/ouia/OuiaComponent.java
- uberfire-client-api/src/main/java/org/uberfire/client/workbench/ouia/OuiaComponentIdAttribute.java
- uberfire-client-api/src/main/java/org/uberfire/client/workbench/ouia/OuiaComponentTypeAttribute.java
- uberfire-client-api/src/test/java/org/uberfire/client/workbench/ouia/OuiaComponentIdAttributeTest.java
- uberfire-client-api/src/test/java/org/uberfire/client/workbench/ouia/OuiaComponentTypeAttributeTest.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/DockResizeBar.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/DocksBar.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/bars/DocksCollapsedBar.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/bars/DocksExpandedBar.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/AbstractDockItem.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SideDockItem.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SingleSideDockItem.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SouthDockItem.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/DockResizeBarTest.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/bars/DocksCollapsedBarTest.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/bars/DocksExpandedBarTest.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/items/AbstractDockItemOuiaTest.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/TreeItem.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/tree/TreeItemTest.java
- https://github.com/kiegroup/kie-wb-common/pull/3333
For more details see: https://issues.redhat.com/browse/KOGITO-204
> KOGITO-204: Introduce OUIA attributes to unify kogito integration tests

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java
**JIRA**: https://issues.redhat.com/browse/BAPL-1735
**Related to original PR**: https://github.com/kiegroup/appformer/pull/1085
- PR fixes regression addreessed in this Jira https://issues.redhat.com/browse/BAQE-1641
<details>
<summary>
</summary>
</details>
> BAPL-1735 :[GSS-RFE] RHPAM + RHSSO customer asking for support of Client Roles

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/tab/TabPanelEntry.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/tab/TabPanelEntryTest.java
For KOGITO-3909 easier testing this PR add some OuiaAttributes into the Editor Tab entry
For more details see https://issues.redhat.com/browse/KOGITO-3909
- https://github.com/kiegroup/kie-wb-common/pull/3537
Prerequisite for:
- https://github.com/kiegroup/kogito-tooling/pull/372
> KOGITO-3909: OuiAttributes for Editor Tab Entry

- uberfire-rest/uberfire-rest-backend/src/build/revapi-config.json
**JIRA:** [BAQE-1696](https://issues.redhat.com/browse/BAQE-1696)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1585
> BAQE-1696 - Change revapi to check against 7.48.0.Final

- dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/main/java/org/dashbuilder/external/impl/ComponentServiceImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/test/java/org/dashbuilder/external/impl/ComponentServiceImplTest.java
Fix for https://issues.redhat.com/browse/RHPAM-3387
Backport to 7.48.x
> RHPAM-3387: UI exception when creating a new Page (#1089)

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/KeyCloakGroupManager.java
**RHPAM-3376**: _https://issues.redhat.com/browse/RHPAM-3376_ 
**master branch PR **: _https://github.com/kiegroup/appformer/pull/1088_
<details>
<summary>
</summary>
</details>
> [backport-7.48.x] RHPAM-3376: Group not found error is displayed when a user is assigned to new group (RHSSO)

- dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/main/java/org/dashbuilder/external/impl/ComponentAssetProviderImpl.java
- dashbuilder/dashbuilder-backend/dashbuilder-external-backend/src/test/java/org/dashbuilder/external/impl/ComponentAssetProviderImplTest.java
https://issues.redhat.com/browse/RHPAM-3412
Backport of RHPAM-3412 fix from master
> RHPAM-3412: Getting not found error for heatmap on windows

- dashbuilder/dashbuilder-runtime/pom.xml
https://issues.redhat.com/browse/RHPAM-2933
<details>
<summary>
</summary>
</details>
> RHPAM-2933 log4j dependencies

- dashbuilder/dashbuilder-runtime/pom.xml
https://issues.redhat.com/browse/RHPAM-2933
<details>
<summary>
</summary>
</details>
> RHPAM-2933 log4j dependencies (#1111)

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/ITextModel.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/MonacoLanguages.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/monaco/jsinterop/Position.java
**JIRA**: [KOGITO-4233](https://issues.redhat.com/browse/KOGITO-4233): [DMN Designer] IntelliSense service
**Part of an ensemble**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1611
- https://github.com/kiegroup/drools/pull/3435
- https://github.com/kiegroup/appformer/pull/1115
- https://github.com/kiegroup/kie-wb-common/pull/3590
- https://github.com/kiegroup/drools-wb/pull/1471
- https://github.com/kiegroup/kie-wb-distributions/pull/1091
**Artifacts**:
- **Business Central**: [WAR file](https://www.dropbox.com/s/fu3ra76qhptzprr/KOGITO-4233-bc.war?dl=0)
- **VS Code**: [plugin](https://www.dropbox.com/s/jaxmlnilmexk1zw/KOGITO-4233-plugin.vsix?dl=0)
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: …
> KOGITO-4233: [DMN Designer] IntelliSense service

- dashbuilder/dashbuilder-runtime/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
- dashbuilder/dashbuilder-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
**JIRA**: https://issues.redhat.com/browse/JBPM-9678
Part of an ensemble, merge with:
https://github.com/kiegroup/kie-soup/pull/188
https://github.com/kiegroup/kie-wb-distributions/pull/1092
> JBPM-9678: Standalone workbench does not start

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/index/LuceneIndexManager.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/test/java/org/uberfire/ext/metadata/backend/lucene/index/LuceneInedexManagerTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/KObjectUtil.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/index/MetadataIndexEngine.java
* Deleting all branches index when deleting a project
(cherry picked from commit a2e6ee6b2c0867c9389876b7aa799a74b520bb7c)
**JIRA**:
[RHPAM-3309](https://issues.redhat.com/browse/RHPAM-3309)
[AF-2813](https://issues.redhat.com/browse/AF-2813)
Original PR : https://github.com/kiegroup/appformer/pull/1108
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: …
> AF-2813: java.io.IOException: Too many open files using business-central

- uberfire-message-console/uberfire-message-console-api/src/main/java/org/guvnor/messageconsole/events/PublishBaseEvent.java
- uberfire-message-console/uberfire-message-console-api/src/main/java/org/guvnor/messageconsole/events/UnpublishMessagesEvent.java
- uberfire-message-console/uberfire-message-console-backend/src/main/java/org/guvnor/messageconsole/backend/BuildResultsObserver.java
- uberfire-message-console/uberfire-message-console-client/pom.xml
- uberfire-message-console/uberfire-message-console-client/src/main/java/org/guvnor/messageconsole/client/console/MessageConsoleService.java
- uberfire-message-console/uberfire-message-console-client/src/test/java/org/guvnor/messageconsole/client/console/MessageConsoleServiceTest.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/builder/model/BuildResults.java
- uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/builder/model/IncrementalBuildResults.java
- uberfire-project/uberfire-project-builder/src/main/java/org/guvnor/common/services/builder/ResourceChangeIncrementalBuilder.java
(cherry picked from commit aed56d176693c7cac9e9487dd11fce41ebb58535)
**RHPAM-2647**: _https://issues.redhat.com/browse/RHPAM-2647_ 
original PR: https://github.com/kiegroup/appformer/pull/1096
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: …
> [backport-7.52.x] RHPAM-2647 :[GSS](7.z) Errors when building a project are shown to all users

- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/ExecutorServiceProducer.java
- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/FSWatch.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/BatchIndex.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BaseIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BatchIndexConcurrencyTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/ComplexFieldsTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/FullTextSearchIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/BaseIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/BatchIndexConcurrencyTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/LuceneFullTextSearchIndexTest.java
**JIRA**:
[AF-2822](https://issues.redhat.com/browse/AF-2822)
* https://github.com/kiegroup/appformer/pull/1129
* https://github.com/kiegroup/kie-wb-common/pull/3612
<details>
<summary>
</summary>
</details>
> AF-2822: Thread starvation while indexing fixed

- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/pom.xml
https://issues.redhat.com/browse/AF-2859
Backport into 7.52.x for https://github.com/kiegroup/appformer/pull/1147
> [7.52.x] AF-2859: Exclude D3 Geo conflicting dependencies

- dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/pom.xml
**JIRA**: https://issues.redhat.com/browse/AF-2859
> AF-2859: Exclude D3 Geo conflicting dependencies

- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/ExecutorServiceProducer.java
- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/RestApi.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java
**JIRA**: 
* https://issues.redhat.com/browse/AF-2862
* https://issues.redhat.com/browse/RHPAM-3739
<details>
<summary>
</summary>
</details>
> AF-2862: Decoupled REST Request Executor Service

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/index/directory/DirectoryLuceneIndex.java
https://github.com/kiegroup/appformer/pull/1126
<details>
<summary>
</summary>
</details>
> [7.52.x] AF-2821: Added SerialMergeScheduler to Lucene Directory configuration

- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/ExecutorServiceProducer.java
- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/FSWatch.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/BatchIndex.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BaseIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/BatchIndexConcurrencyTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/ComplexFieldsTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/infinispan/FullTextSearchIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/BaseIndexTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/BatchIndexConcurrencyTest.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/lucene/LuceneFullTextSearchIndexTest.java
Original: https://github.com/kiegroup/appformer/pull/1129
Backport:
* https://github.com/kiegroup/appformer/pull/1161
* https://github.com/kiegroup/kie-wb-common/pull/3655
<details>
<summary>
</summary>
</details>
> [7.52.x] AF-2822: Thread starvation while indexing fixed

- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/ExecutorServiceProducer.java
- uberfire-commons/src/main/java/org/uberfire/commons/concurrent/RestApi.java
- uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java
Backport from https://github.com/kiegroup/appformer/pull/1151
<details>
<summary>
</summary>
</details>
> [7.52.x] AF-2862: Decoupled REST Request Executor Service (#1151)

- dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-app/pom.xml
- dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/pom.xml
- dashbuilder/dashbuilder-runtime-parent/pom.xml
> Fix DB Runtime version

- dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-app/pom.xml
> Fix version

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/resources/org/guvnor/m2repo/backend/server/settings-security.xml
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/test/resources/org/guvnor/m2repo/backend/server/settings.xml
* Fixed mvn security password on GuvnorM2RepositoryTest
**JIRA**: 
[AF-2887](https://issues.redhat.com/browse/AF-2887)
<details>
<summary>
</summary>
</details>
> AF-2887: Test failure on daily-build on main branch

- uberfire-extensions/uberfire-security/uberfire-servlet-security/src/main/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationService.java
- uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationServiceTest.java
**JIRA**:  
[AF-2905](https://issues.redhat.com/browse/AF-2905)
<details>
<summary>
</summary>
</details>
> AF-2905 : Permissions are not applied by priority

- uberfire-server/src/test/resources/expected-2-sample.html
- uberfire-server/src/test/resources/expected-3-sample.html
- uberfire-server/src/test/resources/expected-4-sample.html
- uberfire-server/src/test/resources/expected-sample.html
[https://issues.redhat.com/browse/JBPM-9958](JBPM-9958)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1836
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
> JBPM-9958 Jsoup library upgrade

- appformer-js-monaco/pom.xml
- appformer-js/package.json
- appformer-js/pom.xml
- dashbuilder/dashbuilder-shared/dashbuilder-js/package.json
- dashbuilder/dashbuilder-shared/dashbuilder-js/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1558
https://github.com/kiegroup/appformer/pull/1217
https://github.com/kiegroup/kie-wb-common/pull/3709
https://github.com/kiegroup/kogito-apps/pull/1141
https://github.com/kiegroup/kogito-editors-java/pull/184
https://github.com/kiegroup/optaweb-employee-rostering/pull/730
https://github.com/kiegroup/optaweb-vehicle-routing/pull/614
https://github.com/kiegroup/process-migration-service/pull/37
https://github.com/kiegroup/lock-treatment-tool/pull/3
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1840
https://github.com/kiegroup/kie-jenkins-scripts/pull/1175
> BXMSPROD-1558 install lock-treatment-tool exec

- dashbuilder/dashbuilder-runtime/pom.xml
KOGITO-6404: Remove unused loggers in Dashbuilder
Backport
Merge with: https://github.com/kiegroup/kie-soup/pull/240
> KOGITO-6404: Remove unused loggers in Dashbuilder

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/RoleLoader.java
**AF-2923**: [Use SAXBuilder from jdom library only with not expanding Entities](https://issues.redhat.com/browse/AF-2923)
related PR : https://github.com/kiegroup/jbpm-designer/pull/924
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
> AF-2923 :Use SAXBuilder from jdom library only with not expanding Enities

- .github/workflows/pull_request.yml
- pom.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4222
* https://github.com/kiegroup/appformer/pull/1245
* https://github.com/kiegroup/kie-tools/pull/890
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each …
> RHPAM-4222 apache artemis to 2.19.1

- pom.xml
https://issues.redhat.com/browse/RHPAM-4222
* https://github.com/kiegroup/appformer/pull/1245
<details>
<summary>
</summary>
[build-chain …
> [7.67.x] apache.activemq.artemis moved to 2.19.1

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/filesystem/WildflyUserFileSystemManager.java
(cherry picked from commit 34d4090d7902a9ef1d259f1c01e95d9ea049fb80)
[DROOLS-6879](https://issues.redhat.com/browse/DROOLS-6879)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1924
* https://github.com/kiegroup/appformer/pull/1252
<details>
<summary>
</summary>
[build-chain …
> [7.67.x] DROOLS-6879 : Update to Wildfly core 17.x

- appformer-js-monaco/yarn.lock
- appformer-js/yarn.lock
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
**JIRA**: https://issues.redhat.com/browse/RHPAM-4271
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …
> RHPAM-4271 minimist npm library to 1.2.6

- appformer-js/yarn.lock
**JIRA**: [AF-2936](https://issues.redhat.com/browse/AF-2936)
**This PR includes the following fixes for security alerts by dependabot**
These packages have micro version updates
- y18n (3.2.1 to 3.2.2)
- lodash (4.17.11 to 4.17.21)
- ws (5.2.2 to 5.2.3)
- tar (2.2.1 to 2.2.2)
- path-parse (1.0.6 to 1.0.7)
- tmpl (1.0.4 to 1.0.5)
- async (2.6.2 to 2.6.4)
These Packages have minor version updates
- ajv (6.10.0 to 6.12.6)
- node-fetch (2.3.0 to 2.6.7)
- hosted-git-info (2.7.1 to 2.8.9)
I have run the sanity checks and found no regression for this update.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in …
> AF-2936: Check dependabot alerts on appformer repository

- appformer-js/package.json
- appformer-js/yarn.lock
- uberfire-services/uberfire-services-backend/src/main/java/org/guvnor/common/services/backend/file/upload/AbstractFileServlet.java
JIRA: [AF-2936](https://issues.redhat.com/browse/AF-2936)
**Referenced Pull Requests**:
https://github.com/kiegroup/kie-wb-common/pull/3735
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can …
> Upgrade react dependencies pointed by dependency bot

- pom.xml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4246
* https://github.com/kiegroup/appformer/pull/1273
* https://github.com/kiegroup/appformer/pull/1274
<details>
<summary>
</summary>
[build-chain …
> RHPAM-4246 `version.org.postgres-driver` property removed

- appformer-js/yarn.lock
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
To avoid problems with future PRs on this branch.
**Referenced Pull Requests**:
- https://github.com/kiegroup/appformer/pull/1282
- https://github.com/kiegroup/appformer/pull/1283
- https://github.com/kiegroup/kie-wb-common/pull/3738
- https://github.com/kiegroup/kie-wb-common/pull/3739
<details>
<summary>
</summary> …
> [7.67] Update yarn.lock

- appformer-js/yarn.lock
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
To avoid problems with future PRs on this branch.
**Referenced Pull Requests**:
- https://github.com/kiegroup/appformer/pull/1282
- https://github.com/kiegroup/appformer/pull/1283
- https://github.com/kiegroup/kie-wb-common/pull/3738
- https://github.com/kiegroup/kie-wb-common/pull/3739
<details>
<summary>
</summary> …
> [7.67-blue] Update yarn.lock

- pom.xml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4246
* https://github.com/kiegroup/appformer/pull/1273
* https://github.com/kiegroup/appformer/pull/1274
<details>
<summary>
</summary>
[build-chain …
> [7.67.x] RHPAM-4246 `version.org.postgres-driver` property removed

- .github/workflows/pull_request.yml
- pom.xml
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [7.67.x] apache.activemq.artemis moved to 2.19.1 (#1251)

- .github/workflows/pull_request.yml
- pom.xml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4222
* https://github.com/kiegroup/appformer/pull/1253
<details>
<summary>
</summary>
[build-chain …
> [7.67.x-blue] apache.activemq.artemis moved to 2.19.1

- dashbuilder/dashbuilder-shared/dashbuilder-js/package.json
- dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/package.json
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …
> RHPAM-4315: EventSource yarn.lock update

- appformer-js/package.json
- appformer-js/yarn.lock
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4243
I will backport it to 7.67.x and blue as soon as wee agree on this
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), …
> RHPAM-4243 CVE-2022-0235 lerna removed from appformer-js

- appformer-js/package.json
- appformer-js/yarn.lock
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4243
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
> [BLUE] lerna removed from appformer-js (#1293)

- appformer-js/package.json
- appformer-js/yarn.lock
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4243
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
> [7.67.x] lerna removed from appformer-js (#1293)

- dashbuilder/dashbuilder-shared/dashbuilder-js/package.json
- dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/package.json
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
**JIRA**: 
[RHPAM-4315](https://issues.redhat.com/browse/RHPAM-4315)
* Original PR: https://github.com/kiegroup/appformer/pull/1277
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a …
> RHPAM-4315: EventSource yarn.lock update (#1277)

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/CredentialsClientFactory.java
[KOGITO-7181](https://issues.redhat.com/browse/KOGITO-7181)
[ZIP](https://drive.google.com/file/d/1r3eyVTQLlbsV7i03ymDQESZ4S0_YLZkT/view?usp=sharing)
[war](https://drive.google.com/file/d/1NVju-ZTJcRJJcOrAlEBT_RftA-WleSHy/view?usp=sharing)
<details>
<summary>
</summary>
[build-chain …
> KOGITO-7181 : Remove default password on Uberfire's CredentialsClientFactory.java

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/CredentialsClientFactory.java
(cherry picked from commit dd33617d41243479b148ad6490275e13f24700a2)
[KOGITO-7181](https://issues.redhat.com/browse/KOGITO-7181)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> [7.67.x] KOGITO-7181 : Remove default password on Uberfire's CredentialsClientFactory.java

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/CredentialsClientFactory.java
(cherry picked from commit dd33617d41243479b148ad6490275e13f24700a2)
[KOGITO-7181](https://issues.redhat.com/browse/KOGITO-7181)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> [7.67.x-blue]KOGITO-7181 : Remove default password on Uberfire's CredentialsClientFactory.java

- dashbuilder/dashbuilder-shared/dashbuilder-js/package.json
- dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/package.json
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
(cherry picked from commit d0e73ada766de16de27ce9b91edd0d538ced1006)
**JIRA**: [RHPAM-4315](https://issues.redhat.com/browse/RHPAM-4315)
* https://github.com/kiegroup/appformer/pull/1294
<details>
<summary>
</summary>
[build-chain …
> [7.67.x-blue] RHPAM-4315: EventSource yarn.lock update (#1277)

- appformer-js-monaco/yarn.lock
- appformer-js/yarn.lock
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
**JIRA**:
- https://issues.redhat.com/browse/RHPAM-4271
- https://github.com/kiegroup/appformer/pull/1304
- https://github.com/kiegroup/kie-wb-common/pull/3778
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/753
- https://github.com/kiegroup/optaweb-employee-rostering/pull/854
- https://github.com/kiegroup/kogito-apps/pull/1461
Upgrade `minimist` package to version `1.2.6`.
If we agree I will backport this to `7.67.x-blue` branch.
**NB**: No need to fix this in `main` branch since it is already fixed.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and …
> [7.67.x] [RHPAM-4271] CVE-2021-44906: Upgrade minimist to 1.2.6

- appformer-js-monaco/yarn.lock
- appformer-js/yarn.lock
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-4271
- https://github.com/kiegroup/appformer/pull/1304
`Minimist` package upgrade backport
<details>
<summary>
</summary>
[build-chain …
> [7.67.x-BLUE] [RHPAM-4271] CVE-2021-44906: Upgrade minimist to 1.2.6

- pom.xml
**JIRA**:
- https://issues.redhat.com/browse/RHPAM-4448
- https://issues.redhat.com/browse/RHDM-1941
- https://issues.redhat.com/browse/RHPAM-4264
- https://issues.redhat.com/browse/RHDM-1901
**referenced Pull Requests**:  
- https://github.com/kiegroup/appformer/pull/1306
- https://github.com/kiegroup/appformer/pull/1307
- https://github.com/kiegroup/appformer/pull/1308
Upgrade org.webjars.bower.moment to 2.29.4
Solved CVEs:
- CVE-2022-24785
- CVE-2022-31129
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
>  [7.67.x-BLUE] [RHPAM-4448] [CVE-2022-31129 CVE-2022-24785] Upgrade moment to 2.29.4

- pom.xml
**JIRA**:
- https://issues.redhat.com/browse/RHPAM-4448
- https://issues.redhat.com/browse/RHDM-1941
- https://issues.redhat.com/browse/RHPAM-4264
- https://issues.redhat.com/browse/RHDM-1901
- https://github.com/kiegroup/appformer/pull/1306
- https://github.com/kiegroup/appformer/pull/1307
- https://github.com/kiegroup/appformer/pull/1308
Upgrade org.webjars.bower.moment to 2.29.4
Solved CVEs:
- CVE-2022-24785
- CVE-2022-31129
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
> [RHPAM-4448] [CVE-2022-31129 CVE-2022-24785] Upgrade moment to 2.29.4

- pom.xml
**JIRA**:
- https://issues.redhat.com/browse/RHPAM-4448
- https://issues.redhat.com/browse/RHDM-1941
- https://issues.redhat.com/browse/RHPAM-4264
- https://issues.redhat.com/browse/RHDM-1901
**referenced Pull Requests**:  
- https://github.com/kiegroup/appformer/pull/1306
- https://github.com/kiegroup/appformer/pull/1307
- https://github.com/kiegroup/appformer/pull/1308
Upgrade org.webjars.bower.moment to 2.29.4
Solved CVEs:
- CVE-2022-24785
- CVE-2022-31129
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
> [7.67.x] [RHPAM-4448] [CVE-2022-31129 CVE-2022-24785] Upgrade moment to 2.29.4

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProviderTest.java
**JIRA**: https://issues.redhat.com/browse/RHPAM-4525
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or …
> RHPAM-4525 ElasticSearchIndexProvider few tests removed

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProviderTest.java
**JIRA**: https://issues.redhat.com/browse/RHPAM-4525
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310
> [7.67.x] RHPAM-4525 ElasticSearchIndexProvider few tests removed

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-elasticsearch/src/test/java/org/uberfire/ext/metadata/backend/elastic/index/ElasticSearchIndexProviderTest.java
**JIRA**: https://issues.redhat.com/browse/RHPAM-4525
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310
> [7.67.x-blue] RHPAM-4525 ElasticSearchIndexProvider few tests removed

- uberfire-server/src/test/resources/expected-2-sample.html
- uberfire-server/src/test/resources/expected-3-sample.html
- uberfire-server/src/test/resources/expected-4-sample.html
- uberfire-server/src/test/resources/expected-sample.html
related to:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2098
* https://github.com/kiegroup/appformer/pull/1313
> Bump jsoup from 1.14.2 to 1.15.3

- uberfire-server/src/test/resources/expected-2-sample.html
- uberfire-server/src/test/resources/expected-3-sample.html
- uberfire-server/src/test/resources/expected-4-sample.html
- uberfire-server/src/test/resources/expected-sample.html
related to:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2098
* https://github.com/kiegroup/appformer/pull/1313
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2099
* https://github.com/kiegroup/appformer/pull/1314
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2100
* https://github.com/kiegroup/appformer/pull/1315
> [7.67.x] Bump jsoup from 1.14.2 to 1.15.3

- pom.xml
**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1798
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2051
- https://github.com/kiegroup/appformer/pull/1301
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2064
- https://github.com/kiegroup/appformer/pull/1302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2065
- https://github.com/kiegroup/appformer/pull/1303
Inherit lienzo version from `kie-bom`
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …
> [BXMSPROD-1798] Removed explicit lienzo version

- pom.xml
**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1798
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2051
- https://github.com/kiegroup/appformer/pull/1301
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2064
- https://github.com/kiegroup/appformer/pull/1302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2065
- https://github.com/kiegroup/appformer/pull/1303
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a …
> [7.67.x] [BXMSPROD-1798] Removed explicit lienzo dependencies, inherited from kie-bom

- uberfire-server/src/test/resources/expected-2-sample.html
- uberfire-server/src/test/resources/expected-3-sample.html
- uberfire-server/src/test/resources/expected-4-sample.html
- uberfire-server/src/test/resources/expected-sample.html
related to:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2098
* https://github.com/kiegroup/appformer/pull/1313
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2099
* https://github.com/kiegroup/appformer/pull/1314
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2100
* https://github.com/kiegroup/appformer/pull/1315
> [7.67.x-blue] Bump jsoup from 1.14.2 to 1.15.3

- pom.xml
**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1798
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2051
- https://github.com/kiegroup/appformer/pull/1301
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2064
- https://github.com/kiegroup/appformer/pull/1302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2065
- https://github.com/kiegroup/appformer/pull/1303
> [7.67.x-BLUE] [BXMSPROD-1798] Custom lienzo version property

- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/DistributionManagementArtifactRepository.java
[RHPAM-4509](https://issues.redhat.com/browse/RHPAM-4509)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need …
> RHPAM-4509 :Unable to deploy kjar to remote maven repository that requires access via proxy in Business Central

- dashbuilder/dashbuilder-runtime/src/main/resources/META-INF/ErraiApp.properties
- dashbuilder/dashbuilder-webapp/src/main/resources/META-INF/ErraiApp.properties
This is a follow up on PR #263 where @tomasdavidorg suggested to clean up also other remaining classes and commented code.
https://issues.redhat.com/browse/AF-2944
* https://github.com/kiegroup/kie-soup/pull/264
<details>
<summary>
</summary>
[build-chain …
> [BXMSPROD-1845] removed referenced ELSProviderType

- appformer-js-monaco/yarn.lock
- appformer-js/yarn.lock
- dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4663
* https://github.com/kiegroup/appformer/pull/1376
* https://github.com/kiegroup/kie-wb-common/pull/3800
* https://github.com/kiegroup/process-migration-service/pull/116
<details>
<summary>
</summary>
[build-chain …
> [CVE-2022-38900][RHPAM-4663] decode-uri-component to 0.2.2

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/BaseGitCommand.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHService.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderSSHBadConfigTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemImplProviderSSHTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHServiceTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/ModuleMavenRepositoryResolverImplTest.java
- uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/RepositoryResolverTestUtils.java
Upgrading sshd-core to 2.9.2
https://issues.redhat.com/browse/RHDM-1788 and https://issues.redhat.com/browse/RHPAM-3807
** Parent and dependent PRs **: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2202
* https://github.com/kiegroup/kie-wb-common/pull/3801
* https://github.com/kiegroup/jbpm-wb/pull/1587
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version …
> RHDM-1788: changes related to upgrade of sshd-core 2.9.2

- appformer-js-monaco/yarn.lock
- appformer-js/yarn.lock
[KOGITO-9215](https://issues.redhat.com/browse/KOGITO-9215)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …
> KOGITO-9215: Bump `loader-utils` to `v1.4.2` on `appformer-js` and `appformer-js-monaco` packages

- uberfire-backend/uberfire-backend-cdi/pom.xml
* https://github.com/kiegroup/kie-wb-distributions/pull/1223
* https://github.com/kiegroup/appformer/pull/1387
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2310
<details>
<summary>
</summary>
[build-chain …
> Bump xalan from 2.7.2 to 2.7.3

- pom.xml
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2488
* https://github.com/kiegroup/droolsjbpm-integration/pull/3063
* https://github.com/kiegroup/appformer/pull/1422
* https://github.com/kiegroup/jbpm/pull/2438
* https://github.com/kiegroup/kie-wb-distributions/pull/1245
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/649
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
> [7.67.x-blue] Updating mysql connector gav

- uberfire-io/src/test/java/org/uberfire/io/CommonIOExceptionsServiceDotFileTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-fs/src/test/java/org/uberfire/java/nio/fs/file/SimpleFileSystemProviderTest.java
Ensemble:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2492
https://github.com/kiegroup/kie-wb-common/pull/3831
https://github.com/kiegroup/drools/pull/76
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> [7.67.x-blue] Upgrade apache poi to 5.2.5
